(function(C){'use strict';const SKILLS=[
['arrays.linear_scan','Linear scan','Arrays',[]],['arrays.sliding_window','Sliding window','Arrays',['arrays.linear_scan']],['arrays.invariants','Window/pointer invariants','Arrays',['arrays.linear_scan']],['arrays.intervals','Intervals','Arrays',['arrays.sorting']],['arrays.sorting','Sorting transformations','Arrays',[]],
['hash.sets','Set membership','Hashing',[]],['hash.frequency','Frequency maps','Hashing',['hash.sets']],['python.hashability','Hashability','Python',[]],['python.counter','Counter/defaultdict','Python',['hash.frequency']],['python.heapq','heapq','Python',[]],['python.deque','deque','Python',[]],['python.sort_keys','Sorting keys/tuples','Python',[]],['python.mutability','Mutability/copying','Python',[]],
['search.binary','Binary search','Search',[]],['search.boundaries','Binary-search boundaries','Search',['search.binary']],
['stack.basic','Stack semantics','Structures',[]],['stack.monotonic','Monotonic stack','Structures',['stack.basic']],['heap.top_k','Top-k heaps','Structures',['python.heapq']],
['graphs.dfs','DFS traversal','Graphs',[]],['graphs.bfs','BFS traversal','Graphs',['python.deque']],['graphs.multi_source','Multi-source BFS','Graphs',['graphs.bfs']],['graphs.cycle_detection','Cycle detection','Graphs',['graphs.dfs']],['graphs.topological','Topological sort','Graphs',['graphs.cycle_detection']],
['dp.recurrence','DP recurrence','Dynamic Programming',[]],['dp.space_optimization','DP space optimization','Dynamic Programming',['dp.recurrence']],['dp.grid','Grid DP','Dynamic Programming',['dp.recurrence']],
['complexity.time','Time complexity','Foundations',[]],['complexity.space','Space complexity','Foundations',[]],['reasoning.edge_cases','Edge-case reasoning','Foundations',[]],['testing.regression','Regression-test design','Engineering',[]]
].map(([id,name,group,prereq])=>({id,name,group,prereq}));
const BASE_MAP={
 'two-sum':['hash.sets','complexity.time'],'valid-parens':['stack.basic','reasoning.edge_cases'],'max-profit':['arrays.linear_scan','arrays.invariants'],'binary-search':['search.binary','reasoning.edge_cases'],'longest-substring':['arrays.sliding_window','arrays.invariants'],'three-sum':['arrays.sorting','arrays.invariants'],'num-islands':['graphs.dfs','graphs.bfs'],'coin-change':['dp.recurrence','dp.space_optimization']};
class SkillGraph{constructor(){this.key='codeopolis-phase26-skills-v1';this.data=this.load()}load(){try{return Object.assign({evidence:{}},JSON.parse(localStorage.getItem(this.key)||'{}'))}catch{return{evidence:{}}}}save(){localStorage.setItem(this.key,JSON.stringify(this.data))}challengeSkills(c){return c.skillIds||BASE_MAP[c.id]||[]}record(challengeId){const c=typeof CHALLENGES!=='undefined'?CHALLENGES.find(x=>x.id===challengeId):null;if(!c)return;const now=Date.now();for(const id of this.challengeSkills(c)){const e=this.data.evidence[id]||{passes:0,challengeIds:[],firstAt:null,lastAt:null};e.passes++;e.firstAt=e.firstAt||now;e.lastAt=now;if(!e.challengeIds.includes(challengeId))e.challengeIds.push(challengeId);this.data.evidence[id]=e}this.save()}status(id){const e=this.data.evidence[id];if(!e)return'Unseen';if(e.passes===0)return'Seen';if(e.challengeIds.length===1&&e.passes===1)return'Solved';if(e.challengeIds.length>=2||e.passes>=2){if(e.firstAt&&e.lastAt-e.firstAt>=24*60*60*1000)return'Retained';return'Mastered'}return'Solved'}snapshot(){return SKILLS.map(s=>({...s,status:this.status(s.id),evidence:this.data.evidence[s.id]||null}))}weakest(limit=6){const rank={Unseen:0,Seen:1,Solved:2,Mastered:3,Retained:4};return this.snapshot().sort((a,b)=>rank[a.status]-rank[b.status]).slice(0,limit)}grouped(){const out={};for(const s of this.snapshot())(out[s.group]||(out[s.group]=[])).push(s);return out}}
C.register('SkillGraph',SkillGraph);window.Phase26Skills=SKILLS;})(window.Codeopolis);