(function(C){
  'use strict';
  function boot(){
    if(C.game)return;
    const canvas=document.getElementById('cityCanvas');if(!canvas||typeof state==='undefined')return;
    const World=C.get('WorldSystem'),Camera=C.get('IsoCamera'),Simulation=C.get('CitySimulation'),Renderer=C.get('CityRenderer'),Audio=C.get('AudioSystem'),Rewards=C.get('RewardEngine'),UI=C.get('GameUI');
    if(!World||!Camera||!Simulation||!Renderer||!Audio||!Rewards||!UI){console.error('Phase 6 modules failed to load');return}

    const world=new World(state),camera=new Camera(canvas,world.world.camera),simulation=new Simulation(world,state),audio=new Audio(world),renderer=new Renderer(canvas,world,camera,simulation,state),rewards=new Rewards(state,world,audio),ui=new UI(world,camera,renderer,audio,rewards);
    C.game={world,camera,simulation,audio,renderer,rewards,ui,startedAt:Date.now(),requestDraw:()=>renderer.requestDraw()};

    // Preserve the proven learning app while routing city rendering through the new engine.
    if(typeof renderCityCanvas==='function')renderCityCanvas=function(){renderer.requestDraw()};

    if(typeof render==='function'){
      const legacyRender=render;
      render=function(){legacyRender();ui.refresh();renderer.requestDraw();const phase=document.getElementById('phaseLabel');if(phase)phase.textContent='Phase 6 · Living Codeopolis'};
    }

    // Present the reward delta generated by the existing judge instead of replacing its economy.
    if(typeof submitCode==='function'){
      const legacySubmit=submitCode;
      submitCode=async function(){
        const challenge=typeof current==='function'?current():null;if(!challenge)return legacySubmit.apply(this,arguments);
        const before=rewards.snapshot(challenge);const result=await legacySubmit.apply(this,arguments);const event=rewards.resolve(before,challenge);
        if(event){persist(false);render()}return result;
      };
    }

    // New purchases become physical placement decisions instead of instantly materializing in a fixed grid.
    if(typeof buyBuilding==='function'){
      const legacyBuy=buyBuilding;
      buyBuilding=function(id){
        const before=(state.buildings||[]).length;const result=legacyBuy.apply(this,arguments);
        if((state.buildings||[]).length>before){world.setTool('building',id);persist(false);if(typeof switchTab==='function')switchTab('city');ui.refresh();ui.toast(`${world.buildingDef(id)?.icon||'🏗️'} Purchased. Choose its location on the city map.`)}
        return result;
      };
    }

    // Successful recall is a meaningful action too, but only correctness earns the micro reinforcement.
    if(typeof answerRecall==='function'){
      const legacyRecall=answerRecall;
      answerRecall=function(){const before=state.learning?.recallCorrect||0;const result=legacyRecall.apply(this,arguments);if((state.learning?.recallCorrect||0)>before){rewards.recordRecall(true);persist(false);ui.refresh()}return result};
    }

    if(typeof resetGame==='function'){
      const legacyReset=resetGame;
      resetGame=function(){const oldState=state;const result=legacyReset.apply(this,arguments);if(state!==oldState)location.reload();return result};
    }

    // Keep the accelerated world clock and camera position without hammering localStorage every animation frame.
    setInterval(()=>{try{persist(false)}catch{}},30000);

    let last=performance.now();
    function frame(now){const dt=Math.max(0,(now-last)/1000);last=now;if(!document.hidden)simulation.update(dt);renderer.render(now);requestAnimationFrame(frame)}
    requestAnimationFrame(frame);

    C.events.on('learning:mastered',e=>{const target=world.districtTile(e.challenge.district);if(target)renderer.focus(target,800)});
    C.events.on('world:road-changed',()=>{persist(false);ui.refresh()});
    C.events.on('world:building-unplaced',()=>{persist(false);ui.refresh()});
    window.addEventListener('resize',()=>renderer.requestDraw());

    world.resetCamera();render();
    C.events.emit('phase6:ready',{version:C.version});
  }

  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(window.Codeopolis);
