(function(C){
  'use strict';
  const DEBUG_SCENARIOS=[
    {id:'debug-two-sum',title:'Production Incident: Duplicate Pair Lookup',diff:'Medium',pattern:'Debugging / Hash Map',district:'hash',fn:'debug_two_sum',money:300,rp:55,prompt:'The implementation sometimes reuses the same index. Repair it so it returns two distinct indices whose values sum to target.',starter:'def debug_two_sum(nums, target):\n    seen = {}\n    for i, x in enumerate(nums):\n        seen[x] = i  # BUG: update happens before lookup\n        need = target - x\n        if need in seen:\n            return [seen[need], i]\n    return []',hint:'Ask whether the current value should enter the map before or after checking its complement.',lesson:'Debugging invariants matters: the lookup structure should represent only prior elements at the moment you query it.',complexity:'O(n) time · O(n) space',public:[['([2,7,11,15], 9)','[0,1]'],['([3,3], 6)','[0,1]']],hidden:[['([3,2,4], 6)','[1,2]']]},
    {id:'debug-binary-search',title:'Production Incident: Search Boundary Loop',diff:'Medium',pattern:'Debugging / Binary Search',district:'search',fn:'debug_search',money:320,rp:60,prompt:'This binary search can miss boundary values. Repair the loop and pointer updates.',starter:'def debug_search(nums, target):\n    left, right = 0, len(nums) - 1\n    while left < right:  # BUG\n        mid = (left + right) // 2\n        if nums[mid] == target:\n            return mid\n        if nums[mid] < target:\n            left = mid  # BUG\n        else:\n            right = mid - 1\n    return -1',hint:'With inclusive boundaries, the loop should still inspect the final candidate and every pointer update must shrink the interval.',lesson:'Most binary-search bugs are invariant violations at the boundaries.',complexity:'O(log n) time · O(1) space',public:[['([1,3,5,7], 7)','3'],['([1,3,5,7], 1)','0']],hidden:[['([5], 5)','0'],['([1,2,3], 4)','-1']]},
    {id:'debug-window',title:'Performance Incident: Quadratic Telemetry Scan',diff:'Medium',pattern:'Debugging / Sliding Window',district:'arrays',fn:'debug_max_sum',money:340,rp:65,prompt:'This service recomputes every k-sized window from scratch. Rewrite it to return the maximum window sum in linear time.',starter:'def debug_max_sum(nums, k):\n    best = None\n    for i in range(len(nums) - k + 1):\n        total = sum(nums[i:i+k])  # PERFORMANCE BUG: repeated work\n        best = total if best is None else max(best, total)\n    return best if best is not None else 0',hint:'Carry the previous window sum forward: subtract the element leaving and add the element entering.',lesson:'Performance debugging often means identifying repeated work and preserving exactly the state needed to avoid recomputation.',complexity:'O(n) time · O(1) extra space',public:[['([1,2,3,4,5], 3)','12'],['([5,-2,3,4], 2)','7']],hidden:[['([], 3)','0'],['([1], 1)','1']]}
  ];
  class DebuggingSystem{
    constructor(state,characters){this.state=state;this.characters=characters;this.data=this.ensure();this.inject()}
    ensure(){const old=this.state.debugging||{};return this.state.debugging={version:1,completed:old.completed||[],history:old.history||[],active:old.active||null}}
    inject(){if(typeof CHALLENGES==='undefined')return;for(const d of DEBUG_SCENARIOS)if(!CHALLENGES.some(c=>c.id===d.id))CHALLENGES.push(d)}
    available(){return DEBUG_SCENARIOS.filter(d=>!this.data.completed.includes(d.id))}
    start(id){const d=DEBUG_SCENARIOS.find(x=>x.id===id);if(!d)return false;this.data.active=id;if(typeof selectChallenge==='function')selectChallenge(id);if(typeof switchTab==='function')switchTab('challenge');C.events.emit('debugging:started',{scenario:d});return true}
    onMastered(e){if(!e.challenge?.id?.startsWith('debug-'))return false;const id=e.challenge.id;if(!this.data.completed.includes(id))this.data.completed.push(id);this.data.history.unshift({id,at:new Date().toISOString()});this.data.history=this.data.history.slice(0,20);this.data.active=null;this.state.money=(this.state.money||0)+120;this.state.research=(this.state.research||0)+25;this.characters?.award?.('theo',10,'production debugging incident');C.events.emit('debugging:resolved',{scenario:e.challenge});return true}
  }
  DebuggingSystem.SCENARIOS=DEBUG_SCENARIOS;C.register('DebuggingSystem',DebuggingSystem);
})(window.Codeopolis);
