(function(C){
  'use strict';
  class Phase10UI{
    constructor(game,llm,missions,incidents,sim){this.game=game;this.llm=llm;this.missions=missions;this.incidents=incidents;this.sim=sim}
    ensureTab(){if(document.getElementById('operationsTab'))return;const tabs=document.querySelector('.tabs');if(tabs){const b=document.createElement('button');b.dataset.tab='operations';b.textContent='🛰️ Ops';tabs.appendChild(b);b.onclick=()=>switchTab('operations')}const host=document.querySelector('.panel');const div=document.createElement('div');div.id='operationsTab';div.className='hidden';host.appendChild(div)}
    refresh(){this.ensureTab();const el=document.getElementById('operationsTab');if(!el)return;const mission=this.missions.data.active,incident=this.incidents.current(),sim=this.sim.active();el.innerHTML=`<div class="phase10-grid">
      <section class="shop-item"><h3>🧠 Intelligent Interviewer</h3><p class="muted">Local evaluation is always available. Optionally point Codeopolis at your own server-side LLM proxy; never put an API key in this page.</p><input id="llmEndpoint" class="p10-input" placeholder="https://your-proxy.example/interview" value="${this.escape(this.llm.config.endpoint||'')}"><div class="actions"><button class="btn" onclick="Codeopolis.game.phase10.ui.saveEndpoint()">Save endpoint</button><span class="tag">${this.llm.enabled()?'LLM enabled':'Local fallback'}</span></div></section>
      <section class="shop-item"><h3>👥 Mentor Mission</h3>${mission?`<b>${this.escape(mission.title)}</b><p>${this.escape(mission.brief)}</p><p class="muted">Reward: 💰 ${mission.rewardMoney} · 🔬 ${mission.rewardResearch}</p><button class="btn primary" onclick="Codeopolis.game.phase10.missions.accept()">Open mission</button>`:`<p class="muted">Generate a mission from your weakest retained district.</p><button class="btn" onclick="Codeopolis.game.phase10.ui.generateMission()">Ask the team</button>`}</section>
      <section class="shop-item"><h3>🚨 Engineering Incident</h3>${this.renderIncident(incident)}</section>
      <section class="shop-item"><h3>🧱 Load Lab</h3>${this.renderSim(sim)}</section>
    </div>`}
    renderIncident(a){if(!a)return(this.incidents.constructor.INCIDENTS||[]).map(x=>`<button class="btn" style="margin:3px" onclick="Codeopolis.game.phase10.ui.startIncident('${x.id}')">${x.icon} ${x.title}</button>`).join('');const stages=['Diagnose','Repair','Scale / architecture','Postmortem'];return`<b>${a.icon} ${this.escape(a.title)}</b><p>Stage ${a.stage+1}/4 · ${stages[a.stage]}</p>${a.stage===0?`<textarea id="incidentText" class="p10-text" placeholder="Describe the likely root cause, invariant, and evidence..."></textarea><button class="btn primary" onclick="Codeopolis.game.phase10.ui.incidentNext()">Submit diagnosis</button>`:a.stage===1?`<button class="btn primary" onclick="Codeopolis.game.phase10.incidents.openRepair()">Open judged repair</button>`:a.stage===2?`<textarea id="incidentText" class="p10-text" placeholder="How would this behave at scale? What architecture or monitoring changes matter?"></textarea><button class="btn primary" onclick="Codeopolis.game.phase10.ui.incidentNext()">Defend engineering plan</button>`:`<textarea id="incidentText" class="p10-text" placeholder="Write a concise postmortem: impact, root cause, detection, prevention, owner..."></textarea><button class="btn good" onclick="Codeopolis.game.phase10.ui.incidentNext()">Complete incident</button>`}`}
    renderSim(a){if(!a)return`<p class="muted">Turn a Phase 9 design into a live system under increasing load.</p>${(this.game.phase9.design.constructor.SCENARIOS||[]).map(s=>`<button class="btn" style="margin:3px" onclick="Codeopolis.game.phase10.ui.startSim('${s.id}')">${s.icon} ${s.name}</button>`).join('')}`;const d=this.game.phase9.design.data.active,scenario=this.game.phase9.design.scenario(a.id),loads=this.sim.constructor.LOADS||[];return`<b>${scenario.icon} ${scenario.name}</b><p>Load: ${(loads[a.loadIndex]||0).toLocaleString()} RPS · latency ${a.metrics.latency}ms · errors ${a.metrics.errorRate}%</p><div>${scenario.components.map(c=>`<button class="btn ${d?.selected.includes(c)?'good':''}" style="margin:2px" onclick="Codeopolis.game.phase10.ui.toggleComponent('${this.escapeAttr(c)}')">${c}</button>`).join('')}</div><p class="muted">Failures: ${a.failures.join('; ')||'none observed'}</p><div class="actions"><button class="btn primary" onclick="Codeopolis.game.phase10.ui.raiseLoad()">Increase load</button><button class="btn" onclick="Codeopolis.game.phase10.ui.finishSim()">Finish review</button></div>`}
    saveEndpoint(){this.llm.saveConfig({endpoint:document.getElementById('llmEndpoint')?.value.trim()||''});persist(false);this.refresh()}
    generateMission(){this.missions.generate(true);persist(false);this.refresh()}
    startIncident(id){this.incidents.start(id);persist(false);this.refresh()}
    incidentNext(){const a=this.incidents.current(),text=document.getElementById('incidentText')?.value||'';if(!a)return;if(a.stage===0)this.incidents.submitDiagnosis(text);else if(a.stage===2)this.incidents.submitEngineeringAnswer(text);else if(a.stage===3)this.incidents.finish(text);persist(false);render()}
    startSim(id){this.sim.start(id);persist(false);this.refresh()}
    toggleComponent(c){this.sim.toggle(c);persist(false);this.refresh()}
    raiseLoad(){this.sim.increaseLoad();persist(false);this.refresh()}
    finishSim(){const explanation=prompt('Explain your scaling and failure-handling decisions:')||'';this.sim.finish(explanation);persist(false);render()}
    escape(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    escapeAttr(s){return String(s).replace(/'/g,"\\'")}
  }
  C.register('Phase10UI',Phase10UI);
})(window.Codeopolis);
