(function(C){
  'use strict';
  class NarrativeSystem{
    constructor(state,characters,recruiting){this.state=state;this.characters=characters;this.recruiting=recruiting;this.data=this.ensure()}
    ensure(){const old=this.state.narrative||{};return this.state.narrative={version:1,seen:old.seen||[],feed:old.feed||[],active:old.active||null}}
    push(kind,title,text,characterId=null,meta={}){const item={id:`${kind}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,kind,title,text,characterId,meta,at:new Date().toISOString()};this.data.feed.unshift(item);this.data.feed=this.data.feed.slice(0,50);this.data.active=item;C.events.emit('story:beat',item);return item}
    once(id,fn){if(this.data.seen.includes(id))return;this.data.seen.push(id);fn()}
    evaluate(){const solved=(this.state.solved||[]).length,rank=this.state.career?.rank||0;if(solved>=3)this.once('maya-intro',()=>this.push('mentor','Maya checks in','You are past the tutorial stage. Start naming the pattern before you touch the keyboard.','maya'));if(solved>=8)this.once('theo-prod',()=>this.push('mentor','Theo opens the profiler','Correctness got you here. Now start noticing when your state can be reduced and when the input shape gives you leverage.','theo'));if(solved>=12)this.once('marcus-communication',()=>this.push('mentor','Marcus schedules a whiteboard review','From here on, interview readiness means explaining why the approach works, not only producing code.','marcus'));if(rank>=2)this.once('jin-architecture',()=>this.push('mentor','Jin joins the council','At senior level, every algorithm is also a systems decision: invariants, failure modes, interfaces.','jin'));if(rank>=3)this.once('ada-founder',()=>this.push('mentor','Ada makes an offer','You have enough leverage to choose a direction, not just pass a loop. Build the city around the engineer you intend to become.','ada'))}
    onMastery(e){this.evaluate();const c=this.characters.bestForDistrict(e.challenge?.district);if(!c)return;const text=e.first?`${e.challenge.title} is now part of your toolkit. ${this.tip(c.id,e.challenge?.district)}`:`Good review. Durable skill is what still works after the syntax fades.`;this.push('reaction',`${c.name} reacts`,text,c.id,{challengeId:e.challenge?.id})}
    onCrisis(c){const mentor=this.characters.bestForDistrict(c.district);if(mentor)this.push('crisis',`${mentor.name}: ${c.title}`,`This incident maps to ${c.district} reasoning. Fix the underlying model, not just the symptom.`,mentor.id,{crisisId:c.id})}
    onRecruiter(company){this.push('recruiting',`${company.icon} ${company.name} reached out`,`${company.offer}. They are interested because your current mastery profile matches their ${company.focus.join(' + ')} work.`, 'ada',{companyId:company.id})}
    tip(id,d){const tips={maya:'Before coding, state the invariant that must stay true.',theo:'Ask what data you truly need to keep in memory.',luna:'Treat the failed cases as experimental evidence.',marcus:'Say the tradeoff out loud as if an interviewer asked why.',jin:'Name the boundary conditions before implementation.',ada:'Think about what this skill unlocks beyond the interview.'};return tips[id]||`Keep strengthening ${d}.`}
  }
  C.register('NarrativeSystem',NarrativeSystem);
})(window.Codeopolis);
