(function(C){
  'use strict';
  class Phase8UI{
    constructor(game,characters,narrative,recruiting,encounters){this.game=game;this.characters=characters;this.narrative=narrative;this.recruiting=recruiting;this.encounters=encounters;this.install();this.bind()}
    install(){
      const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-tab="story"]')){const b=document.createElement('button');b.dataset.tab='story';b.textContent='👥 Team';const strategy=tabs.querySelector('[data-tab="strategy"]');tabs.insertBefore(b,strategy||tabs.lastElementChild);const host=document.querySelector('.panel');const div=document.createElement('div');div.id='storyTab';div.className='hidden';host.insertBefore(div,document.getElementById('statsTab'));b.onclick=()=>switchTab('story')}
      if(!document.getElementById('storyOverlay')){const o=document.createElement('div');o.id='storyOverlay';o.className='story-overlay';o.innerHTML='<div id="storyOverlayCard" class="story-overlay-card"></div>';document.body.appendChild(o);o.onclick=e=>{if(e.target===o||e.target.closest('[data-story-close]'))o.classList.remove('show')}}
      this.refresh()
    }
    bind(){
      C.events.on('story:beat',b=>{this.showBeat(b);this.refresh()});
      C.events.on('story:recruiter-message',()=>this.refresh());
      C.events.on('story:relationship',()=>this.refresh());
      C.events.on('story:character-unlocked',e=>{this.toast(`${e.def.icon} ${e.def.name} joined your team`);this.refresh()});
      C.events.on('story:communication-prompt',e=>this.showCommunication(e));
      C.events.on('story:interview-finished',e=>{this.showInterviewResult(e);this.refresh()});
    }
    refresh(){this.renderStory();this.renderMissionControl()}
    renderStory(){
      const root=document.getElementById('storyTab');if(!root)return;const active=this.recruiting.current();
      root.innerHTML=`<div class="story-grid"><section class="story-card"><h3>👥 Engineering Team</h3><div class="team-grid">${this.characters.unlocked().map(c=>{const r=this.characters.relationship(c.id);return `<button class="person-card" data-person="${c.id}"><span>${c.icon}</span><b>${c.name}</b><small>${c.role}</small><div class="relationship-bar"><i style="width:${Math.min(100,(r.xp%100))}%"></i></div><em>Relationship Lv ${r.level}</em></button>`}).join('')}</div></section><section class="story-card"><h3>📨 Recruiting Inbox</h3>${active?this.activeInterviewHTML(active):this.offerHTML()}</section></div><div class="story-card"><h3>📖 City Story Feed</h3><div class="story-feed">${this.narrative.data.feed.slice(0,12).map(x=>{const c=x.characterId?this.characters.def(x.characterId):null;return `<button class="story-feed-item" data-beat="${x.id}"><span>${c?.icon||'🏙️'}</span><div><b>${this.esc(x.title)}</b><small>${this.esc(x.text)}</small></div></button>`}).join('')||'<span class="muted">Your team will react as the civilization and your interview skills develop.</span>'}</div></div>`;
      root.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>this.showPerson(b.dataset.person));root.querySelectorAll('[data-beat]').forEach(b=>{const beat=this.narrative.data.feed.find(x=>x.id===b.dataset.beat);b.onclick=()=>beat&&this.showBeat(beat)});root.querySelectorAll('[data-start-company]').forEach(b=>b.onclick=()=>{if(this.recruiting.start(b.dataset.startCompany)){persist(false);this.encounters.openCurrentProblem();this.refresh()}});root.querySelectorAll('[data-decline-company]').forEach(b=>b.onclick=()=>{this.recruiting.decline(b.dataset.declineCompany);persist(false);this.refresh()});const resume=root.querySelector('[data-resume-interview]');if(resume)resume.onclick=()=>this.encounters.openCurrentProblem()
    }
    offerHTML(){const offers=this.recruiting.data.offers.map(id=>this.recruiting.company(id)).filter(Boolean);return offers.length?offers.map(c=>`<div class="recruit-card"><div><span class="recruit-icon">${c.icon}</span><b>${c.name}</b><small>${c.offer}</small><em>Focus: ${c.focus.join(' + ')}</em></div><div><button class="btn primary mini" data-start-company="${c.id}">Interview</button><button class="btn mini" data-decline-company="${c.id}">Pass</button></div></div>`).join(''):'<div class="muted">No active offers. Companies reach out when your solved breadth, career level, and retained Knowledge Index match their needs.</div>'}
    activeInterviewHTML(a){const c=this.recruiting.company(a.companyId),done=a.problemIds.filter(id=>a.passed[id]).length;return `<div class="active-story-interview"><span class="tag">INTERVIEW LOOP</span><h3>${c.icon} ${c.name}</h3><p>${c.offer}</p><div class="interview-round-track">${a.problemIds.map((id,i)=>`<span class="${a.passed[id]?'done':i===a.round?'current':''}">${a.passed[id]?'✓':i+1}</span>`).join('')}</div><div class="muted">${done}/${a.problemIds.length} coding rounds passed. Each successful coding round is followed by a communication decision.</div><button class="btn primary" data-resume-interview>Continue interview</button></div>`}
    renderMissionControl(){const sidebar=document.querySelector('.sidebar');if(!sidebar)return;let el=document.getElementById('phase8StoryCard');if(!el){el=document.createElement('div');el.id='phase8StoryCard';el.className='phase8-sidebar-card';const mission=document.getElementById('mission');sidebar.insertBefore(el,mission)}const active=this.recruiting.current(),beat=this.narrative.data.feed[0],offers=this.recruiting.data.offers.length;el.innerHTML=active?`<b>🎙️ ${this.recruiting.company(active.companyId).name} interview active</b><small>Round ${active.round+1}/${active.problemIds.length}</small><button class="btn mini primary" data-phase8-resume>Resume</button>`:beat?`<b>${beat.characterId?this.characters.def(beat.characterId)?.icon:'📖'} ${this.esc(beat.title)}</b><small>${this.esc(beat.text)}</small>${offers?`<button class="btn mini" data-open-story>${offers} recruiting message${offers>1?'s':''}</button>`:''}`:'<span class="muted">Your engineering team will react to meaningful progress.</span>';el.querySelector('[data-phase8-resume]')?.addEventListener('click',()=>this.encounters.openCurrentProblem());el.querySelector('[data-open-story]')?.addEventListener('click',()=>switchTab('story'))}
    showPerson(id){const c=this.characters.def(id),r=this.characters.relationship(id);if(!c||!r)return;this.modal(`<button class="story-close" data-story-close>×</button><div class="person-modal-icon">${c.icon}</div><h2>${c.name}</h2><div class="tag">${c.role}</div><p>${this.esc(c.intro)}</p><div class="person-specialties">${c.specialties.map(s=>`<span>${s}</span>`).join('')}</div><p><b>Relationship level ${r.level}</b> · ${r.xp} XP</p>${r.lastEvent?`<small class="muted">Latest: ${this.esc(r.lastEvent.reason)}</small>`:''}`)}
    showBeat(b){const c=b.characterId?this.characters.def(b.characterId):null;this.modal(`<button class="story-close" data-story-close>×</button><div class="person-modal-icon">${c?.icon||'🏙️'}</div><span class="tag">${b.kind.toUpperCase()}</span><h2>${this.esc(b.title)}</h2><p>${this.esc(b.text)}</p>${c?`<small>${c.name} · ${c.role}</small>`:''}`)}
    showCommunication(e){const p=e.prompt;this.modal(`<div class="communication-prompt"><span class="tag">INTERVIEW FOLLOW-UP</span><h2>🎙️ Explain your thinking</h2><p>${this.esc(p.q)}</p>${p.options.map((o,i)=>`<button class="communication-option" data-comm="${i}">${this.esc(o)}</button>`).join('')}</div>`);document.querySelectorAll('[data-comm]').forEach(b=>b.onclick=()=>{this.encounters.answer(Number(b.dataset.comm));document.getElementById('storyOverlay').classList.remove('show');persist(false);this.refresh()})}
    showInterviewResult(e){const r=e.record;this.modal(`<button class="story-close" data-story-close>×</button><div class="person-modal-icon">${r.passed?'🏆':'📋'}</div><span class="tag">INTERVIEW COMPLETE</span><h2>${e.company.name}</h2><p><b>${r.score}/100</b> · ${r.coding}/${r.total} coding rounds</p><p>${r.passed?`Offer earned: ${e.company.offer}. Your city receives an interview-performance bonus.`:'No offer this time. The result is saved as practice evidence; keep strengthening the weakest rounds and try future opportunities.'}</p>`)}
    modal(html){const o=document.getElementById('storyOverlay'),c=document.getElementById('storyOverlayCard');if(!o||!c)return;c.innerHTML=html;o.classList.add('show')}
    toast(m){this.game.ui?.toast?.(m)}
    esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  }
  C.register('Phase8UI',Phase8UI);
})(window.Codeopolis);
