const PYODIDE_VERSION='314.0.3';
const CHALLENGES=[
{id:'two-sum',title:'Two Sum',diff:'Easy',pattern:'Hash Map',fn:'two_sum',money:100,rp:15,prompt:'Given nums and target, return the indices of two numbers that add to target.',starter:'def two_sum(nums, target):\n    # Return two indices whose values add to target\n    pass',hint:'Store each number you have seen in a dictionary mapping value → index. For x, look for target - x.',lesson:'Hash maps trade memory for fast lookup. This turns a nested O(n²) search into O(n).',complexity:'O(n) time · O(n) space',public:[['([2,7,11,15], 9)','[0,1]'],['([3,2,4], 6)','[1,2]']],hidden:[['([3,3], 6)','[0,1]'],['([-1,-2,-3,-4,-5], -8)','[2,4]']]},
{id:'valid-parens',title:'Valid Parentheses',diff:'Easy',pattern:'Stack',fn:'is_valid',money:110,rp:18,prompt:'Return True when (), {}, and [] are correctly nested and closed.',starter:'def is_valid(s):\n    pass',hint:'Push opening brackets onto a stack. For each closer, verify it matches the most recent opener.',lesson:'Stacks model nested state: the last thing opened must be the first thing closed.',complexity:'O(n) time · O(n) space',public:[["('()[]{}',)",'True'],["('(]',)",'False']],hidden:[["('([{}])',)",'True'],["('(',)",'False'],["('',)",'True']]},
{id:'max-profit',title:'Best Time to Buy and Sell Stock',diff:'Easy',pattern:'One Pass',fn:'max_profit',money:120,rp:20,prompt:'Given daily prices, return the maximum profit from one buy followed by one later sell.',starter:'def max_profit(prices):\n    pass',hint:'Track the cheapest price seen so far and the best profit if you sold today.',lesson:'Many array problems collapse to a few pieces of state maintained during one linear scan.',complexity:'O(n) time · O(1) space',public:[["([7,1,5,3,6,4],)",'5'],["([7,6,4,3,1],)",'0']],hidden:[["([1,2],)",'1'],["([2,4,1],)",'2']]},
{id:'binary-search',title:'Binary Search',diff:'Easy',pattern:'Binary Search',fn:'search',money:130,rp:22,prompt:'Given sorted nums and target, return its index or -1.',starter:'def search(nums, target):\n    pass',hint:'Maintain left/right boundaries. Compare the midpoint and discard half the search range.',lesson:'Binary search is about maintaining a correct search invariant.',complexity:'O(log n) time · O(1) space',public:[["([-1,0,3,5,9,12], 9)",'4'],["([-1,0,3,5,9,12], 2)",'-1']],hidden:[["([5], 5)",'0'],["([2,5], 2)",'0'],["([], 1)",'-1']]},
{id:'longest-substring',title:'Longest Substring Without Repeating Characters',diff:'Medium',pattern:'Sliding Window',fn:'length_of_longest_substring',money:220,rp:40,prompt:'Return the length of the longest substring containing no repeated characters.',starter:'def length_of_longest_substring(s):\n    pass',hint:'Keep a left boundary and a map/set for the current window. Move left when a repeat invalidates it.',lesson:'Sliding windows maintain a valid contiguous region while one boundary advances.',complexity:'O(n) time · O(k) space',public:[["('abcabcbb',)",'3'],["('bbbbb',)",'1']],hidden:[["('pwwkew',)",'3'],["('',)",'0'],["('dvdf',)",'3']]},
{id:'three-sum',title:'3Sum',diff:'Medium',pattern:'Two Pointers',fn:'three_sum',money:260,rp:45,prompt:'Return all unique triplets whose values sum to zero.',starter:'def three_sum(nums):\n    pass',hint:'Sort first. Fix one value, then solve the remaining two-sum search using left/right pointers.',lesson:'Sorting can expose structure that makes pointer movement meaningful.',complexity:'O(n²) time · O(1) extra space excluding output',normalize:'triplets',public:[["([-1,0,1,2,-1,-4],)",'[[-1,-1,2],[-1,0,1]]'],["([0,1,1],)",'[]']],hidden:[["([0,0,0],)",'[[0,0,0]]'],["([],)",'[]'],["([-2,0,1,1,2],)",'[[-2,0,2],[-2,1,1]]']]},
{id:'num-islands',title:'Number of Islands',diff:'Medium',pattern:'DFS / BFS',fn:'num_islands',money:300,rp:55,prompt:'Count connected groups of land ("1") in a 2D grid using horizontal/vertical adjacency.',starter:'def num_islands(grid):\n    pass',hint:'When you find unvisited land, increment the count and flood-fill that whole island with DFS or BFS.',lesson:'Graph traversal appears even when the input is presented as a grid.',complexity:'O(rows × cols) time · O(rows × cols) worst-case space',public:[["([['1','1','1','1','0'],['1','1','0','1','0'],['1','1','0','0','0'],['0','0','0','0','0']],)",'1'],["([['1','1','0','0','0'],['1','1','0','0','0'],['0','0','1','0','0'],['0','0','0','1','1']],)",'3']],hidden:[["([],)",'0'],["([['0']],)",'0'],["([['1']],)",'1']]},
{id:'coin-change',title:'Coin Change',diff:'Medium',pattern:'Dynamic Programming',fn:'coin_change',money:350,rp:70,prompt:'Given coin denominations and an amount, return the fewest coins needed, or -1.',starter:'def coin_change(coins, amount):\n    pass',hint:'Let dp[x] be the minimum coins required to make x. Build answers from smaller amounts.',lesson:'Dynamic programming stores solutions to repeated subproblems and builds toward the target.',complexity:'O(amount × coins) time · O(amount) space',public:[["([1,2,5], 11)",'3'],["([2], 3)",'-1']],hidden:[["([1], 0)",'0'],["([1], 2)",'2'],["([2,5,10,1], 27)",'4']]}
];
const BUILDINGS=[{id:'house',name:'Housing Block',icon:'🏠',cost:150,desc:'+ population and city size'},{id:'market',name:'Market',icon:'🏪',cost:300,desc:'A thriving algorithm economy'},{id:'tower',name:'Tech Tower',icon:'🏢',cost:600,desc:'Unlock the skyline'},{id:'lab',name:'Research Lab',icon:'🧪',cost:450,desc:'A monument to pattern mastery'},{id:'park',name:'City Park',icon:'🌳',cost:200,desc:'Your brain needs recovery too'},{id:'metro',name:'Metro Hub',icon:'🚇',cost:900,desc:'Connect advanced districts'}];
const TECH=[{id:'arrays',name:'Array Engineering',cost:40,desc:'Scanning, state, sorting and pointer foundations.'},{id:'maps',name:'Hash Infrastructure',cost:80,desc:'Fast lookup and frequency maps.'},{id:'graphs',name:'Graph Transit',cost:150,desc:'DFS, BFS, trees and connectivity.'},{id:'dp',name:'Dynamic Planning',cost:250,desc:'Optimal substructure and memoization.'}];
const fresh=()=>({money:100,research:0,level:1,xp:0,streak:0,solved:[],buildings:['camp'],tech:[],current:'two-sum',attempts:{},hints:0,history:[],mastery:{}});
let state;try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem('codeopolis-save'))||{})}catch{state=fresh()}state.history=state.history||[];state.mastery=state.mastery||{};
let pyodide=null,pyStatus='loading';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function persist(renderToo=true){localStorage.setItem('codeopolis-save',JSON.stringify(state));if(renderToo)render()}
function current(){return CHALLENGES.find(x=>x.id===state.current)||CHALLENGES[0]}
function unlocked(c){const i=CHALLENGES.indexOf(c);return i===0||state.solved.includes(CHALLENGES[i-1].id)}
async function initPython(){try{pyStatus='loading';renderPythonStatus();pyodide=await loadPyodide({indexURL:`https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`});pyStatus='ready'}catch(e){console.error(e);pyStatus='error'}renderPythonStatus();renderChallenge()}
function renderPythonStatus(){const el=$('#pythonStatus');if(!el)return;el.className='tag '+(pyStatus==='ready'?'ready':pyStatus==='error'?'error':'loading');el.textContent=pyStatus==='ready'?'Python ready':pyStatus==='error'?'Python unavailable':'Loading Python…'}
function render(){money.textContent=state.money;research.textContent=state.research;level.textContent=state.level;streak.textContent=state.streak;era.textContent=state.level<3?'Settlement Era':state.level<6?'Industrial Era':'Algorithmic Era';renderCity();renderChallenge();renderBuild();renderResearch();renderStats();renderMission();renderPythonStatus()}
function renderCity(){let cells=[...state.buildings];while(cells.length<20)cells.push('');city.innerHTML=cells.slice(0,20).map((x,i)=>{if(x==='camp')return '<div class="tile"><div><span>⛺</span>Founder Camp</div></div>';const b=BUILDINGS.find(y=>y.id===x);return b?`<div class="tile"><div><span>${b.icon}</span>${b.name}</div></div>`:`<div class="tile"><div><span>${i%4===0?'🌲':'·'}</span></div></div>`}).join('')}
function masteryFor(id){return state.mastery[id]||{attempts:0,passes:0,lastSolvedAt:null,bestMs:null}}
function renderChallenge(){const c=current(),done=state.solved.includes(c.id),m=masteryFor(c.id);challengeTab.innerHTML=`<div class="challenge"><span class="tag">${c.diff}</span> <span class="tag">${c.pattern}</span><h3>${c.title}</h3><p>${c.prompt}</p><div class="muted">Target: ${c.complexity}</div><textarea id="editor" class="code" spellcheck="false">${esc(state.attempts[c.id]||c.starter)}</textarea><div class="actions"><button class="btn" onclick="runVisibleTests()" ${pyStatus!=='ready'?'disabled':''}>▶ Run tests</button><button class="btn primary" onclick="submitCode()" ${pyStatus!=='ready'?'disabled':''}>${done?'Re-submit':'Submit mission'}</button><button class="btn" onclick="showHint()">Hint</button><button class="btn" onclick="nextChallenge()">Next Mission</button></div><div id="feedback" class="feedback muted">${pyStatus==='ready'?`Ready. ${c.public.length} visible tests + ${c.hidden.length} hidden tests.`:'Python runtime is loading…'}${done?' · ✅ completed':''}</div><div class="muted" style="margin-top:8px">Attempts ${m.attempts} · passes ${m.passes}${m.bestMs!=null?` · best ${m.bestMs.toFixed(1)} ms`:''}</div></div>`;const ed=$('#editor');if(ed)ed.oninput=e=>{state.attempts[c.id]=e.target.value;persist(false)}}
function pythonHarness(c,code,cases){const payload=JSON.stringify(cases);const normalizer=c.normalize==='triplets'?`def normalize(v):\n    return sorted([sorted(list(x)) for x in v])`:`def normalize(v):\n    return v`;return `import json, traceback, time, copy\n${normalizer}\nns={}\ntry:\n    exec(${JSON.stringify(code)}, ns)\n    fn=ns.get(${JSON.stringify(c.fn)})\n    if not callable(fn):\n        raise NameError('Expected a function named ${c.fn}')\n    cases=json.loads(${JSON.stringify(payload)})\n    results=[]\n    started=time.perf_counter()\n    for idx,pair in enumerate(cases):\n        args=eval(pair[0], {})\n        expected=eval(pair[1], {})\n        try:\n            actual=fn(*copy.deepcopy(args))\n            ok=normalize(actual)==normalize(expected)\n            results.append({'index':idx,'ok':ok,'actual':repr(actual),'expected':repr(expected),'error':None})\n        except Exception as e:\n            results.append({'index':idx,'ok':False,'actual':None,'expected':repr(expected),'error':type(e).__name__+': '+str(e)})\n    elapsed=(time.perf_counter()-started)*1000\n    json.dumps({'fatal':None,'elapsed':elapsed,'results':results})\nexcept Exception as e:\n    json.dumps({'fatal':type(e).__name__+': '+str(e),'trace':traceback.format_exc(limit=2),'elapsed':0,'results':[]})`}
async function judge(c,code,cases){try{return JSON.parse(await pyodide.runPythonAsync(pythonHarness(c,code,cases)))}catch(e){return{fatal:String(e),elapsed:0,results:[]}}}
function complexityCoach(c,code){const loops=(code.match(/\b(for|while)\b/g)||[]).length;const nested=/\b(for|while)\b[^\n]*:\s*\n\s+.*\b(for|while)\b/s.test(code);let note=`Target complexity: ${c.complexity}. `;if(c.pattern==='Hash Map'&&!/[{]|dict\(|defaultdict/.test(code))note+='I do not see an obvious hash-map structure; check whether you are doing repeated scans. ';if(c.pattern==='Binary Search'&&!/\/\/\s*2|>>\s*1/.test(code))note+='Make sure the search interval shrinks by roughly half each step. ';if(nested&&['Hash Map','One Pass','Sliding Window'].includes(c.pattern))note+='Your code appears to contain nested loops; that may be slower than the intended pattern. ';else if(loops)note+=`Detected ${loops} loop construct${loops===1?'':'s'}; validate the real Big-O rather than relying on this heuristic.`;return note}
function testRows(c,result,hidden=false){if(result.fatal)return `<div class="test-row fail">❌ ${esc(result.fatal)}</div>`;return result.results.map((r,i)=>`<div class="test-row ${r.ok?'pass':'fail'}">${r.ok?'✅':'❌'} ${hidden?'Hidden test '+(i+1):'Test '+(i+1)}${r.ok?' passed':`: expected ${esc(r.expected)}, got ${esc(r.error||r.actual)}`}</div>`).join('')}
async function runVisibleTests(){const c=current(),code=$('#editor').value;state.attempts[c.id]=code;const fb=$('#feedback');fb.className='feedback';fb.innerHTML='Running Python tests…';const result=await judge(c,code,c.public);const all=!result.fatal&&result.results.every(r=>r.ok);fb.className='feedback '+(all?'pass':'fail');fb.innerHTML=`<b>${all?'Visible tests passed':'Tests need work'}</b> · ${result.elapsed.toFixed(1)} ms<div class="tests">${testRows(c,result)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;persist(false)}
async function submitCode(){const c=current(),code=$('#editor').value;state.attempts[c.id]=code;const m=masteryFor(c.id);m.attempts++;state.mastery[c.id]=m;const fb=$('#feedback');fb.className='feedback';fb.innerHTML='Running visible + hidden tests…';const visible=await judge(c,code,c.public);if(visible.fatal||visible.results.some(r=>!r.ok)){state.streak=0;recordHistory(c,false,visible.elapsed,'visible');persist(false);fb.className='feedback fail';fb.innerHTML=`<b>Visible tests failed.</b><div class="tests">${testRows(c,visible)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;renderStats();return}const hidden=await judge(c,code,c.hidden);const allHidden=!hidden.fatal&&hidden.results.every(r=>r.ok);const total=visible.elapsed+hidden.elapsed;if(!allHidden){state.streak=0;recordHistory(c,false,total,'hidden');persist(false);fb.className='feedback fail';fb.innerHTML=`<b>Visible tests passed, but ${hidden.results.filter(r=>!r.ok).length||1} hidden test(s) failed.</b><div class="tests">${testRows(c,hidden,true)}</div><div class="muted" style="margin-top:8px">Think about edge cases: empty inputs, duplicates, boundaries, and mutation.</div>`;renderStats();return}const first=!state.solved.includes(c.id);if(first){state.solved.push(c.id);state.money+=c.money;state.research+=c.rp;state.xp+=100+(c.diff==='Medium'?50:0);state.level=1+Math.floor(state.xp/250)}state.streak++;m.passes++;m.lastSolvedAt=new Date().toISOString();m.bestMs=m.bestMs==null?total:Math.min(m.bestMs,total);state.mastery[c.id]=m;recordHistory(c,true,total,'all');persist(false);fb.className='feedback pass';fb.innerHTML=`<b>✅ Mission cleared.</b> ${esc(c.lesson)}${first?`<br>Earned 💰 ${c.money} and 🔬 ${c.rp}.`:''}<div class="tests">${testRows(c,visible)}${testRows(c,hidden,true)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;money.textContent=state.money;research.textContent=state.research;level.textContent=state.level;streak.textContent=state.streak;renderCity();renderMission();renderStats()}
function recordHistory(c,passed,ms,stage){state.history.unshift({id:c.id,title:c.title,pattern:c.pattern,passed,ms,stage,at:new Date().toISOString()});state.history=state.history.slice(0,40)}
function showHint(){state.hints++;persist(false);$('#feedback').innerHTML='💡 '+esc(current().hint)}
function nextChallenge(){const i=CHALLENGES.findIndex(x=>x.id===state.current),c=CHALLENGES[(i+1)%CHALLENGES.length];if(!unlocked(c)){const f=$('#feedback');if(f)f.innerHTML='🔒 Complete the current mission to unlock the next one.';return}state.current=c.id;persist();switchTab('challenge')}
function renderBuild(){buildTab.innerHTML='<div class="shop">'+BUILDINGS.map(b=>`<div class="shop-item"><h4>${b.icon} ${b.name}</h4><div class="muted">${b.desc}</div><p>💰 ${b.cost}</p><button class="btn" ${state.money<b.cost?'disabled':''} onclick="buyBuilding('${b.id}')">Build</button></div>`).join('')+'</div>'}
function buyBuilding(id){const b=BUILDINGS.find(x=>x.id===id);if(!b||state.money<b.cost)return;state.money-=b.cost;state.buildings.push(id);persist()}
function renderResearch(){researchTab.innerHTML='<div class="shop">'+TECH.map(t=>`<div class="shop-item"><h4>${state.tech.includes(t.id)?'✅':'🔬'} ${t.name}</h4><div class="muted">${t.desc}</div><p>🔬 ${t.cost}</p><button class="btn" ${state.tech.includes(t.id)||state.research<t.cost?'disabled':''} onclick="buyTech('${t.id}')">${state.tech.includes(t.id)?'Researched':'Research'}</button></div>`).join('')+'</div>'}
function buyTech(id){const t=TECH.find(x=>x.id===id);if(!t||state.research<t.cost||state.tech.includes(id))return;state.research-=t.cost;state.tech.push(id);persist()}
function reviewDue(){const now=Date.now(),day=86400000;return CHALLENGES.filter(c=>{const m=masteryFor(c.id);return m.lastSolvedAt&&now-new Date(m.lastSolvedAt).getTime()>Math.min(7,1+m.passes*2)*day})}
function renderStats(){const pct=Math.round(state.solved.length/CHALLENGES.length*100),passes=state.history.filter(x=>x.passed).length,total=state.history.length,due=reviewDue();statsTab.innerHTML=`<h3>Interview Readiness</h3><div class="progress"><i style="width:${pct}%"></i></div><p>${state.solved.length}/${CHALLENGES.length} missions completed · ${pct}%</p><div class="metric-grid"><div class="metric"><b>${total?Math.round(passes/total*100):0}%</b><div class="muted">recent pass rate</div></div><div class="metric"><b>${due.length}</b><div class="muted">reviews due</div></div><div class="metric"><b>${state.buildings.length-1}</b><div class="muted">buildings</div></div><div class="metric"><b>${state.tech.length}</b><div class="muted">technologies</div></div></div><h3>Solution history</h3><div class="history">${state.history.slice(0,10).map(h=>`<div class="history-item">${h.passed?'✅':'❌'} <b>${esc(h.title)}</b> · ${esc(h.pattern)} <span class="muted">${h.ms.toFixed(1)} ms · ${new Date(h.at).toLocaleDateString()}</span></div>`).join('')||'<div class="muted">Run a mission to start your history.</div>'}</div>${due.length?`<h3>Review queue</h3><p>${due.map(c=>`<button class="btn" onclick="selectChallenge('${c.id}')">${c.title}</button>`).join(' ')}</p>`:''}`}
function renderMission(){mission.innerHTML=CHALLENGES.map(c=>{const m=masteryFor(c.id);return `<button class="btn" style="width:100%;margin:4px 0;text-align:left" ${unlocked(c)?'':'disabled'} onclick="selectChallenge('${c.id}')">${state.solved.includes(c.id)?'✅':unlocked(c)?'▶️':'🔒'} ${c.title} <span class="muted">· ${c.pattern}${m.passes?' · '+m.passes+' pass'+(m.passes===1?'':'es'):''}</span></button>`}).join('')}
function selectChallenge(id){state.current=id;persist();switchTab('challenge')}
function switchTab(name){document.querySelectorAll('[id$="Tab"]').forEach(x=>x.classList.add('hidden'));const target=document.getElementById(name+'Tab');if(target)target.classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}
function exportSave(){prompt('Copy your Codeopolis save JSON:',JSON.stringify(state))}
function resetGame(){if(confirm('Reset the entire civilization and coding history?')){state=fresh();persist()}}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));render();initPython();