const PYODIDE_VERSION='314.0.3';
const CHALLENGES=[
{id:'two-sum',title:'Two Sum',diff:'Easy',pattern:'Hash Map',district:'hash',fn:'two_sum',money:100,rp:15,prompt:'Given nums and target, return the indices of two numbers that add to target.',starter:'def two_sum(nums, target):\n    # Return two indices whose values add to target\n    pass',hint:'Store each number you have seen in a dictionary mapping value → index. For x, look for target - x.',lesson:'Hash maps trade memory for fast lookup. This turns a nested O(n²) search into O(n).',complexity:'O(n) time · O(n) space',public:[['([2,7,11,15], 9)','[0,1]'],['([3,2,4], 6)','[1,2]']],hidden:[['([3,3], 6)','[0,1]'],['([-1,-2,-3,-4,-5], -8)','[2,4]']]},
{id:'valid-parens',title:'Valid Parentheses',diff:'Easy',pattern:'Stack',district:'structures',fn:'is_valid',money:110,rp:18,prompt:'Return True when (), {}, and [] are correctly nested and closed.',starter:'def is_valid(s):\n    pass',hint:'Push opening brackets onto a stack. For each closer, verify it matches the most recent opener.',lesson:'Stacks model nested state: the last thing opened must be the first thing closed.',complexity:'O(n) time · O(n) space',public:[["('()[]{}',)",'True'],["('(]',)",'False']],hidden:[["('([{}])',)",'True'],["('(',)",'False'],["('',)",'True']]},
{id:'max-profit',title:'Best Time to Buy and Sell Stock',diff:'Easy',pattern:'One Pass',district:'arrays',fn:'max_profit',money:120,rp:20,prompt:'Given daily prices, return the maximum profit from one buy followed by one later sell.',starter:'def max_profit(prices):\n    pass',hint:'Track the cheapest price seen so far and the best profit if you sold today.',lesson:'Many array problems collapse to a few pieces of state maintained during one linear scan.',complexity:'O(n) time · O(1) space',public:[["([7,1,5,3,6,4],)",'5'],["([7,6,4,3,1],)",'0']],hidden:[["([1,2],)",'1'],["([2,4,1],)",'2']]},
{id:'binary-search',title:'Binary Search',diff:'Easy',pattern:'Binary Search',district:'search',fn:'search',money:130,rp:22,prompt:'Given sorted nums and target, return its index or -1.',starter:'def search(nums, target):\n    pass',hint:'Maintain left/right boundaries. Compare the midpoint and discard half the search range.',lesson:'Binary search is about maintaining a correct search invariant.',complexity:'O(log n) time · O(1) space',public:[["([-1,0,3,5,9,12], 9)",'4'],["([-1,0,3,5,9,12], 2)",'-1']],hidden:[["([5], 5)",'0'],["([2,5], 2)",'0'],["([], 1)",'-1']]},
{id:'longest-substring',title:'Longest Substring Without Repeating Characters',diff:'Medium',pattern:'Sliding Window',district:'arrays',fn:'length_of_longest_substring',money:220,rp:40,prompt:'Return the length of the longest substring containing no repeated characters.',starter:'def length_of_longest_substring(s):\n    pass',hint:'Keep a left boundary and a map/set for the current window. Move left when a repeat invalidates it.',lesson:'Sliding windows maintain a valid contiguous region while one boundary advances.',complexity:'O(n) time · O(k) space',public:[["('abcabcbb',)",'3'],["('bbbbb',)",'1']],hidden:[["('pwwkew',)",'3'],["('',)",'0'],["('dvdf',)",'3']]},
{id:'three-sum',title:'3Sum',diff:'Medium',pattern:'Two Pointers',district:'arrays',fn:'three_sum',money:260,rp:45,prompt:'Return all unique triplets whose values sum to zero.',starter:'def three_sum(nums):\n    pass',hint:'Sort first. Fix one value, then solve the remaining two-sum search using left/right pointers.',lesson:'Sorting can expose structure that makes pointer movement meaningful.',complexity:'O(n²) time · O(1) extra space excluding output',normalize:'triplets',public:[["([-1,0,1,2,-1,-4],)",'[[-1,-1,2],[-1,0,1]]'],["([0,1,1],)",'[]']],hidden:[["([0,0,0],)",'[[0,0,0]]'],["([],)",'[]'],["([-2,0,1,1,2],)",'[[-2,0,2],[-2,1,1]]']]},
{id:'num-islands',title:'Number of Islands',diff:'Medium',pattern:'DFS / BFS',district:'graphs',fn:'num_islands',money:300,rp:55,prompt:'Count connected groups of land ("1") in a 2D grid using horizontal/vertical adjacency.',starter:'def num_islands(grid):\n    pass',hint:'When you find unvisited land, increment the count and flood-fill that whole island with DFS or BFS.',lesson:'Graph traversal appears even when the input is presented as a grid.',complexity:'O(rows × cols) time · O(rows × cols) worst-case space',public:[["([['1','1','1','1','0'],['1','1','0','1','0'],['1','1','0','0','0'],['0','0','0','0','0']],)",'1'],["([['1','1','0','0','0'],['1','1','0','0','0'],['0','0','1','0','0'],['0','0','0','1','1']],)",'3']],hidden:[["([],)",'0'],["([['0']],)",'0'],["([['1']],)",'1']]},
{id:'coin-change',title:'Coin Change',diff:'Medium',pattern:'Dynamic Programming',district:'dp',fn:'coin_change',money:350,rp:70,prompt:'Given coin denominations and an amount, return the fewest coins needed, or -1.',starter:'def coin_change(coins, amount):\n    pass',hint:'Let dp[x] be the minimum coins required to make x. Build answers from smaller amounts.',lesson:'Dynamic programming stores solutions to repeated subproblems and builds toward the target.',complexity:'O(amount × coins) time · O(amount) space',public:[["([1,2,5], 11)",'3'],["([2], 3)",'-1']],hidden:[["([1], 0)",'0'],["([1], 2)",'2'],["([2,5,10,1], 27)",'4']]}
];

const DISTRICTS={
core:{name:'Civic Core',icon:'🏛️',desc:'General city administration and population.'},
arrays:{name:'Array Foundry',icon:'🏭',desc:'Arrays, windows, pointers and linear scans.'},
hash:{name:'Hash Bazaar',icon:'🧺',desc:'Fast lookup, sets and frequency maps.'},
structures:{name:'Stack Quarter',icon:'📚',desc:'Stacks, queues and stateful structures.'},
search:{name:'Search Observatory',icon:'🔭',desc:'Binary search and ordered reasoning.'},
graphs:{name:'Graph Transit',icon:'🚇',desc:'Connectivity, traversal and graph thinking.'},
dp:{name:'Dynamic Planning Bureau',icon:'🧠',desc:'Optimization and repeated subproblems.'}
};

const BUILDINGS=[
{id:'house',name:'Housing Block',icon:'🏠',cost:180,district:'core',population:25,energy:-1,happiness:1,desc:'+25 population · -1 energy'},
{id:'market',name:'Hash Market',icon:'🏪',cost:320,district:'hash',moneyRate:8,energy:-1,requiresTech:'maps',desc:'+8 money/min · -1 energy'},
{id:'foundry',name:'Array Foundry',icon:'🏭',cost:420,district:'arrays',moneyRate:10,energy:-2,requiresTech:'arrays',desc:'+10 money/min · -2 energy'},
{id:'observatory',name:'Search Observatory',icon:'🔭',cost:460,district:'search',researchRate:4,energy:-1,requiresTech:'search',desc:'+4 research/min · -1 energy'},
{id:'transit',name:'Graph Transit Hub',icon:'🚇',cost:650,district:'graphs',population:20,happiness:4,energy:-2,requiresTech:'graphs',desc:'+20 population · +4 happiness'},
{id:'lab',name:'DP Research Lab',icon:'🧪',cost:700,district:'dp',researchRate:8,energy:-2,requiresTech:'dp',desc:'+8 research/min · -2 energy'},
{id:'park',name:'Recovery Park',icon:'🌳',cost:260,district:'core',happiness:8,desc:'+8 happiness'},
{id:'solar',name:'Solar Array',icon:'☀️',cost:360,district:'core',energy:6,requiresTech:'energy',desc:'+6 energy capacity'},
{id:'tower',name:'Algorithm Tower',icon:'🏢',cost:950,district:'core',population:45,researchRate:3,energy:-3,requiresEra:2,desc:'+45 population · +3 research/min'},
{id:'academy',name:'Interview Academy',icon:'🎓',cost:1200,district:'core',happiness:5,researchRate:5,energy:-2,requiresEra:3,desc:'+5 happiness · +5 research/min'}
];

const TECH=[
{id:'arrays',name:'Array Engineering',cost:40,desc:'Unlock Array Foundry.',prereq:[]},
{id:'maps',name:'Hash Infrastructure',cost:70,desc:'Unlock Hash Market.',prereq:['arrays']},
{id:'search',name:'Ordered Systems',cost:90,desc:'Unlock Search Observatory.',prereq:['arrays']},
{id:'energy',name:'Grid Engineering',cost:120,desc:'Unlock Solar Arrays.',prereq:['arrays']},
{id:'graphs',name:'Graph Transit',cost:160,desc:'Unlock graph district infrastructure.',prereq:['maps','search']},
{id:'dp',name:'Dynamic Planning',cost:260,desc:'Unlock DP Research Labs.',prereq:['graphs']},
{id:'automation',name:'Civic Automation',cost:350,desc:'+25% passive production.',prereq:['dp','energy']}
];

const EVENTS=[
{id:'brownout',title:'Grid Brownout',text:'A surge hits the city grid. Divert funds to stabilize it or accept a temporary happiness hit.',choices:[{label:'Pay 120 💰',can:s=>s.money>=120,apply:s=>{s.money-=120;s.happiness=Math.min(100,s.happiness+3)},result:'The grid is stabilized.'},{label:'Ration power',apply:s=>{s.happiness=Math.max(25,s.happiness-8)},result:'Citizens endure rolling outages.'}]},
{id:'hackathon',title:'Civic Hackathon',text:'Students want to host an all-night algorithm hackathon.',choices:[{label:'Fund it: 50 💰',can:s=>s.money>=50,apply:s=>{s.money-=50;s.research+=35;s.happiness=Math.min(100,s.happiness+3)},result:'New ideas spread across the city.'},{label:'Skip it',apply:s=>{s.happiness=Math.max(25,s.happiness-2)},result:'The community is disappointed.'}]},
{id:'boom',title:'Startup Boom',text:'A wave of interview-ready engineers launches new companies.',choices:[{label:'Collect growth',apply:s=>{s.money+=180;s.population+=10},result:'The local economy surges.'}]},
{id:'review',title:'Knowledge Decay Alert',text:'Engineers are forgetting an old pattern. Complete a review mission to restore confidence.',choices:[{label:'Add review quest',apply:s=>{s.forcedReview=true},result:'A review mission has been prioritized.'},{label:'Ignore for now',apply:s=>{s.happiness=Math.max(25,s.happiness-3)},result:'Confidence slips a little.'}]}
];

const BOSSES=[
{id:'boss-1',era:1,nextEra:2,title:'Regional Systems Interview',requiresSolved:4,rewardMoney:500,rewardResearch:100,questions:[{q:'Which pattern usually gives O(log n) lookup in a sorted array?',options:['Sliding window','Binary search','DFS','Hash counting'],answer:1},{q:'For balanced brackets, what data structure best models nesting?',options:['Queue','Heap','Stack','Set'],answer:2},{q:'A hash map primarily trades what for faster lookup?',options:['Accuracy','Memory','Recursion depth','Sorting'],answer:1}]},
{id:'boss-2',era:2,nextEra:3,title:'Principal Algorithm Review',requiresSolved:7,rewardMoney:900,rewardResearch:180,questions:[{q:'What is the typical time complexity of DFS over a graph?',options:['O(V+E)','O(log V)','O(V²) always','O(1)'],answer:0},{q:'What makes dynamic programming useful?',options:['Randomization','Repeated subproblems','Only sorted inputs','Constant memory'],answer:1},{q:'A sliding window is most natural for what kind of region?',options:['Arbitrary nodes','Contiguous sequences','Only trees','Hash collisions'],answer:1}]}
];

const fresh=()=>({money:100,research:0,level:1,xp:0,streak:0,solved:[],buildings:['camp'],tech:[],current:'two-sum',attempts:{},hints:0,history:[],mastery:{},population:12,energy:5,happiness:78,eraLevel:1,lastTick:Date.now(),districtXP:{core:1,arrays:0,hash:0,structures:0,search:0,graphs:0,dp:0},eventLog:[],activeEvent:null,lastEventAt:Date.now(),daily:{date:'',completed:false,target:2,progress:0},bossesPassed:[],bossRun:null,forcedReview:false});
let state;try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem('codeopolis-save'))||{})}catch{state=fresh()}
state.history=state.history||[];state.mastery=state.mastery||{};state.districtXP=Object.assign(fresh().districtXP,state.districtXP||{});state.eventLog=state.eventLog||[];state.daily=Object.assign(fresh().daily,state.daily||{});state.bossesPassed=state.bossesPassed||[];
let pyodide=null,pyStatus='loading';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function persist(renderToo=true){localStorage.setItem('codeopolis-save',JSON.stringify(state));if(renderToo)render()}
function current(){return CHALLENGES.find(x=>x.id===state.current)||CHALLENGES[0]}
function currentBoss(){return BOSSES.find(b=>b.era===state.eraLevel&&!state.bossesPassed.includes(b.id))||null}
function masteryFor(id){return state.mastery[id]||{attempts:0,passes:0,lastSolvedAt:null,bestMs:null}}
function unlocked(c){const i=CHALLENGES.indexOf(c);if(i===0)return true;const prev=CHALLENGES[i-1];if(!state.solved.includes(prev.id))return false;if(i>=4&&state.eraLevel<2)return false;if(i>=7&&state.eraLevel<3)return false;return true}
function eraName(){return state.eraLevel===1?'Settlement Era':state.eraLevel===2?'Industrial Algorithm Era':'Metropolitan AI Era'}

async function initPython(){try{pyStatus='loading';renderPythonStatus();pyodide=await loadPyodide({indexURL:`https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`});pyStatus='ready'}catch(e){console.error(e);pyStatus='error'}renderPythonStatus();renderChallenge()}
function renderPythonStatus(){const el=$('#pythonStatus');if(!el)return;el.className='tag '+(pyStatus==='ready'?'ready':pyStatus==='error'?'error':'loading');el.textContent=pyStatus==='ready'?'Python ready':pyStatus==='error'?'Python unavailable':'Loading Python…'}

function productionRates(){let moneyRate=0,researchRate=0,energyDelta=0,popBonus=0,happyBonus=0;for(const id of state.buildings){const b=BUILDINGS.find(x=>x.id===id);if(!b)continue;moneyRate+=b.moneyRate||0;researchRate+=b.researchRate||0;energyDelta+=b.energy||0;popBonus+=b.population||0;happyBonus+=b.happiness||0}const auto=state.tech.includes('automation')?1.25:1;const happinessMod=.5+Math.max(25,state.happiness)/200;const powerMod=state.energy<0?.35:1;return{moneyRate:moneyRate*auto*happinessMod*powerMod,researchRate:researchRate*auto*happinessMod*powerMod,energyDelta,popBonus,happyBonus}}
function applyOfflineProduction(){const now=Date.now(),elapsed=Math.min(now-(state.lastTick||now),6*60*60*1000),mins=elapsed/60000;if(mins<=0)return;const r=productionRates();state.money+=r.moneyRate*mins;state.research+=r.researchRate*mins;state.lastTick=now;state.energy=5+r.energyDelta;state.population=Math.max(state.population,12+r.popBonus);state.happiness=Math.max(25,Math.min(100,72+r.happyBonus+(state.streak>2?3:0)));}
function maybeEvent(){const now=Date.now();if(state.activeEvent)return;if(now-(state.lastEventAt||0)<8*60*1000)return;if(Math.random()<.35){state.activeEvent=EVENTS[Math.floor(Math.random()*EVENTS.length)].id;state.lastEventAt=now}}
function ensureDaily(){const today=new Date().toISOString().slice(0,10);if(state.daily.date!==today)state.daily={date:today,completed:false,target:2,progress:0}}

function render(){applyOfflineProduction();ensureDaily();maybeEvent();money.textContent=Math.floor(state.money);research.textContent=Math.floor(state.research);population.textContent=Math.floor(state.population);energy.textContent=state.energy;happiness.textContent=Math.floor(state.happiness);level.textContent=state.level;streak.textContent=state.streak;era.textContent=eraName();renderCityCanvas();renderCitySummary();renderChallenge();renderCityTab();renderBuild();renderResearch();renderEvents();renderStats();renderMission();renderDaily();renderBoss();renderPythonStatus();persist(false)}

function renderCityCanvas(){const canvas=$('#cityCanvas');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);const sky=ctx.createLinearGradient(0,0,0,canvas.height);sky.addColorStop(0,'#101c35');sky.addColorStop(1,'#172841');ctx.fillStyle=sky;ctx.fillRect(0,0,canvas.width,canvas.height);const tiles=state.buildings.slice(0,18);const positions=[];for(let row=0;row<3;row++)for(let col=0;col<6;col++)positions.push({x:120+col*115+(row%2)*55,y:95+row*88});positions.forEach((p,i)=>{ctx.beginPath();ctx.moveTo(p.x,p.y-34);ctx.lineTo(p.x+55,p.y);ctx.lineTo(p.x,p.y+34);ctx.lineTo(p.x-55,p.y);ctx.closePath();ctx.fillStyle=i<tiles.length?'#27496a':'#19324d';ctx.fill();ctx.strokeStyle='#446b8f';ctx.stroke();if(i<tiles.length){const id=tiles[i],b=BUILDINGS.find(x=>x.id===id);const icon=id==='camp'?'⛺':b?.icon||'🏢';ctx.font='30px system-ui';ctx.textAlign='center';ctx.fillText(icon,p.x,p.y+10)}});ctx.fillStyle='#dbe8ff';ctx.font='bold 18px system-ui';ctx.textAlign='left';ctx.fillText(eraName(),20,28);ctx.font='13px system-ui';ctx.fillStyle='#9eb0d2';ctx.fillText(`Districts powered by ${state.solved.length} mastered missions`,20,48)}
function renderCitySummary(){const r=productionRates();citySummary.innerHTML=`<span>💵 +${r.moneyRate.toFixed(1)}/min</span><span>🔬 +${r.researchRate.toFixed(1)}/min</span><span>⚡ Net ${state.energy}</span><span>🏘️ ${state.buildings.length-1} buildings</span>`}
function districtStats(){return Object.entries(DISTRICTS).map(([id,d])=>{const xp=state.districtXP[id]||0;const level=1+Math.floor(xp/3);const solved=CHALLENGES.filter(c=>c.district===id&&state.solved.includes(c.id)).length;return{id,...d,xp,level,solved}})}
function renderCityTab(){const r=productionRates();cityTab.innerHTML=`<div class="metric-grid"><div class="metric"><b>${Math.floor(state.population)}</b><div class="muted">population</div></div><div class="metric"><b>${Math.floor(state.happiness)}%</b><div class="muted">happiness</div></div><div class="metric"><b>${state.energy}</b><div class="muted">net energy</div></div><div class="metric"><b>${r.moneyRate.toFixed(1)}</b><div class="muted">money / minute</div></div></div><h3>District specialization</h3><div class="district-grid">${districtStats().map(d=>`<div class="district-card"><div class="district-icon">${d.icon}</div><div><b>${d.name}</b><div class="muted">Level ${d.level} · ${d.xp} mastery XP · ${d.solved} solved</div><div class="progress"><i style="width:${(d.xp%3)/3*100}%"></i></div><small>${d.desc}</small></div></div>`).join('')}</div>`}

function renderChallenge(){const c=current(),done=state.solved.includes(c.id),m=masteryFor(c.id);challengeTab.innerHTML=`<div class="challenge"><span class="tag">${c.diff}</span> <span class="tag">${c.pattern}</span> <span class="tag">${DISTRICTS[c.district].icon} ${DISTRICTS[c.district].name}</span><h3>${c.title}</h3><p>${c.prompt}</p><div class="muted">Target: ${c.complexity}</div><textarea id="editor" class="code" spellcheck="false">${esc(state.attempts[c.id]||c.starter)}</textarea><div class="actions"><button class="btn" onclick="runVisibleTests()" ${pyStatus!=='ready'?'disabled':''}>▶ Run tests</button><button class="btn primary" onclick="submitCode()" ${pyStatus!=='ready'?'disabled':''}>${done?'Re-submit':'Submit mission'}</button><button class="btn" onclick="showHint()">Hint</button><button class="btn" onclick="nextChallenge()">Next Mission</button></div><div id="feedback" class="feedback muted">${pyStatus==='ready'?`Ready. ${c.public.length} visible tests + ${c.hidden.length} hidden tests.`:'Python runtime is loading…'}${done?' · ✅ completed':''}</div><div class="muted" style="margin-top:8px">Attempts ${m.attempts} · passes ${m.passes}${m.bestMs!=null?` · best ${m.bestMs.toFixed(1)} ms`:''}</div></div>`;const ed=$('#editor');if(ed)ed.oninput=e=>{state.attempts[c.id]=e.target.value;persist(false)}}
function pythonHarness(c,code,cases){const payload=JSON.stringify(cases);const normalizer=c.normalize==='triplets'?`def normalize(v):\n    return sorted([sorted(list(x)) for x in v])`:`def normalize(v):\n    return v`;return `import json, traceback, time, copy\n${normalizer}\nns={}\ntry:\n    exec(${JSON.stringify(code)}, ns)\n    fn=ns.get(${JSON.stringify(c.fn)})\n    if not callable(fn):\n        raise NameError('Expected a function named ${c.fn}')\n    cases=json.loads(${JSON.stringify(payload)})\n    results=[]\n    started=time.perf_counter()\n    for idx,pair in enumerate(cases):\n        args=eval(pair[0], {})\n        expected=eval(pair[1], {})\n        try:\n            actual=fn(*copy.deepcopy(args))\n            ok=normalize(actual)==normalize(expected)\n            results.append({'index':idx,'ok':ok,'actual':repr(actual),'expected':repr(expected),'error':None})\n        except Exception as e:\n            results.append({'index':idx,'ok':False,'actual':None,'expected':repr(expected),'error':type(e).__name__+': '+str(e)})\n    elapsed=(time.perf_counter()-started)*1000\n    json.dumps({'fatal':None,'elapsed':elapsed,'results':results})\nexcept Exception as e:\n    json.dumps({'fatal':type(e).__name__+': '+str(e),'trace':traceback.format_exc(limit=2),'elapsed':0,'results':[]})`}
async function judge(c,code,cases){try{return JSON.parse(await pyodide.runPythonAsync(pythonHarness(c,code,cases)))}catch(e){return{fatal:String(e),elapsed:0,results:[]}}}
function complexityCoach(c,code){const loops=(code.match(/\b(for|while)\b/g)||[]).length;const nested=/\b(for|while)\b[^\n]*:\s*\n\s+.*\b(for|while)\b/s.test(code);let note=`Target complexity: ${c.complexity}. `;if(c.pattern==='Hash Map'&&!/[{]|dict\(|defaultdict/.test(code))note+='I do not see an obvious hash-map structure; check whether you are doing repeated scans. ';if(c.pattern==='Binary Search'&&!/\/\/\s*2|>>\s*1/.test(code))note+='Make sure the search interval shrinks by roughly half each step. ';if(nested&&['Hash Map','One Pass','Sliding Window'].includes(c.pattern))note+='Your code appears to contain nested loops; that may be slower than the intended pattern. ';else if(loops)note+=`Detected ${loops} loop construct${loops===1?'':'s'}; validate the real Big-O rather than relying on this heuristic.`;return note}
function testRows(c,result,hidden=false){if(result.fatal)return `<div class="test-row fail">❌ ${esc(result.fatal)}</div>`;return result.results.map((r,i)=>`<div class="test-row ${r.ok?'pass':'fail'}">${r.ok?'✅':'❌'} ${hidden?'Hidden test '+(i+1):'Test '+(i+1)}${r.ok?' passed':`: expected ${esc(r.expected)}, got ${esc(r.error||r.actual)}`}</div>`).join('')}
async function runVisibleTests(){const c=current(),code=$('#editor').value;state.attempts[c.id]=code;const fb=$('#feedback');fb.className='feedback';fb.innerHTML='Running Python tests…';const result=await judge(c,code,c.public);const all=!result.fatal&&result.results.every(r=>r.ok);fb.className='feedback '+(all?'pass':'fail');fb.innerHTML=`<b>${all?'Visible tests passed':'Tests need work'}</b> · ${result.elapsed.toFixed(1)} ms<div class="tests">${testRows(c,result)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;persist(false)}
async function submitCode(){const c=current(),code=$('#editor').value;state.attempts[c.id]=code;const m=masteryFor(c.id);m.attempts++;state.mastery[c.id]=m;const fb=$('#feedback');fb.className='feedback';fb.innerHTML='Running visible + hidden tests…';const visible=await judge(c,code,c.public);if(visible.fatal||visible.results.some(r=>!r.ok)){state.streak=0;recordHistory(c,false,visible.elapsed,'visible');persist(false);fb.className='feedback fail';fb.innerHTML=`<b>Visible tests failed.</b><div class="tests">${testRows(c,visible)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;renderStats();return}const hidden=await judge(c,code,c.hidden);const allHidden=!hidden.fatal&&hidden.results.every(r=>r.ok);const total=visible.elapsed+hidden.elapsed;if(!allHidden){state.streak=0;recordHistory(c,false,total,'hidden');persist(false);fb.className='feedback fail';fb.innerHTML=`<b>Visible tests passed, but ${hidden.results.filter(r=>!r.ok).length||1} hidden test(s) failed.</b><div class="tests">${testRows(c,hidden,true)}</div><div class="muted" style="margin-top:8px">Think about edge cases: empty inputs, duplicates, boundaries, and mutation.</div>`;renderStats();return}const first=!state.solved.includes(c.id);if(first){state.solved.push(c.id);state.money+=c.money;state.research+=c.rp;state.xp+=100+(c.diff==='Medium'?50:0);state.level=1+Math.floor(state.xp/250);state.districtXP[c.district]=(state.districtXP[c.district]||0)+2}else state.districtXP[c.district]=(state.districtXP[c.district]||0)+1;state.streak++;m.passes++;m.lastSolvedAt=new Date().toISOString();m.bestMs=m.bestMs==null?total:Math.min(m.bestMs,total);state.mastery[c.id]=m;state.daily.progress=Math.min(state.daily.target,state.daily.progress+1);if(state.daily.progress>=state.daily.target&&!state.daily.completed){state.daily.completed=true;state.money+=150;state.research+=25;state.happiness=Math.min(100,state.happiness+3)}state.forcedReview=false;recordHistory(c,true,total,'all');persist(false);fb.className='feedback pass';fb.innerHTML=`<b>✅ Mission cleared.</b> ${esc(c.lesson)}${first?`<br>Earned 💰 ${c.money} and 🔬 ${c.rp}. District mastery increased.`:''}<div class="tests">${testRows(c,visible)}${testRows(c,hidden,true)}</div><div class="muted" style="margin-top:8px">${esc(complexityCoach(c,code))}</div>`;render()}
function recordHistory(c,passed,ms,stage){state.history.unshift({id:c.id,title:c.title,pattern:c.pattern,passed,ms,stage,at:new Date().toISOString()});state.history=state.history.slice(0,60)}
function showHint(){state.hints++;persist(false);$('#feedback').innerHTML='💡 '+esc(current().hint)}
function nextChallenge(){const i=CHALLENGES.findIndex(x=>x.id===state.current),c=CHALLENGES[(i+1)%CHALLENGES.length];if(!unlocked(c)){const f=$('#feedback');if(f)f.innerHTML='🔒 This mission is gated by the previous problem or your current civilization era. Beat the era boss if needed.';return}state.current=c.id;persist();switchTab('challenge')}

function buildingLockedReason(b){if(b.requiresTech&&!state.tech.includes(b.requiresTech))return `Requires ${TECH.find(t=>t.id===b.requiresTech)?.name||b.requiresTech}`;if(b.requiresEra&&state.eraLevel<b.requiresEra)return `Requires Era ${b.requiresEra}`;if(state.money<b.cost)return 'Not enough money';return ''}
function renderBuild(){buildTab.innerHTML='<div class="shop">'+BUILDINGS.map(b=>{const reason=buildingLockedReason(b);return `<div class="shop-item"><h4>${b.icon} ${b.name}</h4><div class="tag">${DISTRICTS[b.district].name}</div><div class="muted">${b.desc}</div><p>💰 ${b.cost}</p><button class="btn" ${reason?'disabled':''} onclick="buyBuilding('${b.id}')">${reason||'Build'}</button></div>`}).join('')+'</div>'}
function buyBuilding(id){const b=BUILDINGS.find(x=>x.id===id);if(!b||buildingLockedReason(b))return;state.money-=b.cost;state.buildings.push(id);state.districtXP[b.district]=(state.districtXP[b.district]||0)+1;persist()}
function techLockedReason(t){const missing=t.prereq.filter(id=>!state.tech.includes(id));if(state.tech.includes(t.id))return 'Researched';if(missing.length)return 'Requires '+missing.map(id=>TECH.find(x=>x.id===id)?.name||id).join(', ');if(state.research<t.cost)return 'Not enough research';return ''}
function renderResearch(){researchTab.innerHTML='<div class="tech-tree">'+TECH.map(t=>{const reason=techLockedReason(t);return `<div class="shop-item"><h4>${state.tech.includes(t.id)?'✅':'🔬'} ${t.name}</h4><div class="muted">${t.desc}</div><div class="prereq">${t.prereq.length?'Prereq: '+t.prereq.map(id=>TECH.find(x=>x.id===id)?.name).join(' → '):'Foundation technology'}</div><p>🔬 ${t.cost}</p><button class="btn" ${reason?'disabled':''} onclick="buyTech('${t.id}')">${reason||'Research'}</button></div>`}).join('')+'</div>'}
function buyTech(id){const t=TECH.find(x=>x.id===id);if(!t||techLockedReason(t))return;state.research-=t.cost;state.tech.push(id);persist()}

function renderEvents(){const active=EVENTS.find(e=>e.id===state.activeEvent);eventsTab.innerHTML=`<h3>City Events</h3>${active?`<div class="event-card"><h3>🎲 ${active.title}</h3><p>${active.text}</p><div class="actions">${active.choices.map((c,i)=>`<button class="btn primary" ${c.can&&!c.can(state)?'disabled':''} onclick="chooseEvent(${i})">${c.label}</button>`).join('')}</div></div>`:'<div class="muted">No active city event. Events can appear as the civilization grows.</div>'}<h3>Event log</h3><div class="history">${state.eventLog.slice(0,8).map(x=>`<div class="history-item">${esc(x.title)} <span class="muted">· ${esc(x.result)}</span></div>`).join('')||'<div class="muted">Nothing has happened yet.</div>'}</div>`}
function chooseEvent(i){const e=EVENTS.find(x=>x.id===state.activeEvent),c=e?.choices[i];if(!e||!c||(c.can&&!c.can(state)))return;c.apply(state);state.eventLog.unshift({title:e.title,result:c.result,at:new Date().toISOString()});state.activeEvent=null;persist()}

function reviewDue(){const now=Date.now(),day=86400000;return CHALLENGES.filter(c=>{const m=masteryFor(c.id);return m.lastSolvedAt&&now-new Date(m.lastSolvedAt).getTime()>Math.min(7,1+m.passes*2)*day})}
function renderStats(){const pct=Math.round(state.solved.length/CHALLENGES.length*100),passes=state.history.filter(x=>x.passed).length,total=state.history.length,due=reviewDue();statsTab.innerHTML=`<h3>Interview Readiness</h3><div class="progress"><i style="width:${pct}%"></i></div><p>${state.solved.length}/${CHALLENGES.length} missions completed · ${pct}%</p><div class="metric-grid"><div class="metric"><b>${total?Math.round(passes/total*100):0}%</b><div class="muted">recent pass rate</div></div><div class="metric"><b>${due.length}</b><div class="muted">reviews due</div></div><div class="metric"><b>${state.buildings.length-1}</b><div class="muted">buildings</div></div><div class="metric"><b>${state.tech.length}</b><div class="muted">technologies</div></div></div><h3>Solution history</h3><div class="history">${state.history.slice(0,10).map(h=>`<div class="history-item">${h.passed?'✅':'❌'} <b>${esc(h.title)}</b> · ${esc(h.pattern)} <span class="muted">${h.ms.toFixed(1)} ms · ${new Date(h.at).toLocaleDateString()}</span></div>`).join('')||'<div class="muted">Run a mission to start your history.</div>'}</div>${due.length?`<h3>Review queue</h3><p>${due.map(c=>`<button class="btn" onclick="selectChallenge('${c.id}')">${c.title}</button>`).join(' ')}</p>`:''}`}
function renderMission(){mission.innerHTML=CHALLENGES.map(c=>{const m=masteryFor(c.id);return `<button class="btn mission-btn" ${unlocked(c)?'':'disabled'} onclick="selectChallenge('${c.id}')">${state.solved.includes(c.id)?'✅':unlocked(c)?'▶️':'🔒'} ${c.title}<span class="muted">${c.pattern}${m.passes?' · '+m.passes+' pass'+(m.passes===1?'':'es'):''}</span></button>`}).join('')}
function renderDaily(){ensureDaily();dailyQuest.innerHTML=`<b>📅 Daily Quest</b><div class="muted">Pass ${state.daily.target} coding missions or reviews today.</div><div class="progress"><i style="width:${state.daily.progress/state.daily.target*100}%"></i></div><small>${state.daily.progress}/${state.daily.target}${state.daily.completed?' · ✅ +150 💰 +25 🔬':''}</small>`}

function bossEligible(b){if(!b)return false;const districtBreadth=new Set(state.solved.map(id=>CHALLENGES.find(c=>c.id===id)?.district)).size;return state.solved.length>=b.requiresSolved&&districtBreadth>=Math.min(4,b.requiresSolved)}
function renderBoss(){const b=currentBoss();if(!b){bossCard.innerHTML='<b>🏆 Era interviews complete</b><div class="muted">Keep mastering patterns and developing the city.</div>';return}const eligible=bossEligible(b);if(state.bossRun?.id===b.id){const q=b.questions[state.bossRun.index];bossCard.innerHTML=`<b>👔 ${b.title}</b><p>${q.q}</p><div class="boss-options">${q.options.map((o,i)=>`<button class="btn" onclick="answerBoss(${i})">${o}</button>`).join('')}</div><small>Question ${state.bossRun.index+1}/${b.questions.length} · score ${state.bossRun.score}</small>`;return}bossCard.innerHTML=`<b>👔 Era Boss: ${b.title}</b><div class="muted">Requires ${b.requiresSolved} solved missions across multiple districts.</div><p>${state.solved.length}/${b.requiresSolved} solved</p><button class="btn primary" ${eligible?'':'disabled'} onclick="startBoss()">${eligible?'Start boss interview':'Not ready yet'}</button>`}
function startBoss(){const b=currentBoss();if(!bossEligible(b))return;state.bossRun={id:b.id,index:0,score:0};persist()}
function answerBoss(choice){const b=currentBoss();if(!b||!state.bossRun)return;const q=b.questions[state.bossRun.index];if(choice===q.answer)state.bossRun.score++;state.bossRun.index++;if(state.bossRun.index>=b.questions.length){const passed=state.bossRun.score>=Math.ceil(b.questions.length*.67);if(passed){state.bossesPassed.push(b.id);state.eraLevel=b.nextEra;state.money+=b.rewardMoney;state.research+=b.rewardResearch;state.happiness=Math.min(100,state.happiness+5);state.eventLog.unshift({title:`Boss passed: ${b.title}`,result:`Advanced to ${eraName()}`,at:new Date().toISOString()})}else state.eventLog.unshift({title:`Boss attempt: ${b.title}`,result:'Interview not passed. Review patterns and try again.',at:new Date().toISOString()});state.bossRun=null}persist()}

function selectChallenge(id){const c=CHALLENGES.find(x=>x.id===id);if(!c||!unlocked(c))return;state.current=id;persist();switchTab('challenge')}
function switchTab(name){document.querySelectorAll('[id$="Tab"]').forEach(x=>x.classList.add('hidden'));const target=document.getElementById(name+'Tab');if(target)target.classList.remove('hidden');document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name))}
function exportSave(){prompt('Copy your Codeopolis save JSON:',JSON.stringify(state))}
function resetGame(){if(confirm('Reset the entire civilization and coding history?')){state=fresh();persist()}}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
render();initPython();setInterval(()=>{applyOfflineProduction();maybeEvent();render()},30000);