// Phase 4: adaptive learning layer for Codeopolis.
// This file intentionally extends the Phase 3 game instead of replacing app.js.

const PHASE4_CHALLENGES=[
{id:'contains-duplicate',title:'Contains Duplicate',diff:'Easy',pattern:'Hash Set',district:'hash',fn:'contains_duplicate',money:120,rp:18,prompt:'Return True if any value appears at least twice in nums.',starter:'def contains_duplicate(nums):\n    pass',hint:'A set can tell you whether a value has already appeared.',lesson:'Sets are ideal when you only care whether something has been seen.',complexity:'O(n) time · O(n) space',public:[["([1,2,3,1],)",'True'],["([1,2,3,4],)",'False']],hidden:[["([],)",'False'],["([1,1],)",'True']],phase4:true,companies:['Foundations','Amazon-style'],solution:'def contains_duplicate(nums):\n    return len(nums) != len(set(nums))'},
{id:'group-anagrams',title:'Group Anagrams',diff:'Medium',pattern:'Hash Map',district:'hash',fn:'group_anagrams',money:260,rp:45,prompt:'Group strings that are anagrams of one another.',starter:'def group_anagrams(strs):\n    pass',hint:'Use a canonical signature such as sorted characters or a 26-count tuple.',lesson:'Hashing a canonical representation lets equivalent items collapse into the same bucket.',complexity:'O(n · k log k) with sorting signatures',normalize:'groups',public:[["(['eat','tea','tan','ate','nat','bat'],)","[['eat','tea','ate'],['tan','nat'],['bat']]"],["([''],)","[['']]" ]],hidden:[["([],)",'[]'],["(['a'],)","[['a']]" ]],phase4:true,companies:['Meta-style','Foundations'],solution:'def group_anagrams(strs):\n    groups = {}\n    for s in strs:\n        key = tuple(sorted(s))\n        groups.setdefault(key, []).append(s)\n    return list(groups.values())'},
{id:'top-k-frequent',title:'Top K Frequent Elements',diff:'Medium',pattern:'Bucket / Hash Map',district:'hash',fn:'top_k_frequent',money:280,rp:50,prompt:'Return the k most frequent values.',starter:'def top_k_frequent(nums, k):\n    pass',hint:'Count frequencies, then use buckets indexed by frequency.',lesson:'Frequency buckets can avoid sorting every item.',complexity:'O(n) target time',normalize:'unordered',public:[["([1,1,1,2,2,3], 2)",'[1,2]'],["([1], 1)",'[1]']],hidden:[["([4,4,4,5,5,6,6,6,6], 2)",'[4,6]']],phase4:true,companies:['Meta-style','Amazon-style'],solution:'def top_k_frequent(nums, k):\n    counts = {}\n    for n in nums:\n        counts[n] = counts.get(n, 0) + 1\n    buckets = [[] for _ in range(len(nums)+1)]\n    for n, count in counts.items():\n        buckets[count].append(n)\n    out=[]\n    for count in range(len(buckets)-1,0,-1):\n        for n in buckets[count]:\n            out.append(n)\n            if len(out)==k:\n                return out'},
{id:'product-except-self',title:'Product of Array Except Self',diff:'Medium',pattern:'Prefix / Suffix',district:'arrays',fn:'product_except_self',money:280,rp:48,prompt:'Return an array where output[i] is the product of every nums value except nums[i], without division.',starter:'def product_except_self(nums):\n    pass',hint:'Write prefix products into the result, then multiply by a running suffix product.',lesson:'Prefix and suffix accumulators remove the need for repeated work.',complexity:'O(n) time · O(1) extra output-excluded space',public:[["([1,2,3,4],)",'[24,12,8,6]'],["([-1,1,0,-3,3],)",'[0,0,9,0,0]']],hidden:[["([2,3],)",'[3,2]']],phase4:true,companies:['Google-style','Foundations'],solution:'def product_except_self(nums):\n    out=[1]*len(nums)\n    prefix=1\n    for i in range(len(nums)):\n        out[i]=prefix\n        prefix*=nums[i]\n    suffix=1\n    for i in range(len(nums)-1,-1,-1):\n        out[i]*=suffix\n        suffix*=nums[i]\n    return out'},
{id:'valid-palindrome',title:'Valid Palindrome',diff:'Easy',pattern:'Two Pointers',district:'arrays',fn:'is_palindrome',money:130,rp:20,prompt:'Return True if a string is a palindrome after ignoring non-alphanumeric characters and case.',starter:'def is_palindrome(s):\n    pass',hint:'Move left/right pointers inward, skipping characters you should ignore.',lesson:'Two pointers are especially natural when symmetry matters.',complexity:'O(n) time · O(1) space',public:[["('A man, a plan, a canal: Panama',)",'True'],["('race a car',)",'False']],hidden:[["(' ',)",'True']],phase4:true,companies:['Foundations'],solution:'def is_palindrome(s):\n    l, r = 0, len(s)-1\n    while l < r:\n        while l < r and not s[l].isalnum(): l += 1\n        while l < r and not s[r].isalnum(): r -= 1\n        if s[l].lower() != s[r].lower(): return False\n        l += 1; r -= 1\n    return True'},
{id:'container-water',title:'Container With Most Water',diff:'Medium',pattern:'Two Pointers',district:'arrays',fn:'max_area',money:300,rp:52,prompt:'Given heights, return the maximum water area formed by two vertical lines.',starter:'def max_area(height):\n    pass',hint:'The shorter wall limits area, so move that pointer inward.',lesson:'A greedy pointer move can eliminate candidates that cannot beat the current pair.',complexity:'O(n) time · O(1) space',public:[["([1,8,6,2,5,4,8,3,7],)",'49'],["([1,1],)",'1']],hidden:[["([4,3,2,1,4],)",'16']],phase4:true,companies:['Meta-style','Google-style'],solution:'def max_area(height):\n    l,r=0,len(height)-1\n    best=0\n    while l<r:\n        best=max(best,(r-l)*min(height[l],height[r]))\n        if height[l] < height[r]: l += 1\n        else: r -= 1\n    return best'},
{id:'character-replacement',title:'Longest Repeating Character Replacement',diff:'Medium',pattern:'Sliding Window',district:'arrays',fn:'character_replacement',money:310,rp:55,prompt:'Return the longest substring that can be made one repeated character using at most k replacements.',starter:'def character_replacement(s, k):\n    pass',hint:'Track window length and the highest single-character frequency inside the window.',lesson:'A sliding window can be valid based on an aggregate condition rather than exact contents.',complexity:'O(n) time',public:[["('ABAB', 2)",'4'],["('AABABBA', 1)",'4']],hidden:[["('', 2)",'0'],["('AAAA', 0)",'4']],phase4:true,companies:['Meta-style'],solution:'def character_replacement(s, k):\n    counts={}\n    left=best=maxf=0\n    for right,ch in enumerate(s):\n        counts[ch]=counts.get(ch,0)+1\n        maxf=max(maxf,counts[ch])\n        while right-left+1-maxf > k:\n            counts[s[left]]-=1\n            left+=1\n        best=max(best,right-left+1)\n    return best'},
{id:'min-window',title:'Minimum Window Substring',diff:'Hard',pattern:'Sliding Window',district:'arrays',fn:'min_window',money:520,rp:100,prompt:'Return the smallest substring of s containing every character of t with multiplicity.',starter:'def min_window(s, t):\n    pass',hint:'Expand until all required counts are satisfied, then shrink while validity remains.',lesson:'Advanced sliding windows often track how many constraints are currently satisfied.',complexity:'O(|s| + |t|) time',public:[["('ADOBECODEBANC', 'ABC')","'BANC'"],["('a','a')","'a'"]],hidden:[["('a','aa')","''"],["('aa','aa')","'aa'"]],phase4:true,companies:['Google-style','Meta-style'],solution:'def min_window(s, t):\n    if not t: return ""\n    need={}\n    for ch in t: need[ch]=need.get(ch,0)+1\n    have={}; formed=0; required=len(need)\n    left=0; best=(float("inf"),0,0)\n    for right,ch in enumerate(s):\n        have[ch]=have.get(ch,0)+1\n        if ch in need and have[ch]==need[ch]: formed+=1\n        while formed==required:\n            if right-left+1 < best[0]: best=(right-left+1,left,right)\n            c=s[left]; have[c]-=1\n            if c in need and have[c] < need[c]: formed-=1\n            left+=1\n    return "" if best[0]==float("inf") else s[best[1]:best[2]+1]'},
{id:'daily-temperatures',title:'Daily Temperatures',diff:'Medium',pattern:'Monotonic Stack',district:'structures',fn:'daily_temperatures',money:300,rp:55,prompt:'For each day, return how many days until a warmer temperature, or 0.',starter:'def daily_temperatures(temperatures):\n    pass',hint:'Keep indices in a stack whose temperatures are monotonically decreasing.',lesson:'Monotonic stacks efficiently answer nearest-greater-element questions.',complexity:'O(n) time · O(n) space',public:[["([73,74,75,71,69,72,76,73],)",'[1,1,4,2,1,1,0,0]'],["([30,40,50,60],)",'[1,1,1,0]']],hidden:[["([30,60,90],)",'[1,1,0]']],phase4:true,companies:['Amazon-style','Foundations'],solution:'def daily_temperatures(temperatures):\n    out=[0]*len(temperatures); stack=[]\n    for i,t in enumerate(temperatures):\n        while stack and temperatures[stack[-1]] < t:\n            j=stack.pop(); out[j]=i-j\n        stack.append(i)\n    return out'},
{id:'largest-rectangle',title:'Largest Rectangle in Histogram',diff:'Hard',pattern:'Monotonic Stack',district:'structures',fn:'largest_rectangle_area',money:540,rp:105,prompt:'Return the largest rectangle area in a histogram.',starter:'def largest_rectangle_area(heights):\n    pass',hint:'Use a monotonic increasing stack of (start_index, height).',lesson:'When a monotonic condition breaks, the stack tells you exactly which spans are now finalized.',complexity:'O(n) time',public:[["([2,1,5,6,2,3],)",'10'],["([2,4],)",'4']],hidden:[["([],)",'0'],["([1],)",'1']],phase4:true,companies:['Google-style'],solution:'def largest_rectangle_area(heights):\n    stack=[]; best=0\n    for i,h in enumerate(heights+[0]):\n        start=i\n        while stack and stack[-1][1] > h:\n            idx,height=stack.pop(); best=max(best,height*(i-idx)); start=idx\n        stack.append((start,h))\n    return best'},
{id:'search-rotated',title:'Search in Rotated Sorted Array',diff:'Medium',pattern:'Binary Search',district:'search',fn:'search_rotated',money:320,rp:58,prompt:'Return the index of target in a rotated sorted array, or -1.',starter:'def search_rotated(nums, target):\n    pass',hint:'At every midpoint, at least one half is still normally sorted.',lesson:'Binary search works whenever each comparison lets you discard a guaranteed region.',complexity:'O(log n) time',public:[["([4,5,6,7,0,1,2], 0)",'4'],["([4,5,6,7,0,1,2], 3)",'-1']],hidden:[["([1], 0)",'-1'],["([1],1)",'0']],phase4:true,companies:['Meta-style','Google-style'],solution:'def search_rotated(nums, target):\n    l,r=0,len(nums)-1\n    while l<=r:\n        m=(l+r)//2\n        if nums[m]==target: return m\n        if nums[l] <= nums[m]:\n            if nums[l] <= target < nums[m]: r=m-1\n            else: l=m+1\n        else:\n            if nums[m] < target <= nums[r]: l=m+1\n            else: r=m-1\n    return -1'},
{id:'find-min-rotated',title:'Find Minimum in Rotated Sorted Array',diff:'Medium',pattern:'Binary Search',district:'search',fn:'find_min',money:300,rp:54,prompt:'Return the minimum value in a rotated sorted array of unique values.',starter:'def find_min(nums):\n    pass',hint:'Compare the midpoint to the right edge to decide which side contains the rotation.',lesson:'Binary search can target structural boundaries, not just exact values.',complexity:'O(log n) time',public:[["([3,4,5,1,2],)",'1'],["([4,5,6,7,0,1,2],)",'0']],hidden:[["([11,13,15,17],)",'11']],phase4:true,companies:['Foundations'],solution:'def find_min(nums):\n    l,r=0,len(nums)-1\n    while l<r:\n        m=(l+r)//2\n        if nums[m] > nums[r]: l=m+1\n        else: r=m\n    return nums[l]'},
{id:'merge-intervals',title:'Merge Intervals',diff:'Medium',pattern:'Intervals',district:'arrays',fn:'merge_intervals',money:310,rp:56,prompt:'Merge all overlapping intervals and return the merged list.',starter:'def merge_intervals(intervals):\n    pass',hint:'Sort by start time, then compare each interval to the most recently merged interval.',lesson:'Sorting often converts global overlap problems into a single linear scan.',complexity:'O(n log n) time',normalize:'intervals',public:[["([[1,3],[2,6],[8,10],[15,18]],)",'[[1,6],[8,10],[15,18]]'],["([[1,4],[4,5]],)",'[[1,5]]']],hidden:[["([],)",'[]'],["([[1,4],[0,4]],)",'[[0,4]]']],phase4:true,companies:['Amazon-style','Foundations'],solution:'def merge_intervals(intervals):\n    intervals=sorted(intervals)\n    out=[]\n    for start,end in intervals:\n        if not out or start > out[-1][1]: out.append([start,end])\n        else: out[-1][1]=max(out[-1][1],end)\n    return out'},
{id:'meeting-rooms',title:'Meeting Rooms',diff:'Easy',pattern:'Intervals',district:'arrays',fn:'can_attend_meetings',money:160,rp:25,prompt:'Return True if a person can attend every interval without overlap.',starter:'def can_attend_meetings(intervals):\n    pass',hint:'Sort intervals by start and compare adjacent meetings.',lesson:'Once intervals are ordered, many overlap checks become local.',complexity:'O(n log n) time',public:[["([[0,30],[5,10],[15,20]],)",'False'],["([[7,10],[2,4]],)",'True']],hidden:[["([],)",'True']],phase4:true,companies:['Amazon-style'],solution:'def can_attend_meetings(intervals):\n    intervals=sorted(intervals)\n    return all(intervals[i-1][1] <= intervals[i][0] for i in range(1,len(intervals)))'},
{id:'house-robber',title:'House Robber',diff:'Medium',pattern:'Dynamic Programming',district:'dp',fn:'rob',money:300,rp:58,prompt:'Return the maximum amount you can rob without robbing adjacent houses.',starter:'def rob(nums):\n    pass',hint:'At each house choose between skipping it or adding it to the best result from two houses back.',lesson:'Many DP problems reduce to a tiny rolling state.',complexity:'O(n) time · O(1) space',public:[["([1,2,3,1],)",'4'],["([2,7,9,3,1],)",'12']],hidden:[["([],)",'0'],["([5],)",'5']],phase4:true,companies:['Foundations','Amazon-style'],solution:'def rob(nums):\n    prev2=prev1=0\n    for n in nums:\n        prev2,prev1=prev1,max(prev1,prev2+n)\n    return prev1'},
{id:'decode-ways',title:'Decode Ways',diff:'Medium',pattern:'Dynamic Programming',district:'dp',fn:'num_decodings',money:330,rp:62,prompt:'Digits map 1→A through 26→Z. Return the number of valid decodings.',starter:'def num_decodings(s):\n    pass',hint:'A position may extend a valid one-digit decode and sometimes a valid two-digit decode.',lesson:'DP often counts paths through a constrained state graph.',complexity:'O(n) time · O(1) space',public:[["('12',)",'2'],["('226',)",'3']],hidden:[["('06',)",'0'],["('1',)",'1']],phase4:true,companies:['Google-style'],solution:'def num_decodings(s):\n    if not s or s[0]=="0": return 0\n    two,one=1,1\n    for i in range(1,len(s)):\n        cur=0\n        if s[i] != "0": cur += one\n        if 10 <= int(s[i-1:i+1]) <= 26: cur += two\n        two,one=one,cur\n    return one'},
{id:'lis',title:'Longest Increasing Subsequence',diff:'Medium',pattern:'Dynamic Programming / Binary Search',district:'dp',fn:'length_of_lis',money:360,rp:68,prompt:'Return the length of the longest strictly increasing subsequence.',starter:'def length_of_lis(nums):\n    pass',hint:'For the O(n log n) version, maintain the smallest possible tail for each subsequence length.',lesson:'The tails array compresses many candidate subsequences into only the information future values need.',complexity:'O(n log n) target',public:[["([10,9,2,5,3,7,101,18],)",'4'],["([0,1,0,3,2,3],)",'4']],hidden:[["([7,7,7,7],)",'1'],["([],)",'0']],phase4:true,companies:['Google-style','Meta-style'],solution:'def length_of_lis(nums):\n    import bisect\n    tails=[]\n    for n in nums:\n        i=bisect.bisect_left(tails,n)\n        if i==len(tails): tails.append(n)\n        else: tails[i]=n\n    return len(tails)'},
{id:'partition-subset',title:'Partition Equal Subset Sum',diff:'Medium',pattern:'Dynamic Programming',district:'dp',fn:'can_partition',money:360,rp:70,prompt:'Return True if nums can be partitioned into two subsets with equal sum.',starter:'def can_partition(nums):\n    pass',hint:'If total sum is even, ask whether some subset can reach total/2.',lesson:'Subset-sum DP tracks which totals are reachable as items are considered.',complexity:'O(n · target) time',public:[["([1,5,11,5],)",'True'],["([1,2,3,5],)",'False']],hidden:[["([2,2,1,1],)",'True']],phase4:true,companies:['Meta-style'],solution:'def can_partition(nums):\n    total=sum(nums)\n    if total%2: return False\n    target=total//2; reachable={0}\n    for n in nums:\n        reachable |= {x+n for x in list(reachable) if x+n<=target}\n    return target in reachable'},
{id:'unique-paths',title:'Unique Paths',diff:'Medium',pattern:'Grid DP',district:'dp',fn:'unique_paths',money:290,rp:55,prompt:'A robot moves only right/down in an m×n grid. Return the number of unique paths.',starter:'def unique_paths(m, n):\n    pass',hint:'Each cell can be reached from the cell above plus the cell to the left.',lesson:'Grid DP is often just a spatial form of recurrence bookkeeping.',complexity:'O(mn) time; O(n) space possible',public:[["(3,7)",'28'],["(3,2)",'3']],hidden:[["(1,1)",'1']],phase4:true,companies:['Foundations'],solution:'def unique_paths(m, n):\n    row=[1]*n\n    for _ in range(m-1):\n        for j in range(n-2,-1,-1): row[j]+=row[j+1]\n    return row[0]'},
{id:'jump-game',title:'Jump Game',diff:'Medium',pattern:'Greedy',district:'arrays',fn:'can_jump',money:300,rp:56,prompt:'Each nums[i] is maximum jump length. Return whether the final index is reachable.',starter:'def can_jump(nums):\n    pass',hint:'Track the farthest index reachable so far.',lesson:'Greedy works when a single frontier summarizes every useful prior choice.',complexity:'O(n) time · O(1) space',public:[["([2,3,1,1,4],)",'True'],["([3,2,1,0,4],)",'False']],hidden:[["([0],)",'True']],phase4:true,companies:['Amazon-style'],solution:'def can_jump(nums):\n    far=0\n    for i,n in enumerate(nums):\n        if i>far: return False\n        far=max(far,i+n)\n    return True'},
{id:'min-path-sum',title:'Minimum Path Sum',diff:'Medium',pattern:'Grid DP',district:'dp',fn:'min_path_sum',money:330,rp:62,prompt:'Return the minimum sum path from top-left to bottom-right moving only right/down.',starter:'def min_path_sum(grid):\n    pass',hint:'The cheapest path into a cell comes from the cheaper of its top and left neighbors.',lesson:'Optimization DP replaces path enumeration with the best known partial result.',complexity:'O(rows × cols) time',public:[["([[1,3,1],[1,5,1],[4,2,1]],)",'7'],["([[1,2,3],[4,5,6]],)",'12']],hidden:[["([[5]],)",'5']],phase4:true,companies:['Google-style'],solution:'def min_path_sum(grid):\n    dp=[float("inf")]*len(grid[0]); dp[0]=0\n    for row in grid:\n        for j,v in enumerate(row):\n            dp[j]=v+min(dp[j],dp[j-1] if j else float("inf"))\n    return dp[-1]'},
{id:'course-schedule',title:'Course Schedule',diff:'Medium',pattern:'Topological Sort',district:'graphs',fn:'can_finish',money:360,rp:72,prompt:'Given num_courses and prerequisite pairs [course, prerequisite], return whether all courses can be finished.',starter:'def can_finish(num_courses, prerequisites):\n    pass',hint:'A directed cycle makes completion impossible. Use indegrees/Kahn BFS or DFS cycle coloring.',lesson:'Dependency ordering is a graph problem even when the domain talks about courses or jobs.',complexity:'O(V + E) time',public:[["(2, [[1,0]])",'True'],["(2, [[1,0],[0,1]])",'False']],hidden:[["(1, [])",'True']],phase4:true,companies:['Amazon-style','Google-style'],solution:'def can_finish(num_courses, prerequisites):\n    graph=[[] for _ in range(num_courses)]; indeg=[0]*num_courses\n    for course,pre in prerequisites:\n        graph[pre].append(course); indeg[course]+=1\n    q=[i for i,d in enumerate(indeg) if d==0]; seen=0\n    while q:\n        node=q.pop(); seen+=1\n        for nxt in graph[node]:\n            indeg[nxt]-=1\n            if indeg[nxt]==0: q.append(nxt)\n    return seen==num_courses'},
{id:'connected-components',title:'Number of Connected Components',diff:'Medium',pattern:'DFS / Union Find',district:'graphs',fn:'count_components',money:350,rp:68,prompt:'Given n nodes labeled 0..n-1 and undirected edges, return the number of connected components.',starter:'def count_components(n, edges):\n    pass',hint:'Build adjacency and start a traversal from each unseen node, or union endpoints.',lesson:'Counting components is repeated graph discovery.',complexity:'O(V + E) time',public:[["(5, [[0,1],[1,2],[3,4]])",'2'],["(5, [[0,1],[1,2],[2,3],[3,4]])",'1']],hidden:[["(3, [])",'3']],phase4:true,companies:['Meta-style'],solution:'def count_components(n, edges):\n    graph=[[] for _ in range(n)]\n    for a,b in edges: graph[a].append(b); graph[b].append(a)\n    seen=set(); count=0\n    for i in range(n):\n        if i in seen: continue\n        count+=1; stack=[i]; seen.add(i)\n        while stack:\n            node=stack.pop()\n            for nxt in graph[node]:\n                if nxt not in seen: seen.add(nxt); stack.append(nxt)\n    return count'},
{id:'redundant-connection',title:'Redundant Connection',diff:'Medium',pattern:'Union Find',district:'graphs',fn:'find_redundant_connection',money:360,rp:70,prompt:'A tree gained one extra edge. Return the edge that creates the cycle.',starter:'def find_redundant_connection(edges):\n    pass',hint:'Union endpoints. The first edge whose endpoints already share a root is redundant.',lesson:'Union-Find is a compact way to maintain connectivity as edges arrive.',complexity:'Near O(n) amortized',public:[["([[1,2],[1,3],[2,3]],)",'[2,3]'],["([[1,2],[2,3],[3,4],[1,4],[1,5]],)",'[1,4]']],hidden:[["([[1,2],[2,3],[1,3]],)",'[1,3]']],phase4:true,companies:['Google-style'],solution:'def find_redundant_connection(edges):\n    parent=list(range(len(edges)+1))\n    def find(x):\n        while x!=parent[x]:\n            parent[x]=parent[parent[x]]; x=parent[x]\n        return x\n    for a,b in edges:\n        ra,rb=find(a),find(b)\n        if ra==rb: return [a,b]\n        parent[ra]=rb'},
{id:'rotting-oranges',title:'Rotting Oranges',diff:'Medium',pattern:'BFS',district:'graphs',fn:'oranges_rotting',money:340,rp:66,prompt:'Each minute, rotten oranges infect adjacent fresh oranges. Return minutes until none are fresh, or -1.',starter:'def oranges_rotting(grid):\n    pass',hint:'Start BFS simultaneously from every rotten orange; each BFS layer is one minute.',lesson:'Multi-source BFS models processes that expand outward in parallel.',complexity:'O(rows × cols) time',public:[["([[2,1,1],[1,1,0],[0,1,1]],)",'4'],["([[2,1,1],[0,1,1],[1,0,1]],)",'-1']],hidden:[["([[0,2]],)",'0']],phase4:true,companies:['Amazon-style'],solution:'def oranges_rotting(grid):\n    from collections import deque\n    q=deque(); fresh=0\n    for r,row in enumerate(grid):\n        for c,v in enumerate(row):\n            if v==2: q.append((r,c,0))\n            elif v==1: fresh+=1\n    minutes=0\n    while q:\n        r,c,minutes=q.popleft()\n        for dr,dc in ((1,0),(-1,0),(0,1),(0,-1)):\n            nr,nc=r+dr,c+dc\n            if 0<=nr<len(grid) and 0<=nc<len(grid[0]) and grid[nr][nc]==1:\n                grid[nr][nc]=2; fresh-=1; q.append((nr,nc,minutes+1))\n    return -1 if fresh else minutes'},
{id:'word-search',title:'Word Search',diff:'Medium',pattern:'Backtracking',district:'graphs',fn:'exist',money:370,rp:72,prompt:'Return True if word can be formed by adjacent horizontal/vertical cells without reusing a cell.',starter:'def exist(board, word):\n    pass',hint:'Start DFS from matching cells and mark a cell used only for the current recursive path.',lesson:'Backtracking explores choices while undoing temporary state after each branch.',complexity:'O(rows × cols × 4^L) worst case',public:[["([['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], 'ABCCED')",'True'],["([['A','B','C','E'],['S','F','C','S'],['A','D','E','E']], 'ABCB')",'False']],hidden:[["([['a']], 'a')",'True']],phase4:true,companies:['Meta-style','Google-style'],solution:'def exist(board, word):\n    rows,cols=len(board),len(board[0])\n    def dfs(r,c,i):\n        if i==len(word): return True\n        if r<0 or c<0 or r>=rows or c>=cols or board[r][c]!=word[i]: return False\n        ch=board[r][c]; board[r][c]="#"\n        ok=dfs(r+1,c,i+1) or dfs(r-1,c,i+1) or dfs(r,c+1,i+1) or dfs(r,c-1,i+1)\n        board[r][c]=ch\n        return ok\n    return any(dfs(r,c,0) for r in range(rows) for c in range(cols))'}
];

CHALLENGES.push(...PHASE4_CHALLENGES);

const PHASE4_REFERENCE_SOLUTIONS={
  'two-sum':'def two_sum(nums, target):\n    seen={}\n    for i,n in enumerate(nums):\n        need=target-n\n        if need in seen: return [seen[need],i]\n        seen[n]=i',
  'valid-parens':'def is_valid(s):\n    pairs={")":"(","]":"[","}":"{"}; stack=[]\n    for ch in s:\n        if ch in "([{": stack.append(ch)\n        elif not stack or stack.pop()!=pairs[ch]: return False\n    return not stack',
  'max-profit':'def max_profit(prices):\n    low=float("inf"); best=0\n    for p in prices:\n        low=min(low,p); best=max(best,p-low)\n    return best',
  'binary-search':'def search(nums, target):\n    l,r=0,len(nums)-1\n    while l<=r:\n        m=(l+r)//2\n        if nums[m]==target:return m\n        if nums[m]<target:l=m+1\n        else:r=m-1\n    return -1',
  'longest-substring':'def length_of_longest_substring(s):\n    last={}; left=best=0\n    for right,ch in enumerate(s):\n        if ch in last and last[ch]>=left:left=last[ch]+1\n        last[ch]=right; best=max(best,right-left+1)\n    return best',
  'three-sum':'def three_sum(nums):\n    nums.sort(); out=[]\n    for i,a in enumerate(nums):\n        if i and a==nums[i-1]: continue\n        l,r=i+1,len(nums)-1\n        while l<r:\n            total=a+nums[l]+nums[r]\n            if total<0:l+=1\n            elif total>0:r-=1\n            else:\n                out.append([a,nums[l],nums[r]]); l+=1; r-=1\n                while l<r and nums[l]==nums[l-1]:l+=1\n    return out',
  'num-islands':'def num_islands(grid):\n    if not grid:return 0\n    rows,cols=len(grid),len(grid[0]); count=0\n    def flood(r,c):\n        if r<0 or c<0 or r>=rows or c>=cols or grid[r][c]!="1":return\n        grid[r][c]="0"\n        flood(r+1,c);flood(r-1,c);flood(r,c+1);flood(r,c-1)\n    for r in range(rows):\n        for c in range(cols):\n            if grid[r][c]=="1":count+=1;flood(r,c)\n    return count',
  'coin-change':'def coin_change(coins, amount):\n    dp=[amount+1]*(amount+1);dp[0]=0\n    for x in range(1,amount+1):\n        for coin in coins:\n            if coin<=x:dp[x]=min(dp[x],1+dp[x-coin])\n    return -1 if dp[amount]>amount else dp[amount]'
};

const PRACTICE_PLAYLISTS={
  adaptive:{name:'Adaptive Coach',description:'Prioritizes weak, decayed, and recently failed patterns.',ids:[]},
  foundations:{name:'Foundations Mix',description:'Core interview patterns before specialization.',ids:['two-sum','contains-duplicate','valid-parens','valid-palindrome','binary-search','max-profit','meeting-rooms','house-robber']},
  arrays:{name:'Arrays & Windows',description:'Pointers, sliding windows, intervals, prefix/suffix, and greedy.',ids:['max-profit','longest-substring','three-sum','product-except-self','valid-palindrome','container-water','character-replacement','min-window','merge-intervals','meeting-rooms','jump-game']},
  graphs:{name:'Graphs & Traversal',description:'DFS, BFS, topological ordering, Union-Find, and backtracking.',ids:['num-islands','course-schedule','connected-components','redundant-connection','rotting-oranges','word-search']},
  dp:{name:'Dynamic Programming',description:'State transitions, grid DP, subset DP, and optimization.',ids:['coin-change','house-robber','decode-ways','lis','partition-subset','unique-paths','min-path-sum']},
  meta:{name:'Meta-style Practice',description:'A broad practice mix inspired by common interview categories; not a claimed current question list.',ids:['group-anagrams','container-water','character-replacement','search-rotated','lis','connected-components','word-search']},
  google:{name:'Google-style Practice',description:'Algorithm-heavy practice mix; not a claimed current question list.',ids:['product-except-self','min-window','largest-rectangle','search-rotated','decode-ways','min-path-sum','course-schedule','redundant-connection','word-search']},
  amazon:{name:'Amazon-style Practice',description:'Practical data-structure and graph mix; not a claimed current question list.',ids:['contains-duplicate','top-k-frequent','daily-temperatures','meeting-rooms','house-robber','jump-game','course-schedule','rotting-oranges']}
};

const RECALL_QUESTIONS=[
{pattern:'Hash Map',q:'What is the main reason to introduce a hash map in an interview solution?',options:['To preserve sorting','To trade extra memory for fast lookup','To guarantee recursion','To reduce all algorithms to O(1)'],answer:1},
{pattern:'Two Pointers',q:'When is a two-pointer approach especially promising?',options:['When relationships depend on two positions in ordered or symmetric data','Only for graphs','Only when recursion is banned','Whenever input is a dictionary'],answer:0},
{pattern:'Sliding Window',q:'What distinguishes a sliding-window problem?',options:['The answer depends on a contiguous region whose validity can be updated incrementally','It always requires sorting','It always uses a heap','It only works on matrices'],answer:0},
{pattern:'Monotonic Stack',q:'What does a monotonic stack help avoid?',options:['Repeated scans for the next greater/smaller boundary','Hash collisions','Graph cycles','Binary search'],answer:0},
{pattern:'Binary Search',q:'What must be true for binary search reasoning to work?',options:['Every midpoint comparison must let you discard a guaranteed region','The array must contain unique positive values','You must use recursion','The answer must be an index'],answer:0},
{pattern:'Intervals',q:'What is often the first useful transformation for interval problems?',options:['Sort by start/end boundary','Convert to a tree','Reverse every interval','Use BFS'],answer:0},
{pattern:'DFS / BFS',q:'What question should make you think “graph traversal”?',options:['How are states/nodes connected and which are reachable?','How can I sort this list?','How can I calculate a prefix sum?','How do I find a median?'],answer:0},
{pattern:'Dynamic Programming',q:'What are the two strongest clues for DP?',options:['Overlapping subproblems and reusable optimal/counting state','Sorted input and unique values','Only recursion and trees','Constant-size input'],answer:0},
{pattern:'Greedy',q:'What must a greedy choice preserve?',options:['It must leave a state where locally best progress cannot block the global solution','It must enumerate every possibility','It must always sort descending','It must use O(1) time'],answer:0},
{pattern:'Union Find',q:'What does Union-Find maintain efficiently?',options:['Connectivity among dynamically joined components','Substring frequencies','Heap order','Matrix prefixes'],answer:0}
];

state.learning=Object.assign({playlist:'adaptive',timerMinutes:30,timerActive:false,timerStartedAt:null,timerProblemId:null,recallCorrect:0,recallTotal:0,lastRecall:null,sessionSolved:0,sessionStartedAt:null},state.learning||{});
for(const c of CHALLENGES){const m=masteryFor(c.id);if(m.strength==null)m.strength=m.passes?Math.min(100,45+m.passes*12):0;if(m.intervalDays==null)m.intervalDays=1;if(m.nextReviewAt==null&&m.lastSolvedAt)m.nextReviewAt=new Date(new Date(m.lastSolvedAt).getTime()+86400000).toISOString();state.mastery[c.id]=m}
persist(false);

const baseUnlocked=unlocked;
unlocked=function(c){if(c.phase4)return state.eraLevel>=3;return baseUnlocked(c)};

const basePythonHarness=pythonHarness;
pythonHarness=function(c,code,cases){if(!c.normalize||c.normalize==='triplets')return basePythonHarness(c,code,cases);const payload=JSON.stringify(cases);let normalizer='def normalize(v):\n    return v';if(c.normalize==='groups')normalizer='def normalize(v):\n    return sorted([sorted(list(group)) for group in v])';if(c.normalize==='unordered')normalizer='def normalize(v):\n    return sorted(list(v))';if(c.normalize==='intervals')normalizer='def normalize(v):\n    return sorted([list(x) for x in v])';return `import json, traceback, time, copy\n${normalizer}\nns={}\ntry:\n    exec(${JSON.stringify(code)}, ns)\n    fn=ns.get(${JSON.stringify(c.fn)})\n    if not callable(fn):\n        raise NameError('Expected a function named ${c.fn}')\n    cases=json.loads(${JSON.stringify(payload)})\n    results=[]\n    started=time.perf_counter()\n    for idx,pair in enumerate(cases):\n        args=eval(pair[0], {})\n        expected=eval(pair[1], {})\n        try:\n            actual=fn(*copy.deepcopy(args))\n            ok=normalize(actual)==normalize(expected)\n            results.append({'index':idx,'ok':ok,'actual':repr(actual),'expected':repr(expected),'error':None})\n        except Exception as e:\n            results.append({'index':idx,'ok':False,'actual':None,'expected':repr(expected),'error':type(e).__name__+': '+str(e)})\n    elapsed=(time.perf_counter()-started)*1000\n    json.dumps({'fatal':None,'elapsed':elapsed,'results':results})\nexcept Exception as e:\n    json.dumps({'fatal':type(e).__name__+': '+str(e),'trace':traceback.format_exc(limit=2),'elapsed':0,'results':[]})`};

function daysSince(value){if(!value)return 999;return Math.max(0,(Date.now()-new Date(value).getTime())/86400000)}
function effectiveStrength(c){const m=masteryFor(c.id);if(!m.passes)return 0;const decay=Math.max(0,daysSince(m.lastSolvedAt)-m.intervalDays)*4;const failurePenalty=Math.max(0,m.attempts-m.passes)*3;return Math.max(0,Math.round((m.strength||50)-decay-failurePenalty))}
function dueForAdaptive(c){const m=masteryFor(c.id);return !!m.nextReviewAt&&new Date(m.nextReviewAt).getTime()<=Date.now()}
function adaptiveScore(c){if(!unlocked(c))return -9999;const m=masteryFor(c.id);let score=100-effectiveStrength(c);if(!state.solved.includes(c.id))score+=35;if(dueForAdaptive(c))score+=45;const recent=state.history.slice(0,12).find(h=>h.id===c.id);if(recent&&!recent.passed)score+=30;const district=state.districtXP[c.district]||0;score+=Math.max(0,35-district/8);if(state.current===c.id)score-=12;return score}
function adaptiveQueue(limit=8){return CHALLENGES.filter(unlocked).sort((a,b)=>adaptiveScore(b)-adaptiveScore(a)).slice(0,limit)}
function playlistChallenges(key=state.learning.playlist){const p=PRACTICE_PLAYLISTS[key]||PRACTICE_PLAYLISTS.adaptive;if(key==='adaptive')return adaptiveQueue(12);return p.ids.map(id=>CHALLENGES.find(c=>c.id===id)).filter(c=>c&&unlocked(c))}
function chooseNextAdaptive(){const choices=playlistChallenges();if(!choices.length)return null;const currentIndex=choices.findIndex(c=>c.id===state.current);return choices[(currentIndex+1+choices.length)%choices.length]||choices[0]}
function selectRecommended(){const c=adaptiveQueue(1)[0];if(c)selectChallenge(c.id)}
function setPlaylist(key){if(!PRACTICE_PLAYLISTS[key])return;state.learning.playlist=key;persist(false);renderLearning();renderMission()}

function scheduleMastery(c,passed){const m=masteryFor(c.id);if(passed){m.strength=Math.min(100,(m.strength||20)+18);m.intervalDays=Math.min(30,Math.max(1,Math.round((m.intervalDays||1)*1.8)));m.nextReviewAt=new Date(Date.now()+m.intervalDays*86400000).toISOString()}else{m.strength=Math.max(0,(m.strength||20)-12);m.intervalDays=1;m.nextReviewAt=new Date(Date.now()+86400000).toISOString()}state.mastery[c.id]=m}

const baseSubmitCode=submitCode;
submitCode=async function(){const c=current(),before=masteryFor(c.id).passes||0;await baseSubmitCode();const after=masteryFor(c.id).passes||0;const passed=after>before;scheduleMastery(c,passed);if(passed){state.learning.sessionSolved=(state.learning.sessionSolved||0)+1;showWalkthroughButton(c)}persist(false);renderLearning()};

const baseRunVisibleTests=runVisibleTests;
runVisibleTests=async function(){if(state.learning.timerActive&&state.learning.timerProblemId!==current().id){state.learning.timerProblemId=current().id;state.learning.timerStartedAt=Date.now();persist(false)}return baseRunVisibleTests()};

function referenceSolution(c){return c.solution||PHASE4_REFERENCE_SOLUTIONS[c.id]||null}
function showWalkthroughButton(c=current()){const fb=$('#feedback');if(!fb||!state.solved.includes(c.id))return;if(!fb.querySelector('.walkthrough-btn'))fb.insertAdjacentHTML('beforeend',`<div class="actions"><button class="btn walkthrough-btn" onclick="showWalkthrough('${c.id}')">📘 Post-solve walkthrough</button></div>`)}
function showWalkthrough(id){const c=CHALLENGES.find(x=>x.id===id);if(!c)return;const sol=referenceSolution(c);const fb=$('#feedback');if(!fb)return;fb.innerHTML+=`<div class="walkthrough"><h4>${esc(c.pattern)} walkthrough</h4><p>${esc(c.lesson)}</p><p><b>Recognition clue:</b> ${esc(c.hint)}</p><p><b>Target:</b> ${esc(c.complexity)}</p>${sol?`<details><summary>Reference solution</summary><pre>${esc(sol)}</pre></details>`:''}<p class="muted">Reference solutions are for post-solve study. Re-code the pattern later from memory rather than memorizing syntax.</p></div>`}

function startTimer(minutes=state.learning.timerMinutes){state.learning.timerMinutes=Number(minutes)||30;state.learning.timerActive=true;state.learning.timerStartedAt=Date.now();state.learning.timerProblemId=current().id;state.learning.sessionStartedAt=state.learning.sessionStartedAt||new Date().toISOString();persist(false);renderLearning()}
function stopTimer(){state.learning.timerActive=false;state.learning.timerStartedAt=null;state.learning.timerProblemId=null;persist(false);renderLearning()}
function timerRemaining(){if(!state.learning.timerActive||!state.learning.timerStartedAt)return state.learning.timerMinutes*60;return Math.max(0,state.learning.timerMinutes*60-Math.floor((Date.now()-state.learning.timerStartedAt)/1000))}
function renderTimer(){const el=$('#interviewTimer');if(!el)return;const remaining=timerRemaining();if(state.learning.timerActive&&remaining<=0){state.learning.timerActive=false;persist(false);el.innerHTML='<b>⏰ Interview block complete.</b><div class="muted">Review your reasoning, then submit or inspect the walkthrough after solving.</div>';return}const min=Math.floor(remaining/60),sec=remaining%60;el.innerHTML=`<div class="timer-clock">${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}</div><div class="muted">${state.learning.timerActive?`Timed: ${esc((CHALLENGES.find(c=>c.id===state.learning.timerProblemId)||current()).title)}`:'Interview timer is idle.'}</div><div class="actions">${state.learning.timerActive?'<button class="btn" onclick="stopTimer()">Stop</button>':`<button class="btn" onclick="startTimer(20)">20 min</button><button class="btn" onclick="startTimer(30)">30 min</button><button class="btn" onclick="startTimer(45)">45 min</button>`}</div>`}
setInterval(()=>{if(state.learning.timerActive)renderTimer()},1000);

function recallQuestion(){if(state.learning.lastRecall){const last=RECALL_QUESTIONS.findIndex(q=>q.q===state.learning.lastRecall);return RECALL_QUESTIONS[(last+1)%RECALL_QUESTIONS.length]}const weak=adaptiveQueue(5).map(c=>c.pattern);return RECALL_QUESTIONS.find(q=>weak.some(p=>p.includes(q.pattern)||q.pattern.includes(p)))||RECALL_QUESTIONS[0]}
function answerRecall(index){const q=recallQuestion();state.learning.recallTotal++;const ok=Number(index)===q.answer;if(ok){state.learning.recallCorrect++;state.research+=4}else state.happiness=Math.max(25,state.happiness-1);state.learning.lastRecall=q.q;persist(false);const el=$('#recallDrill');if(el)el.innerHTML=`<div class="feedback ${ok?'pass':'fail'}"><b>${ok?'✅ Correct':'❌ Not quite'}</b><br>${esc(q.options[q.answer])}</div><button class="btn" onclick="renderLearning()">Next recall</button>`}

function renderLearning(){const tab=$('#learningTab');if(!tab)return;const queue=adaptiveQueue(8),playlist=PRACTICE_PLAYLISTS[state.learning.playlist]||PRACTICE_PLAYLISTS.adaptive;const q=recallQuestion();const playlistOptions=Object.entries(PRACTICE_PLAYLISTS).map(([key,p])=>`<option value="${key}" ${state.learning.playlist===key?'selected':''}>${esc(p.name)}</option>`).join('');tab.innerHTML=`
<div class="learning-grid">
  <section class="learning-card"><h3>🧭 Adaptive Coach</h3><p class="muted">Scores problems using mastery strength, time decay, failures, district weakness, and whether a problem is new.</p><button class="btn primary" onclick="selectRecommended()">Practice highest priority</button><div class="adaptive-list">${queue.map((c,i)=>{const m=masteryFor(c.id);return `<button class="adaptive-row" onclick="selectChallenge('${c.id}')"><b>${i+1}. ${esc(c.title)}</b><span>${esc(c.pattern)} · strength ${effectiveStrength(c)}% ${dueForAdaptive(c)?'· REVIEW DUE':''}</span></button>`}).join('')}</div></section>
  <section class="learning-card"><h3>🗂️ Practice Playlist</h3><select class="learning-select" onchange="setPlaylist(this.value)">${playlistOptions}</select><p class="muted">${esc(playlist.description)}</p><div>${playlistChallenges().slice(0,10).map(c=>`<button class="btn mini" onclick="selectChallenge('${c.id}')">${esc(c.title)}</button>`).join(' ')||'<span class="muted">Advance your era to unlock this mix.</span>'}</div></section>
  <section class="learning-card"><h3>⏱️ Interview Mode</h3><div id="interviewTimer"></div><p class="muted">Timer is deliberately client-side and does not auto-fail you. The goal is realistic pacing plus post-session reflection.</p></section>
  <section class="learning-card"><h3>🧠 Recall Drill</h3><div id="recallDrill"><span class="tag">${esc(q.pattern)}</span><p><b>${esc(q.q)}</b></p>${q.options.map((o,i)=>`<button class="recall-option" onclick="answerRecall(${i})">${esc(o)}</button>`).join('')}</div><div class="muted">Recall accuracy: ${state.learning.recallTotal?Math.round(state.learning.recallCorrect/state.learning.recallTotal*100):0}% (${state.learning.recallCorrect}/${state.learning.recallTotal})</div></section>
</div>`;renderTimer()}

const baseRender=render;
render=function(){baseRender();renderLearning();showWalkthroughButton();const phase=$('#phaseLabel');if(phase)phase.textContent='Phase 4 · Adaptive Learning'};

const baseRenderMission=renderMission;
renderMission=function(){const choices=state.learning.playlist==='adaptive'?adaptiveQueue(12):playlistChallenges();const filtered=choices.length?choices:CHALLENGES.filter(unlocked);mission.innerHTML=filtered.slice(0,18).map(c=>{const m=masteryFor(c.id),strength=effectiveStrength(c);return `<button class="btn" style="width:100%;margin:4px 0;text-align:left" onclick="selectChallenge('${c.id}')">${state.solved.includes(c.id)?'✅':'▶️'} ${esc(c.title)} <span class="muted">· ${esc(c.pattern)} · ${strength}%${dueForAdaptive(c)?' · review':''}</span></button>`}).join('');};

const baseNextChallenge=nextChallenge;
nextChallenge=function(){if(state.learning.playlist&&state.learning.playlist!=='adaptive'){const next=chooseNextAdaptive();if(next){state.current=next.id;persist();switchTab('challenge');return}}const recommended=adaptiveQueue(2).find(c=>c.id!==state.current);if(recommended&&state.eraLevel>=3){state.current=recommended.id;persist();switchTab('challenge');return}baseNextChallenge()};

const baseRenderStats=renderStats;
renderStats=function(){baseRenderStats();const root=$('#statsTab');if(!root)return;const unlockedProblems=CHALLENGES.filter(unlocked),avg=unlockedProblems.length?Math.round(unlockedProblems.reduce((s,c)=>s+effectiveStrength(c),0)/unlockedProblems.length):0,due=unlockedProblems.filter(dueForAdaptive).length;root.insertAdjacentHTML('afterbegin',`<div class="phase4-metrics"><div class="metric"><b>${CHALLENGES.length}</b><div class="muted">problem bank</div></div><div class="metric"><b>${avg}%</b><div class="muted">effective mastery</div></div><div class="metric"><b>${due}</b><div class="muted">adaptive reviews due</div></div><div class="metric"><b>${state.learning.recallTotal?Math.round(state.learning.recallCorrect/state.learning.recallTotal*100):0}%</b><div class="muted">recall accuracy</div></div></div>`)};

// Ensure the new layer is visible immediately after app.js finishes its initial render.
render();
