// Phase 5: interview realism, data structures, mocks, and session analytics.
const PHASE5_CHALLENGES=[
{id:'reverse-list',title:'Reverse Linked List',diff:'Easy',pattern:'Linked List',district:'structures',fn:'reverse_list',inputAdapter:'list_first',outputAdapter:'listnode',money:180,rp:28,prompt:'Reverse a singly linked list and return the new head. ListNode is provided.',starter:'def reverse_list(head):\n    pass',hint:'Track prev, current, and the next node before rewiring each pointer.',lesson:'Linked-list problems are pointer-state problems: preserve what you need before mutation.',complexity:'O(n) time · O(1) space',public:[["([1,2,3,4,5],)",'[5,4,3,2,1]'],["([1,2],)",'[2,1]']],hidden:[["([],)",'[]'],["([1],)",'[1]']],phase5:true,companies:['Foundations','Meta-style'],solution:'def reverse_list(head):\n    prev=None\n    while head:\n        nxt=head.next\n        head.next=prev\n        prev=head\n        head=nxt\n    return prev'},
{id:'merge-two-lists',title:'Merge Two Sorted Lists',diff:'Easy',pattern:'Linked List',district:'structures',fn:'merge_two_lists',inputAdapter:'two_lists',outputAdapter:'listnode',money:190,rp:30,prompt:'Merge two sorted linked lists and return the head of the merged list.',starter:'def merge_two_lists(list1, list2):\n    pass',hint:'Use a dummy head and repeatedly attach the smaller current node.',lesson:'Dummy nodes simplify head-edge cases and pointer construction.',complexity:'O(n+m) time · O(1) extra space',public:[["([1,2,4],[1,3,4])",'[1,1,2,3,4,4]'],["([],[0])",'[0]']],hidden:[["([],[])",'[]']],phase5:true,companies:['Amazon-style','Foundations'],solution:'def merge_two_lists(a,b):\n    dummy=ListNode(); cur=dummy\n    while a and b:\n        if a.val<=b.val: cur.next,a=a,a.next\n        else: cur.next,b=b,b.next\n        cur=cur.next\n    cur.next=a or b\n    return dummy.next'},
{id:'middle-list',title:'Middle of the Linked List',diff:'Easy',pattern:'Fast / Slow Pointers',district:'structures',fn:'middle_node',inputAdapter:'list_first',outputAdapter:'listnode',money:170,rp:26,prompt:'Return the middle node of a linked list. For even length, return the second middle.',starter:'def middle_node(head):\n    pass',hint:'Move one pointer one step and another two steps.',lesson:'Fast/slow pointers derive relative positions without knowing list length first.',complexity:'O(n) time · O(1) space',public:[["([1,2,3,4,5],)",'[3,4,5]'],["([1,2,3,4,5,6],)",'[4,5,6]']],hidden:[["([1],)",'[1]']],phase5:true,companies:['Foundations'],solution:'def middle_node(head):\n    slow=fast=head\n    while fast and fast.next:\n        slow=slow.next; fast=fast.next.next\n    return slow'},
{id:'remove-nth',title:'Remove Nth Node From End',diff:'Medium',pattern:'Fast / Slow Pointers',district:'structures',fn:'remove_nth_from_end',inputAdapter:'list_first',outputAdapter:'listnode',money:300,rp:52,prompt:'Remove the nth node from the end of a linked list and return its head.',starter:'def remove_nth_from_end(head, n):\n    pass',hint:'Offset fast by n nodes, then move fast and slow together from a dummy head.',lesson:'A fixed pointer gap converts an end-relative position into a single forward pass.',complexity:'O(n) time · O(1) space',public:[["([1,2,3,4,5],2)",'[1,2,3,5]'],["([1],1)",'[]']],hidden:[["([1,2],1)",'[1]']],phase5:true,companies:['Meta-style'],solution:'def remove_nth_from_end(head,n):\n    dummy=ListNode(0,head); fast=slow=dummy\n    for _ in range(n): fast=fast.next\n    while fast.next:\n        fast=fast.next; slow=slow.next\n    slow.next=slow.next.next\n    return dummy.next'},
{id:'invert-tree',title:'Invert Binary Tree',diff:'Easy',pattern:'Tree DFS',district:'graphs',fn:'invert_tree',inputAdapter:'tree_first',outputAdapter:'treenode',money:190,rp:30,prompt:'Invert a binary tree and return its root. TreeNode is provided.',starter:'def invert_tree(root):\n    pass',hint:'Swap left/right at every node, recursively or iteratively.',lesson:'Tree recursion often mirrors the recursive structure of the data itself.',complexity:'O(n) time · O(h) space',public:[["([4,2,7,1,3,6,9],)",'[4,7,2,9,6,3,1]'],["([2,1,3],)",'[2,3,1]']],hidden:[["([],)",'[]']],phase5:true,companies:['Google-style','Foundations'],solution:'def invert_tree(root):\n    if not root:return None\n    root.left,root.right=invert_tree(root.right),invert_tree(root.left)\n    return root'},
{id:'max-depth-tree',title:'Maximum Depth of Binary Tree',diff:'Easy',pattern:'Tree DFS',district:'graphs',fn:'max_depth',inputAdapter:'tree_first',money:180,rp:28,prompt:'Return the maximum depth of a binary tree.',starter:'def max_depth(root):\n    pass',hint:'Depth is 1 plus the larger child depth.',lesson:'Define precisely what your recursive function returns, then combine child results.',complexity:'O(n) time · O(h) space',public:[["([3,9,20,None,None,15,7],)",'3'],["([1,None,2],)",'2']],hidden:[["([],)",'0']],phase5:true,companies:['Amazon-style','Foundations'],solution:'def max_depth(root):\n    if not root:return 0\n    return 1+max(max_depth(root.left),max_depth(root.right))'},
{id:'same-tree',title:'Same Tree',diff:'Easy',pattern:'Tree DFS',district:'graphs',fn:'is_same_tree',inputAdapter:'two_trees',money:180,rp:28,prompt:'Return True if two binary trees are structurally identical with equal values.',starter:'def is_same_tree(p, q):\n    pass',hint:'Compare the current nodes, then compare matching child pairs.',lesson:'Recursive equality requires both local equality and recursive structural equality.',complexity:'O(n) time',public:[["([1,2,3],[1,2,3])",'True'],["([1,2],[1,None,2])",'False']],hidden:[["([],[])",'True']],phase5:true,companies:['Foundations'],solution:'def is_same_tree(p,q):\n    if not p or not q:return p is q\n    return p.val==q.val and is_same_tree(p.left,q.left) and is_same_tree(p.right,q.right)'},
{id:'level-order',title:'Binary Tree Level Order Traversal',diff:'Medium',pattern:'Tree BFS',district:'graphs',fn:'level_order',inputAdapter:'tree_first',money:310,rp:55,prompt:'Return node values level by level from left to right.',starter:'def level_order(root):\n    pass',hint:'Process the queue in fixed-size batches, one batch per level.',lesson:'BFS naturally represents distance or level from a source.',complexity:'O(n) time · O(w) space',public:[["([3,9,20,None,None,15,7],)",'[[3],[9,20],[15,7]]'],["([1],)",'[[1]]']],hidden:[["([],)",'[]']],phase5:true,companies:['Meta-style','Amazon-style'],solution:'def level_order(root):\n    if not root:return []\n    q=[root]; out=[]\n    while q:\n        level=[]\n        for _ in range(len(q)):\n            n=q.pop(0); level.append(n.val)\n            if n.left:q.append(n.left)\n            if n.right:q.append(n.right)\n        out.append(level)\n    return out'},
{id:'validate-bst',title:'Validate Binary Search Tree',diff:'Medium',pattern:'BST Invariants',district:'search',fn:'is_valid_bst',inputAdapter:'tree_first',money:320,rp:58,prompt:'Return True if a binary tree is a valid BST.',starter:'def is_valid_bst(root):\n    pass',hint:'Carry lower and upper bounds down the recursion.',lesson:'BST validity is global: each node inherits constraints from every ancestor.',complexity:'O(n) time · O(h) space',public:[["([2,1,3],)",'True'],["([5,1,4,None,None,3,6],)",'False']],hidden:[["([2,2,2],)",'False']],phase5:true,companies:['Google-style','Meta-style'],solution:'def is_valid_bst(root):\n    def dfs(node,lo,hi):\n        if not node:return True\n        if not lo < node.val < hi:return False\n        return dfs(node.left,lo,node.val) and dfs(node.right,node.val,hi)\n    return dfs(root,float("-inf"),float("inf"))'},
{id:'kth-smallest-bst',title:'Kth Smallest Element in a BST',diff:'Medium',pattern:'BST Inorder',district:'search',fn:'kth_smallest',inputAdapter:'tree_first',money:320,rp:58,prompt:'Return the kth smallest value in a BST.',starter:'def kth_smallest(root, k):\n    pass',hint:'Inorder traversal of a BST visits values in sorted order.',lesson:'Exploit structural guarantees before reaching for a general-purpose sort.',complexity:'O(h+k) typical time',public:[["([3,1,4,None,2],1)",'1'],["([5,3,6,2,4,None,None,1],3)",'3']],hidden:[["([2,1,3],2)",'2']],phase5:true,companies:['Meta-style'],solution:'def kth_smallest(root,k):\n    stack=[]\n    while True:\n        while root: stack.append(root); root=root.left\n        root=stack.pop(); k-=1\n        if k==0:return root.val\n        root=root.right'},
{id:'lca-bst',title:'Lowest Common Ancestor of a BST',diff:'Medium',pattern:'BST Invariants',district:'search',fn:'lowest_common_ancestor',inputAdapter:'tree_pq',outputAdapter:'nodeval',money:310,rp:55,prompt:'Given a BST and nodes p and q, return their lowest common ancestor.',starter:'def lowest_common_ancestor(root, p, q):\n    pass',hint:'If both targets are smaller go left; if both are larger go right; otherwise you found the split.',lesson:'BST ordering can turn a general tree search into a directed walk.',complexity:'O(h) time · O(1) space',public:[["([6,2,8,0,4,7,9,None,None,3,5],2,8)",'6'],["([6,2,8,0,4,7,9,None,None,3,5],2,4)",'2']],hidden:[["([2,1],2,1)",'2']],phase5:true,companies:['Amazon-style'],solution:'def lowest_common_ancestor(root,p,q):\n    while root:\n        if p.val<root.val and q.val<root.val: root=root.left\n        elif p.val>root.val and q.val>root.val: root=root.right\n        else:return root'},
{id:'kth-largest',title:'Kth Largest Element in an Array',diff:'Medium',pattern:'Heap',district:'structures',fn:'find_kth_largest',money:320,rp:58,prompt:'Return the kth largest element in an unsorted array.',starter:'def find_kth_largest(nums, k):\n    pass',hint:'Maintain a min-heap of at most k elements.',lesson:'A bounded heap tracks the best k candidates without sorting everything.',complexity:'O(n log k) time',public:[["([3,2,1,5,6,4],2)",'5'],["([3,2,3,1,2,4,5,5,6],4)",'4']],hidden:[["([1],1)",'1']],phase5:true,companies:['Amazon-style','Foundations'],solution:'def find_kth_largest(nums,k):\n    import heapq\n    h=[]\n    for n in nums:\n        heapq.heappush(h,n)\n        if len(h)>k:heapq.heappop(h)\n    return h[0]'},
{id:'last-stone',title:'Last Stone Weight',diff:'Easy',pattern:'Heap',district:'structures',fn:'last_stone_weight',money:190,rp:30,prompt:'Repeatedly smash the two heaviest stones and return the final weight.',starter:'def last_stone_weight(stones):\n    pass',hint:'Python has a min-heap; negate weights to simulate a max-heap.',lesson:'Priority queues model systems where the next action always targets the current extreme.',complexity:'O(n log n) time',public:[["([2,7,4,1,8,1],)",'1'],["([1],)",'1']],hidden:[["([],)",'0']],phase5:true,companies:['Amazon-style'],solution:'def last_stone_weight(stones):\n    import heapq\n    h=[-x for x in stones]; heapq.heapify(h)\n    while len(h)>1:\n        a=-heapq.heappop(h); b=-heapq.heappop(h)\n        if a!=b:heapq.heappush(h,-(a-b))\n    return -h[0] if h else 0'},
{id:'k-closest',title:'K Closest Points to Origin',diff:'Medium',pattern:'Heap',district:'structures',fn:'k_closest',normalize:'unordered',money:320,rp:58,prompt:'Return the k points closest to the origin.',starter:'def k_closest(points, k):\n    pass',hint:'Distance comparison does not require square roots.',lesson:'Heaps are useful when you need only a small extreme subset of a large collection.',complexity:'O(n log k) time',public:[["([[1,3],[-2,2]],1)",'[[-2,2]]'],["([[3,3],[5,-1],[-2,4]],2)",'[[3,3],[-2,4]]']],hidden:[["([[0,1],[1,0]],2)",'[[0,1],[1,0]]']],phase5:true,companies:['Meta-style','Google-style'],solution:'def k_closest(points,k):\n    import heapq\n    return heapq.nsmallest(k,points,key=lambda p:p[0]*p[0]+p[1]*p[1])'},
{id:'task-scheduler',title:'Task Scheduler',diff:'Medium',pattern:'Heap / Greedy',district:'structures',fn:'least_interval',money:340,rp:62,prompt:'Given CPU tasks and cooldown n, return the minimum intervals needed to execute all tasks.',starter:'def least_interval(tasks, n):\n    pass',hint:'Schedule the most frequent available task, while cooling tasks wait until reusable.',lesson:'Greedy scheduling becomes manageable when availability and priority are separated.',complexity:'O(tasks log 26) time',public:[["(['A','A','A','B','B','B'],2)",'8'],["(['A','C','A','B','D','B'],1)",'6']],hidden:[["(['A','A','A','B','B','B'],0)",'6']],phase5:true,companies:['Amazon-style'],solution:'def least_interval(tasks,n):\n    from collections import Counter\n    counts=Counter(tasks).values(); mx=max(counts,default=0); ties=sum(c==mx for c in counts)\n    return max(len(tasks),(mx-1)*(n+1)+ties)'},
{id:'trie-operations',title:'Implement Trie',diff:'Medium',pattern:'Trie',district:'hash',fn:'trie_operations',money:350,rp:65,prompt:'Process operations [insert, search, startsWith] and return outputs for search/startsWith. Implement a trie internally.',starter:'def trie_operations(operations, values):\n    pass',hint:'Each node maps characters to children and stores an end-of-word flag.',lesson:'Tries trade memory for prefix-aware lookup proportional to word length.',complexity:'O(total characters) time',public:[["(['insert','search','search','startsWith','insert','search'],['apple','apple','app','app','app','app'])",'[True,False,True,True]']],hidden:[["(['insert','startsWith','search'],['cat','ca','ca'])",'[True,False]']],phase5:true,companies:['Google-style','Foundations'],solution:'def trie_operations(ops,vals):\n    root={}; out=[]\n    for op,w in zip(ops,vals):\n        if op=="insert":\n            node=root\n            for ch in w:node=node.setdefault(ch,{})\n            node["#"]=True\n        else:\n            node=root; ok=True\n            for ch in w:\n                if ch not in node:ok=False;break\n                node=node[ch]\n            if op=="search":ok=ok and "#" in node\n            out.append(ok)\n    return out'},
{id:'word-dictionary',title:'Design Add and Search Words',diff:'Medium',pattern:'Trie + DFS',district:'hash',fn:'word_dictionary',money:370,rp:68,prompt:'Process add/search operations where search may contain . matching any single letter; return search results.',starter:'def word_dictionary(operations, values):\n    pass',hint:'Trie search becomes DFS when you encounter a wildcard.',lesson:'A trie narrows branching to only prefixes that can still match.',complexity:'O(word length) normal search; wildcard may branch',public:[["(['add','add','add','search','search','search','search'],['bad','dad','mad','pad','bad','.ad','b..'])",'[False,True,True,True]']],hidden:[["(['add','search','search'],['a','.','..'])",'[True,False]']],phase5:true,companies:['Meta-style'],solution:'def word_dictionary(ops,vals):\n    root={}; out=[]\n    def search(w):\n        def dfs(i,node):\n            if i==len(w):return "#" in node\n            ch=w[i]\n            if ch==".":return any(k!="#" and dfs(i+1,v) for k,v in node.items())\n            return ch in node and dfs(i+1,node[ch])\n        return dfs(0,root)\n    for op,w in zip(ops,vals):\n        if op=="add":\n            node=root\n            for ch in w:node=node.setdefault(ch,{})\n            node["#"]=True\n        else:out.append(search(w))\n    return out'},
{id:'subsets',title:'Subsets',diff:'Medium',pattern:'Backtracking',district:'graphs',fn:'subsets',normalize:'groups',money:310,rp:56,prompt:'Return all subsets of a list of unique integers.',starter:'def subsets(nums):\n    pass',hint:'At each index choose whether to include the value, or iteratively extend existing subsets.',lesson:'Backtracking systematically enumerates a decision tree.',complexity:'O(n·2^n) time',public:[["([1,2,3],)",'[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]']],hidden:[["([],)",'[[]]']],phase5:true,companies:['Meta-style','Foundations'],solution:'def subsets(nums):\n    out=[[]]\n    for n in nums:out += [x+[n] for x in out]\n    return out'},
{id:'combination-sum',title:'Combination Sum',diff:'Medium',pattern:'Backtracking',district:'dp',fn:'combination_sum',normalize:'groups',money:340,rp:62,prompt:'Return combinations of candidates that sum to target; each candidate may be reused.',starter:'def combination_sum(candidates, target):\n    pass',hint:'DFS with an index: either reuse the current candidate or move to the next.',lesson:'Backtracking needs a state definition that avoids duplicate search paths.',complexity:'Exponential in target/candidates',public:[["([2,3,6,7],7)",'[[2,2,3],[7]]'],["([2,3,5],8)",'[[2,2,2,2],[2,3,3],[3,5]]']],hidden:[["([2],1)",'[]']],phase5:true,companies:['Amazon-style'],solution:'def combination_sum(candidates,target):\n    out=[]\n    def dfs(i,total,path):\n        if total==target:out.append(path[:]);return\n        if i==len(candidates) or total>target:return\n        path.append(candidates[i]);dfs(i,total+candidates[i],path);path.pop()\n        dfs(i+1,total,path)\n    dfs(0,0,[])\n    return out'},
{id:'median-stream',title:'Find Median from Data Stream',diff:'Hard',pattern:'Two Heaps',district:'structures',fn:'median_stream',money:520,rp:100,prompt:'Given a stream of numbers, return the median after each insertion.',starter:'def median_stream(nums):\n    pass',hint:'Maintain a max-heap for the lower half and min-heap for the upper half, balanced within one element.',lesson:'Two heaps maintain a dynamic partition around the median.',complexity:'O(n log n) total time',public:[["([1,2,3],)",'[1.0,1.5,2.0]'],["([5,2,10,4],)",'[5.0,3.5,5.0,4.5]']],hidden:[["([1],)",'[1.0]']],phase5:true,companies:['Google-style'],solution:'def median_stream(nums):\n    import heapq\n    lo=[];hi=[];out=[]\n    for x in nums:\n        heapq.heappush(lo,-x)\n        heapq.heappush(hi,-heapq.heappop(lo))\n        if len(hi)>len(lo):heapq.heappush(lo,-heapq.heappop(hi))\n        out.append(float(-lo[0]) if len(lo)>len(hi) else (-lo[0]+hi[0])/2)\n    return out'}
];
PHASE5_CHALLENGES.forEach(c=>{if(!CHALLENGES.some(x=>x.id===c.id))CHALLENGES.push(c)});

state.mock=Object.assign({active:null,history:[],selectedLength:3},state.mock||{});

function mockEligibleProblems(){return CHALLENGES.filter(c=>unlocked(c)&&c.diff!=='Hard').sort((a,b)=>adaptiveScore(b)-adaptiveScore(a));}
function buildMockSet(count=3){const pool=mockEligibleProblems(),picked=[],districts=new Set();for(const c of pool){if(picked.length>=count)break;if(!districts.has(c.district)||picked.length>=Math.ceil(count/2)){picked.push(c);districts.add(c.district)}}for(const c of pool){if(picked.length>=count)break;if(!picked.includes(c))picked.push(c)}return picked.slice(0,count)}
function startMockInterview(count=3,minutes=45){const problems=buildMockSet(count);state.mock.active={id:'mock-'+Date.now(),startedAt:Date.now(),endsAt:Date.now()+minutes*60000,minutes,problemIds:problems.map(c=>c.id),attempts:{},passed:{},runtime:{},hintsAtStart:state.hints||0,finished:false};state.current=problems[0]?.id||state.current;persist();switchTab('challenge')}
function currentMock(){return state.mock.active&&!state.mock.active.finished?state.mock.active:null}
function mockRemaining(){const m=currentMock();return m?Math.max(0,m.endsAt-Date.now()):0}
function formatClock(ms){const s=Math.ceil(ms/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function finishMockInterview(reason='completed'){const m=currentMock();if(!m)return;const solved=m.problemIds.filter(id=>m.passed[id]).length;const total=m.problemIds.length;const accuracy=total?solved/total:0;const used=Math.min(m.minutes*60000,Date.now()-m.startedAt);const pace=Math.max(0,1-used/(m.minutes*60000));const hints=Math.max(0,(state.hints||0)-m.hintsAtStart);const score=Math.round(100*(accuracy*.75+pace*.15+Math.max(0,1-hints/Math.max(1,total))*.10));const record={id:m.id,at:new Date().toISOString(),minutes:m.minutes,problemIds:m.problemIds,solved,total,accuracy:Math.round(accuracy*100),score,hints,usedMs:used,reason};state.mock.history.unshift(record);state.mock.history=state.mock.history.slice(0,30);state.mock.active=null;state.money+=score*3;state.research+=Math.round(score/2);persist();switchTab('mock')}
function openMockProblem(id){if(!currentMock())return;selectChallenge(id);switchTab('challenge')}

const phase5RecordHistory=recordHistory;
recordHistory=function(c,passed,ms,stage){phase5RecordHistory(c,passed,ms,stage);const m=currentMock();if(!m||!m.problemIds.includes(c.id))return;m.attempts[c.id]=(m.attempts[c.id]||0)+1;if(passed){m.passed[c.id]=true;m.runtime[c.id]=ms}persist(false)};

function renderMock(){const root=$('#mockTab');if(!root)return;const m=currentMock();if(m){const done=m.problemIds.filter(id=>m.passed[id]).length;root.innerHTML=`<div class="mock-header"><div><h3>🎙️ Live Mock Interview</h3><div class="muted">${done}/${m.problemIds.length} solved · ${m.minutes} minute block</div></div><div class="mock-clock" id="mockClock">${formatClock(mockRemaining())}</div></div><div class="mock-problems">${m.problemIds.map((id,i)=>{const c=CHALLENGES.find(x=>x.id===id),pass=m.passed[id];return `<button class="btn mock-problem ${pass?'mock-pass':''}" onclick="openMockProblem('${id}')">${pass?'✅':'${i+1}.'} ${esc(c.title)} <span>${esc(c.pattern)}</span></button>`}).join('')}</div><div class="actions"><button class="btn primary" onclick="finishMockInterview('ended')">End & score interview</button></div>`;return}const history=state.mock.history||[];root.innerHTML=`<h3>🎙️ Mock Interview Center</h3><p class="muted">Mocks select multiple adaptive problems across different patterns. Only real hidden-test passes count.</p><div class="mock-launch"><button class="btn primary" onclick="startMockInterview(2,30)">30 min · 2 problems</button><button class="btn primary" onclick="startMockInterview(3,45)">45 min · 3 problems</button><button class="btn primary" onclick="startMockInterview(4,60)">60 min · 4 problems</button></div><h3>Interview history</h3><div class="history">${history.slice(0,10).map(x=>`<div class="history-item"><b>${x.score}/100</b> · ${x.solved}/${x.total} solved · ${x.accuracy}% accuracy · ${x.hints} hints <span class="muted">${new Date(x.at).toLocaleDateString()}</span></div>`).join('')||'<div class="muted">Complete a mock interview to create your first scorecard.</div>'}</div>`}

function mockAnalytics(){const h=state.mock.history||[];if(!h.length)return{avg:0,best:0,count:0};return{avg:Math.round(h.reduce((s,x)=>s+x.score,0)/h.length),best:Math.max(...h.map(x=>x.score)),count:h.length}}
const phase5RenderStats=renderStats;
renderStats=function(){phase5RenderStats();const root=$('#statsTab');if(!root)return;const a=mockAnalytics(),trees=CHALLENGES.filter(c=>['Tree DFS','Tree BFS','BST Invariants','BST Inorder'].includes(c.pattern)),lists=CHALLENGES.filter(c=>c.pattern.includes('Linked List')||c.pattern.includes('Pointers'));root.insertAdjacentHTML('beforeend',`<h3>Interview performance</h3><div class="metric-grid"><div class="metric"><b>${a.avg}</b><div class="muted">average mock score</div></div><div class="metric"><b>${a.best}</b><div class="muted">best mock score</div></div><div class="metric"><b>${a.count}</b><div class="muted">mock interviews</div></div><div class="metric"><b>${trees.filter(c=>state.solved.includes(c.id)).length}/${trees.length}</b><div class="muted">tree/BST coverage</div></div></div>`)};

const phase5Render=render;
render=function(){phase5Render();renderMock();const phase=$('#phaseLabel');if(phase)phase.textContent='Phase 5 · Interview Realism'};

setInterval(()=>{const m=currentMock();if(!m)return;const left=mockRemaining(),el=$('#mockClock');if(el)el.textContent=formatClock(left);if(left<=0)finishMockInterview('timeout')},1000);
render();
