(function(C){
  'use strict';
  const DEFAULT_BUILDERS=1,BOOST_PER_SOLVE_MS=5000;
  function install(){
    const World=C.get?.('WorldSystem');if(!World||World.prototype.__p1gConstructionInstalled)return false;
    const p=World.prototype;p.__p1gConstructionInstalled=true;
    const previousPlace=p.placeBuilding,previousUnplace=p.unplaceBuilding,previousProgress=p.constructionProgress,previousNormalize=p.normalize;
    p.ensureConstructionState=function(){const w=this.world,c=w.construction||(w.construction={builders:DEFAULT_BUILDERS,queue:[],boostBankMs:0});c.builders=Math.max(1,Math.min(3,Number(c.builders)||DEFAULT_BUILDERS));c.boostBankMs=Math.max(0,Number(c.boostBankMs)||0);if(!Array.isArray(c.queue))c.queue=[];return c};
    p.constructionDurationFor=function(id){const def=C.BuildingRegistry?.definition?.(this,id)||this.buildingDef(id)||{},fp=def.footprint||{w:1,h:1},area=Math.max(1,(fp.w||1)*(fp.h||1)),cost=Math.max(0,Number(def.cost)||0);return Math.round(Math.min(45000,10000+area*5000+Math.min(12000,cost*8)))};
    p.constructionJobAt=function(x,y){const a=this.anchorFor?.(x,y)||{x,y},key=`${a.x},${a.y}`;return this.ensureConstructionState().queue.find(j=>j.key===key)||null};
    p.constructionSummary=function(now=Date.now()){this.updateConstruction(now);const c=this.ensureConstructionState(),active=c.queue.filter(j=>j.status==='active'),queued=c.queue.filter(j=>j.status==='queued');return{builders:c.builders,active,queued,total:c.queue.length,boostBankMs:c.boostBankMs}};
    p.startQueuedJobs=function(now=Date.now()){const c=this.ensureConstructionState();let active=c.queue.filter(j=>j.status==='active').length;for(const j of c.queue){if(active>=c.builders)break;if(j.status!=='queued')continue;j.status='active';j.startedAt=now;active++;const t=this.tile(j.x,j.y);if(t){t.constructionStatus='active';t.constructionStartedAt=now}C.events.emit('world:construction-started',{...j})}};
    p.updateConstruction=function(now=Date.now()){const c=this.ensureConstructionState();this.startQueuedJobs(now);let changed=false;for(const j of [...c.queue]){if(j.status!=='active')continue;const elapsed=Math.max(0,now-(Number(j.startedAt)||now))+(Number(j.boostMs)||0);if(elapsed<j.durationMs)continue;const t=this.tile(j.x,j.y);if(t?.buildingId===j.id){t.constructionMs=0;t.constructionStatus='complete';delete t.constructionStartedAt}c.queue.splice(c.queue.indexOf(j),1);changed=true;C.events.emit('world:construction-complete',{id:j.id,x:j.x,y:j.y,durationMs:j.durationMs})}if(changed)this.startQueuedJobs(now);return changed};
    p.constructionProgress=function(tile,now=Date.now()){if(!tile?.buildingId)return 1;this.updateConstruction(now);let job=null;for(const j of this.ensureConstructionState().queue){if(this.tile(j.x,j.y)===tile){job=j;break}}if(!job)return previousProgress?.call(this,tile,now)??1;if(job.status==='queued')return 0;const elapsed=Math.max(0,now-(Number(job.startedAt)||now))+(Number(job.boostMs)||0);return Math.max(0,Math.min(1,elapsed/job.durationMs))};
    p.placeBuilding=function(id,x,y,opts={}){if(opts.construction===false)return previousPlace.call(this,id,x,y,opts);const result=previousPlace.call(this,id,x,y,{...opts,construction:false});if(!result.ok)return result;const c=this.ensureConstructionState(),durationMs=this.constructionDurationFor(id),key=`${x},${y}`,job={key,id,x,y,durationMs,enqueuedAt:Date.now(),startedAt:null,status:'queued',boostMs:0};c.queue.push(job);const t=this.tile(x,y);if(t){t.constructionMs=durationMs;t.constructionStatus='queued';t.placedAt=job.enqueuedAt}this.startQueuedJobs(job.enqueuedAt);C.events.emit('world:construction-queued',{...job,position:c.queue.length});return{...result,construction:true,durationMs,queued:true}};
    p.unplaceBuilding=function(x,y){const job=this.constructionJobAt(x,y);if(job)return{ok:false,reason:'Finish or cancel construction before moving this building'};return previousUnplace.call(this,x,y)};
    p.grantConstructionBoost=function(ms=BOOST_PER_SOLVE_MS,source='coding'){const c=this.ensureConstructionState(),amount=Math.max(0,Math.round(Number(ms)||0));c.boostBankMs+=amount;C.events.emit('world:construction-boost-earned',{ms:amount,source,total:c.boostBankMs});return c.boostBankMs};
    p.applyConstructionBoost=function(ms=BOOST_PER_SOLVE_MS,x=null,y=null){const c=this.ensureConstructionState();this.updateConstruction();const job=(Number.isInteger(x)&&Number.isInteger(y))?this.constructionJobAt(x,y):c.queue.find(j=>j.status==='active')||c.queue[0];if(!job)return{ok:false,reason:'No construction job'};const amount=Math.min(c.boostBankMs,Math.max(0,Math.round(Number(ms)||0)));if(!amount)return{ok:false,reason:'Solve coding challenges to earn build boosts'};c.boostBankMs-=amount;job.boostMs=(Number(job.boostMs)||0)+amount;C.events.emit('world:construction-boost-applied',{id:job.id,x:job.x,y:job.y,ms:amount,remaining:c.boostBankMs});this.updateConstruction();return{ok:true,ms:amount,job,remaining:c.boostBankMs}};
    p.cancelConstruction=function(x,y){const job=this.constructionJobAt(x,y);if(!job)return{ok:false,reason:'Building is not under construction'};const c=this.ensureConstructionState();c.queue=c.queue.filter(j=>j!==job);const r=previousUnplace.call(this,job.x,job.y);this.startQueuedJobs();C.events.emit('world:construction-cancelled',{...job});return{ok:!!r.ok,id:job.id}};
    p.normalize=function(world){previousNormalize.call(this,world);const c=world.construction||(world.construction={builders:DEFAULT_BUILDERS,queue:[],boostBankMs:0});c.builders=Math.max(1,Math.min(3,Number(c.builders)||DEFAULT_BUILDERS));c.boostBankMs=Math.max(0,Number(c.boostBankMs)||0);c.queue=(Array.isArray(c.queue)?c.queue:[]).filter(j=>j&&Number.isInteger(j.x)&&Number.isInteger(j.y)&&this.coordsInside(world,j.x,j.y)&&world.tiles?.[`${j.x},${j.y}`]?.buildingId===j.id).map(j=>({...j,key:`${j.x},${j.y}`,durationMs:Math.max(1000,Number(j.durationMs)||15000),enqueuedAt:Number(j.enqueuedAt)||Date.now(),startedAt:j.status==='active'?(Number(j.startedAt)||Date.now()):null,status:j.status==='active'?'active':'queued',boostMs:Math.max(0,Number(j.boostMs)||0)}))};
    if(C.events?.on){for(const evt of ['challenge:solved','problem:solved','coding:solved'])C.events.on(evt,()=>{const world=C.game?.world;if(world?.grantConstructionBoost)world.grantConstructionBoost(BOOST_PER_SOLVE_MS,evt)})}
    return true;
  }
  C.register('ConstructionSystem',{install,BOOST_PER_SOLVE_MS});
})(window.Codeopolis);
