(function(C){
  'use strict';
  const VERSION=1;
  const ZONES=Object.freeze({residential:Object.freeze({id:'residential',name:'Residential',icon:'🏠',color:0x65c98b,description:'Homes, neighborhoods, and population capacity.'}),learning:Object.freeze({id:'learning',name:'Learning',icon:'📚',color:0x60a5fa,description:'Interview practice, teaching, and skill-building venues.'}),research:Object.freeze({id:'research',name:'Research',icon:'🔬',color:0xb58cff,description:'Deep technical research and algorithm development.'}),compute:Object.freeze({id:'compute',name:'Compute',icon:'⚡',color:0xf4b860,description:'Power, systems, infrastructure, and compute capacity.'}),civic:Object.freeze({id:'civic',name:'Civic',icon:'🌳',color:0x59c3c3,description:'Parks, recovery, community, and civic services.'}),mixed:Object.freeze({id:'mixed',name:'Mixed',icon:'🏙️',color:0xf08fb5,description:'Flexible innovation corridors that accept every building type.'})});
  const COMPLEMENTS=Object.freeze({residential:['civic','learning'],learning:['residential','research','civic'],research:['learning','compute'],compute:['research'],civic:['residential','learning'],mixed:['residential','learning','research','compute','civic']});
  const BY_ID=Object.freeze({house:'residential',park:'civic',camp:'civic',academy:'learning',market:'learning',foundry:'learning',observatory:'learning',lab:'research',solar:'compute',transit:'compute'});
  function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function key(x,y){return `${x},${y}`}
  function ensure(state){const z=state.cityZoning||(state.cityZoning={version:VERSION,tiles:{},activeZone:'residential',overlay:true,history:[]});z.version=VERSION;z.tiles=z.tiles&&typeof z.tiles==='object'?z.tiles:{};z.activeZone=ZONES[z.activeZone]?z.activeZone:'residential';z.overlay=z.overlay!==false;z.history=Array.isArray(z.history)?z.history.slice(-49):[];return z}
  function normalizeZone(zone){return ZONES[zone]?zone:null}
  function zoneAt(state,x,y){return ensure(state).tiles[key(x,y)]||null}
  function zoneTiles(state){const z=ensure(state);return Object.entries(z.tiles).map(([k,zone])=>{const [x,y]=k.split(',').map(Number);return{x,y,zone,def:ZONES[zone]}}).filter(v=>Number.isInteger(v.x)&&Number.isInteger(v.y)&&v.def)}
  function canZone(state,world,x,y,zone){if(zone!==null&&!normalizeZone(zone))return{ok:false,reason:'Unknown zone type.'};if(!world?.inside?.(x,y))return{ok:false,reason:'Outside the city boundary.'};const tile=world.tile?.(x,y);if(tile?.road)return{ok:false,reason:'Road tiles cannot be zoned.'};const terrain=C.phaserCity?.adapter?.terrainAt?.(x,y);if(terrain==='water')return{ok:false,reason:'Water tiles cannot be zoned.'};return{ok:true}}
  function setZone(state,world,x,y,zone,source='player'){const z=ensure(state),next=normalizeZone(zone),verdict=canZone(state,world,x,y,next);if(!verdict.ok)return verdict;const k=key(x,y),before=z.tiles[k]||null;if(before===next)return{ok:true,changed:false,x,y,zone:next,before};if(next)z.tiles[k]=next;else delete z.tiles[k];const row={x,y,before,zone:next,source,at:Date.now()};z.history.push(row);if(z.history.length>50)z.history.shift();C.events?.emit?.('zoning:changed',row);C.events?.emit?.('zoning:demand-changed',demand(state,world));return{ok:true,changed:true,...row}}
  function clearZone(state,world,x,y,source='player'){return setZone(state,world,x,y,null,source)}
  function setActiveZone(state,zone){const z=ensure(state);if(zone==='erase'){z.activeZone='erase';return z.activeZone}if(!ZONES[zone])return z.activeZone;z.activeZone=zone;C.events?.emit?.('zoning:mode',{zone});return zone}
  function preferredZone(defOrId={}){const id=typeof defOrId==='string'?defOrId:String(defOrId.id||''),def=typeof defOrId==='string'?{}:defOrId;if(BY_ID[id])return BY_ID[id];const district=String(def.district||'').toLowerCase(),name=String(def.name||id).toLowerCase();if(/house|housing|residen|apartment|habitat|home/.test(name))return'residential';if(/park|garden|recovery|civic|community|plaza/.test(name))return'civic';if(/power|energy|solar|grid|compute|server|network|transit|infrastructure|systems|reliability/.test(`${name} ${district}`))return'compute';if(/research|laboratory|institute|algorithm|dynamic|dp/.test(`${name} ${district}`))return'research';if(/academy|school|learn|interview|market|foundry|observatory|array|hash|search|graph/.test(`${name} ${district}`))return'learning';return'mixed'}
  function definition(world,x,y){const a=world?.anchorFor?.(x,y)||{x,y},tile=world?.tile?.(a.x,a.y);if(!tile?.buildingId)return null;const def=C.BuildingRegistry?.definition?.(world,tile.buildingId)||world?.buildingDef?.(tile.buildingId)||{id:tile.buildingId,name:tile.buildingId,footprint:tile.footprint||{w:1,h:1}};return{anchor:a,tile,id:tile.buildingId,def,footprint:tile.footprint||def.footprint||{w:1,h:1}}}
  function footprintCells(world,x,y,def=null){const b=def?{anchor:{x,y},footprint:def.footprint||{w:1,h:1}}:definition(world,x,y);if(!b)return[];const fp=b.footprint||{w:1,h:1},out=[];for(let dy=0;dy<(fp.h||1);dy++)for(let dx=0;dx<(fp.w||1);dx++)out.push({x:b.anchor.x+dx,y:b.anchor.y+dy});return out}
  function composition(state,cells){const counts={},zoned=cells.map(c=>zoneAt(state,c.x,c.y)).filter(Boolean);for(const zone of zoned)counts[zone]=(counts[zone]||0)+1;const ranked=Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])),zone=ranked[0]?.[0]||null,top=ranked[0]?.[1]||0;return{zone,counts,zoned:zoned.length,total:cells.length,coverage:cells.length?zoned.length/cells.length:0,consistency:zoned.length?top/zoned.length:0}}
  function neighbors(world,x,y){return[[x,y-1],[x+1,y],[x,y+1],[x-1,y]].filter(([nx,ny])=>world?.inside?.(nx,ny)).map(([nx,ny])=>({x:nx,y:ny}))}
  function clusterFor(state,world,x,y,zoneOverride=null){const zone=zoneOverride||zoneAt(state,x,y);if(!zone)return null;const seen=new Set,queue=[{x,y}],cells=[];while(queue.length){const p=queue.shift(),k=key(p.x,p.y);if(seen.has(k)||zoneAt(state,p.x,p.y)!==zone)continue;seen.add(k);cells.push(p);for(const n of neighbors(world,p.x,p.y))if(!seen.has(key(n.x,n.y))&&zoneAt(state,n.x,n.y)===zone)queue.push(n)}return{zone,size:cells.length,cells,keys:seen,maturity:cells.length>=8?'district':cells.length>=4?'quarter':cells.length>=2?'block':'parcel'}}
  function allClusters(state,world){const seen=new Set,out=[];for(const t of zoneTiles(state)){const k=key(t.x,t.y);if(seen.has(k)||!world?.inside?.(t.x,t.y))continue;const c=clusterFor(state,world,t.x,t.y,t.zone);if(!c)continue;for(const ck of c.keys)seen.add(ck);out.push(c)}return out.sort((a,b)=>b.size-a.size||a.zone.localeCompare(b.zone))}
  function adjacentZones(state,world,cells){const own=new Set(cells.map(c=>key(c.x,c.y))),counts={};for(const cell of cells)for(const n of neighbors(world,cell.x,cell.y)){if(own.has(key(n.x,n.y)))continue;const zone=zoneAt(state,n.x,n.y);if(zone)counts[zone]=(counts[zone]||0)+1}return counts}
  function specializationFor(zone,cluster,state,world){if(!zone||!cluster||cluster.size<4)return null;const keys=cluster.keys||new Set(cluster.cells.map(c=>key(c.x,c.y))),types={};for(const b of world?.placedBuildings?.()||[]){const cells=footprintCells(world,b.x,b.y);if(!cells.some(c=>keys.has(key(c.x,c.y))))continue;const p=preferredZone(b.def||world?.buildingDef?.(b.id)||b.id);types[p]=(types[p]||0)+1}let name;if(zone==='residential')name=types.civic?'Garden Learning Neighborhood':'Residential Quarter';else if(zone==='learning')name=types.research?'Learning & Research Campus':'Interview Campus';else if(zone==='research')name=types.compute?'AI Research Park':'Algorithm Research Park';else if(zone==='compute')name=types.research?'Research Compute Grid':'Systems & Compute Grid';else if(zone==='civic')name='Civic Commons';else name='Innovation Corridor';return{name,zone,size:cluster.size,tier:cluster.size>=8?3:cluster.size>=6?2:1,buildingMix:types}}
  function buildingStatus(state,world,x,y){const b=definition(world,x,y);if(!state||!b)return null;const cells=footprintCells(world,b.anchor.x,b.anchor.y,b.def),mix=composition(state,cells),preferred=preferredZone({...b.def,id:b.id});let zone=mix.zone,anchorCell=cells.find(c=>zoneAt(state,c.x,c.y)===zone)||cells[0],cluster=zone&&anchorCell?clusterFor(state,world,anchorCell.x,anchorCell.y,zone):null,adj=adjacentZones(state,world,cells),complements=COMPLEMENTS[preferred]||[],complementEdges=complements.reduce((n,z)=>n+(adj[z]||0),0),fit=!zone?'unzoned':zone===preferred||zone==='mixed'?'match':'mismatch',clusterBonus=fit==='match'&&cluster?Math.min(.12,Math.max(0,cluster.size-1)*.02):0,adjacencyBonus=fit==='match'?Math.min(.08,complementEdges*.015):0,base=fit==='match'?(zone==='mixed'?1.03:1.05):fit==='mismatch'?.86:1,efficiency=clamp(base+clusterBonus+adjacencyBonus,.8,1.25),specialization=specializationFor(zone,cluster,state,world);return{version:VERSION,x:b.anchor.x,y:b.anchor.y,id:b.id,name:b.def.name||b.id,zone,preferredZone:preferred,fit,coverage:Number(mix.coverage.toFixed(2)),consistency:Number(mix.consistency.toFixed(2)),efficiency:Number(efficiency.toFixed(3)),cluster:cluster?{zone:cluster.zone,size:cluster.size,maturity:cluster.maturity}:null,adjacentZones:adj,complementEdges,specialization}}
  function placementStatus(state,world,id,x,y){const def=C.BuildingRegistry?.definition?.(world,id)||world?.buildingDef?.(id)||{id,name:id,footprint:{w:1,h:1}},cells=footprintCells(world,x,y,def),mix=composition(state,cells),preferred=preferredZone(def),fit=!mix.zone?'unzoned':mix.zone===preferred||mix.zone==='mixed'?'match':'mismatch';return{id,preferredZone:preferred,zone:mix.zone,fit,coverage:Number(mix.coverage.toFixed(2)),label:fit==='match'?`${ZONES[mix.zone]?.icon||'🏙️'} ${ZONES[mix.zone]?.name||mix.zone} fit`:fit==='mismatch'?`⚠️ Prefers ${ZONES[preferred]?.name||preferred}`:`Unzoned · prefers ${ZONES[preferred]?.name||preferred}`}}
  function summary(state,world){const tiles=zoneTiles(state).filter(t=>world?.inside?.(t.x,t.y)),counts={};for(const id of Object.keys(ZONES))counts[id]=0;for(const t of tiles)counts[t.zone]++;const clusters=allClusters(state,world),specializations=clusters.map(c=>specializationFor(c.zone,c,state,world)).filter(Boolean),buildings=(world?.placedBuildings?.()||[]).map(b=>buildingStatus(state,world,b.x,b.y)).filter(Boolean),matched=buildings.filter(b=>b.fit==='match').length,mismatched=buildings.filter(b=>b.fit==='mismatch').length;return{version:VERSION,zonedTiles:tiles.length,counts,clusters:clusters.map(c=>({zone:c.zone,size:c.size,maturity:c.maturity,cells:c.cells})),largestCluster:clusters[0]?{zone:clusters[0].zone,size:clusters[0].size,maturity:clusters[0].maturity}:null,specializations,buildings:buildings.length,matched,mismatched,unzoned:Math.max(0,buildings.length-matched-mismatched)}}
  function demand(state,world){const sum=summary(state,world),pop=C.PopulationSimulation?.summary?.(state,world)||null,nav=C.LearningCityLoop?.navigator?.(state,world)||null,unmatched=(world?.placedBuildings?.()||[]).reduce((acc,b)=>{const p=preferredZone(b.def||world?.buildingDef?.(b.id)||b.id),s=buildingStatus(state,world,b.x,b.y);if(!s?.zone)acc[p]=(acc[p]||0)+1;return acc},{}),housing=pop?.demand?.housing==='high'?88:pop?.demand?.housing==='low'?28:58,jobs=pop?.demand?.jobs==='high'?74:pop?.demand?.jobs==='low'?38:56,happiness=Number(pop?.happiness??state.happiness??65),power=Number(pop?.powerCoverage??1),base={residential:housing,learning:nav?.target?78:54,research:Math.max(42,jobs-5),compute:power<.8?90:power<.95?68:48,civic:clamp(105-happiness,28,82),mixed:42};const scores={};for(const id of Object.keys(ZONES)){const supply=Number(sum.counts[id])||0,need=Number(unmatched[id])||0;scores[id]=Math.round(clamp(base[id]+need*8-Math.min(24,supply*2),10,95))}const ranked=Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([zone,score])=>({zone,score,name:ZONES[zone].name,icon:ZONES[zone].icon}));return{version:VERSION,scores,ranked,top:ranked[0]||null,population:pop?{housing:pop.demand.housing,jobs:pop.demand.jobs,happiness:pop.happiness,powerCoverage:pop.powerCoverage}:null}}
  function applyEffectMultiplier(fx,status){if(!fx||!status)return fx;const m=status.efficiency;return{...fx,zoning:status,zoningMultiplier:m,population:Math.round((Number(fx.population)||0)*m),energy:Math.round((Number(fx.energy)||0)*m),happiness:Math.round((Number(fx.happiness)||0)*m),moneyRate:Number(((Number(fx.moneyRate)||0)*m).toFixed(1)),researchRate:Number(((Number(fx.researchRate)||0)*m).toFixed(1))}}
  function install(state,world){if(!state||!world)return false;ensure(state);const proto=world.constructor?.prototype||Object.getPrototypeOf(world);if(proto&&!proto.__r8DistrictZoningInstalled){proto.__r8DistrictZoningInstalled=true;const previousEffects=proto.buildingEffects,previousProfile=proto.serviceProfile;proto.zoneAt=function(x,y){return zoneAt(C.game?.state||this.state||state,x,y)};proto.buildingZoningStatus=function(x,y){return buildingStatus(C.game?.state||this.state||state,this,x,y)};proto.cityZoningSummary=function(){return summary(C.game?.state||this.state||state,this)};proto.cityZoningDemand=function(){return demand(C.game?.state||this.state||state,this)};proto.setZone=function(x,y,zone,source='player'){return setZone(C.game?.state||this.state||state,this,x,y,zone,source)};if(typeof previousEffects==='function')proto.buildingEffects=function(x,y){return applyEffectMultiplier(previousEffects.call(this,x,y),buildingStatus(C.game?.state||this.state||state,this,x,y))};if(typeof previousProfile==='function')proto.serviceProfile=function(x,y){const p=previousProfile.call(this,x,y);if(!p)return p;const s=buildingStatus(C.game?.state||this.state||state,this,x,y);if(!s)return p;const m=s.efficiency;return{...p,zoning:s,zoningMultiplier:m,powerSupply:Math.round((Number(p.powerSupply)||0)*m),powerDemand:Math.max(0,Math.round((Number(p.powerDemand)||0)/Math.max(.8,m))),workerDemand:Math.round((Number(p.workerDemand)||0)*m),housingCapacity:Math.round((Number(p.housingCapacity)||0)*m)}}}
    if(!install._events){install._events=true;for(const evt of['world:building-placed','world:building-unplaced','world:building-upgraded','world:road-changed','population:updated'])C.events?.on?.(evt,()=>{const s=C.game?.state||state,w=C.game?.world||world;if(s&&w)C.events?.emit?.('zoning:demand-changed',demand(s,w))});C.events?.on?.('zoning:changed',()=>C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')?.refresh?.())}
    C.events?.emit?.('zoning:ready',{summary:summary(state,world),demand:demand(state,world)});return true}
  function audit(state,world){const s=summary(state,world),d=demand(state,world);return{version:VERSION,ready:true,summary:s,demand:d,learningProgressDestructive:false}}
  C.DistrictZoning={VERSION,ZONES,COMPLEMENTS,BY_ID,ensure,normalizeZone,zoneAt,zoneTiles,canZone,setZone,clearZone,setActiveZone,preferredZone,definition,footprintCells,composition,neighbors,clusterFor,allClusters,adjacentZones,specializationFor,buildingStatus,placementStatus,summary,demand,applyEffectMultiplier,install,audit};
})(window.Codeopolis);
