(function(C){
  'use strict';
  const VERSION=1,UI_URL='src/progression/technology-tree-ui.js';
  const TECHS=Object.freeze([
    {id:'foundational_engineering',name:'Foundational Engineering',icon:'🪵',age:1,branch:'foundations',resource:'materials',cost:18,mastery:{level:2,count:1},requires:[],effect:'Unlocks engineered foundation structures.'},
    {id:'indexed_data',name:'Indexed Data',icon:'💱',age:2,branch:'data',resource:'trade',cost:24,mastery:{level:2,count:2},requires:['foundational_engineering'],effect:'Unlocks advanced data-structure buildings.'},
    {id:'tree_structures',name:'Tree Structures',icon:'🌳',age:2,branch:'graphs',resource:'research',cost:28,mastery:{level:2,count:2},requires:['indexed_data'],effect:'Opens the graph/search research branch.'},
    {id:'graph_traversal',name:'Graph Traversal',icon:'🕸️',age:3,branch:'graphs',resource:'research',cost:38,mastery:{level:3,count:2},requires:['tree_structures'],effect:'Unlocks Graph district advanced buildings.'},
    {id:'algorithmic_optimization',name:'Algorithmic Optimization',icon:'⚙️',age:3,branch:'compute',resource:'compute',cost:42,mastery:{level:3,count:2},requires:['indexed_data'],effect:'Opens the optimization branch.'},
    {id:'dynamic_systems',name:'Dynamic Systems',icon:'🧠',age:3,branch:'compute',resource:'compute',cost:52,mastery:{level:3,count:3},requires:['algorithmic_optimization'],effect:'Unlocks advanced optimization buildings.'},
    {id:'systems_architecture',name:'Systems Architecture',icon:'🏗️',age:4,branch:'systems',resource:'infrastructure',cost:55,mastery:{level:3,count:4},requires:['graph_traversal','algorithmic_optimization'],effect:'Opens systems infrastructure research.'},
    {id:'distributed_systems',name:'Distributed Systems',icon:'🌐',age:4,branch:'systems',resource:'infrastructure',cost:68,mastery:{level:4,count:1},requires:['systems_architecture'],effect:'Unlocks advanced Systems district buildings.'},
    {id:'reliability_engineering',name:'Reliability Engineering',icon:'🛡️',age:4,branch:'reliability',resource:'stability',cost:58,mastery:{level:3,count:4},requires:['systems_architecture'],effect:'Opens production reliability research.'},
    {id:'resilience_engineering',name:'Resilience Engineering',icon:'🏥',age:5,branch:'reliability',resource:'stability',cost:72,mastery:{level:4,count:3},requires:['reliability_engineering','distributed_systems'],effect:'Unlocks advanced Reliability district buildings.'},
    {id:'frontier_computation',name:'Frontier Computation',icon:'🚀',age:5,branch:'frontier',resource:'compute',cost:85,mastery:{level:4,count:4},requires:['dynamic_systems','distributed_systems'],effect:'Unlocks frontier-scale optimization technologies.'},
    {id:'frontier_engineering',name:'Frontier Engineering',icon:'✨',age:6,branch:'frontier',resource:'research',cost:110,mastery:{level:5,count:3},requires:['frontier_computation','resilience_engineering'],effect:'Completes the cross-domain technology tree.'}
  ]);
  const BY_ID=Object.freeze(Object.fromEntries(TECHS.map(t=>[t.id,t])));
  function ensure(state){state.tech=Array.isArray(state.tech)?[...new Set(state.tech)]:[];const x=state.technologyTree||(state.technologyTree={version:VERSION,history:[]});x.version=VERSION;x.history=Array.isArray(x.history)?x.history.slice(-49):[];return x}
  function unlocked(state,id){ensure(state);return state.tech.includes(id)}
  function masteryCount(state,level,branch){const rows=C.ConceptMastery?.all?.(state)||[];return rows.filter(r=>(r.level?.level||0)>=level&&(!branch||branch==='frontier'||String(r.concept?.district||'').toLowerCase().includes(branch)||({graphs:['graphs','research'],compute:['dp','compute'],systems:['systems','infrastructure'],reliability:['reliability','stability'],data:['trade','hash','structures'],foundations:['arrays','materials','strings']}[branch]||[]).includes(String(r.concept?.district||'').toLowerCase()))).length}
  function status(state,tech){const t=typeof tech==='string'?BY_ID[tech]:tech;if(!t)return{locked:true,reason:'Unknown technology'};ensure(state);if(unlocked(state,t.id))return{tech:t,unlocked:true,researchable:false,missing:[]};const missing=[],age=C.AgeProgression?.current?.(state)?.level||Number(state.eraLevel)||1;if(age<t.age)missing.push({type:'age',have:age,need:t.age});for(const id of t.requires)if(!unlocked(state,id))missing.push({type:'tech',id});const haveMastery=masteryCount(state,t.mastery.level,t.branch);if(haveMastery<t.mastery.count)missing.push({type:'mastery',have:haveMastery,need:t.mastery.count,level:t.mastery.level});const bal=C.ConceptResources?.balances?.(state)?.[t.resource]||0;if(bal<t.cost)missing.push({type:'resource',id:t.resource,have:bal,need:t.cost});return{tech:t,unlocked:false,researchable:missing.length===0,missing}}
  function formatMissing(m){if(m.type==='age')return`Age ${m.need}`;if(m.type==='tech')return BY_ID[m.id]?.name||m.id;if(m.type==='mastery')return`${m.need} concepts at mastery ${m.level}+`;if(m.type==='resource'){const d=C.ConceptResources?.RESOURCE_DEFS?.[m.id];return`${d?.icon||'◆'} ${m.need} ${d?.name||m.id}`}return'Requirement'}
  function research(state,id){const s=status(state,id);if(!s.tech)return{ok:false,reason:'Unknown technology'};if(s.unlocked)return{ok:true,already:true,tech:s.tech};if(!s.researchable)return{ok:false,reason:s.missing.map(formatMissing).join(' · '),status:s};const paid=C.ConceptResources?.spend?.(state,{[s.tech.resource]:s.tech.cost},`technology:${id}`);if(paid&&!paid.ok)return{ok:false,reason:'Insufficient resources'};state.tech.push(id);const tree=ensure(state),entry={id,at:Date.now()};tree.history.push(entry);if(tree.history.length>50)tree.history.shift();const result={ok:true,tech:s.tech,entry};C.events?.emit?.('technology:unlocked',result);C.events?.emit?.('progression:changed',{type:'technology',id});return result}
  function requiredTechForBuilding(def={}){const d=String(def.district||'').toLowerCase();if(/reliab|security|test|incident/.test(d))return'resilience_engineering';if(/system|network|infrastructure|concurr/.test(d))return'distributed_systems';if(/\bdp\b|greedy|optimization|compute/.test(d))return'dynamic_systems';if(/graph|tree|search|traversal/.test(d))return'graph_traversal';if(/hash|heap|stack|queue|structure/.test(d))return'indexed_data';return null}
  function snapshot(state){ensure(state);return{version:VERSION,unlocked:[...state.tech],nodes:TECHS.map(t=>status(state,t))}}
  function attachUI(state){const host=C.phaserCity?.host;if(!host||C.phaserCity?.technologies)return false;if(C.TechnologyTreeUI){C.phaserCity.technologies=new C.TechnologyTreeUI(host,state);return true}if(typeof document==='undefined')return false;const old=document.querySelector('[data-p2h-tech-ui="1"]');if(old)return false;const s=document.createElement('script');s.src=UI_URL;s.dataset.p2hTechUi='1';s.onload=()=>attachUI(state);document.head.appendChild(s);return false}
  function install(state){if(!state)return false;ensure(state);if(!install._wrapped){install._wrapped=true;const R=C.BuildingRegistry,orig=R?.status;if(R&&orig&&!orig.__p2hWrapped){R.status=function(world,s,id){const out=orig.call(this,world,s,id),req=requiredTechForBuilding(out.def||{});out.requiredTechnology=req;if(!out.owned&&req&&!unlocked(s,req)){const n=BY_ID[req]?.name||req;out.locked=out.locked||`Research ${n} first`}return out};R.status.__p2hWrapped=true}}if(!install._events){install._events=true;for(const evt of['mastery:updated','age:advanced','learning:resource-earned','learning:resources-spent','technology:unlocked'])C.events?.on?.(evt,()=>C.phaserCity?.technologies?.render?.());C.events?.on?.('civilization:phaser-ready',()=>attachUI(C.game?.state||window.state||state))}attachUI(state);return true}
  C.TechnologyTree={VERSION,TECHS,BY_ID,ensure,unlocked,masteryCount,status,formatMissing,research,requiredTechForBuilding,snapshot,attachUI,install};
})(window.Codeopolis);