(() => {
  const KEY = 'codeopolis_phase22_repo_sim_v1';
  const scenarios = [
    {id:'cache-race',title:'Cache Stampede Guard',company:'Atlas Cloud',file:'services/cache.py',difficulty:'Medium',summary:'A teammate added request coalescing to reduce origin load.',diff:`@@ def get_or_load(key):\n-    return origin.load(key)\n+    if key not in inflight:\n+        inflight[key] = origin.load(key)\n+    value = inflight[key]\n+    del inflight[key]\n+    return value`,issues:[{id:'race',label:'Check-then-act race on inflight',kind:'correctness'},{id:'failure',label:'Failed loads can leave inconsistent state',kind:'reliability'},{id:'cleanup',label:'Cleanup is not protected with finally',kind:'reliability'}],tests:['Concurrent callers for the same key share one load','Origin failure does not poison later calls','Different keys remain independent'],lesson:'Shared-state coordination needs atomic ownership plus cleanup on every exit path.'},
    {id:'auth-filter',title:'Authorization Filter Refactor',company:'Vector Security',file:'api/documents.py',difficulty:'Hard',summary:'A refactor moves authorization into a reusable query helper.',diff:`@@ def list_documents(user):\n-    docs = [d for d in all_docs() if can_read(user, d)]\n+    docs = query_documents(owner_id=user.id)\n     return sorted(docs, key=lambda d: d.updated_at, reverse=True)`,issues:[{id:'semantics',label:'Ownership is not equivalent to can_read authorization',kind:'security'},{id:'sharing',label:'Shared/team documents disappear',kind:'correctness'},{id:'coverage',label:'No test preserves non-owner authorized access',kind:'testing'}],tests:['Owner can read owned document','Team member can read shared document','Unauthorized user cannot read document'],lesson:'Performance refactors must preserve authorization semantics, not approximate them.'},
    {id:'heap-regression',title:'Scheduler Complexity Regression',company:'Nova Robotics',file:'planner/scheduler.py',difficulty:'Medium',summary:'A PR simplifies dispatch ordering for the fleet scheduler.',diff:`@@ def next_jobs(jobs, k):\n-    return heapq.nsmallest(k, jobs, key=lambda j: j.deadline)\n+    jobs.sort(key=lambda j: j.deadline)\n+    return jobs[:k]`,issues:[{id:'complexity',label:'Full sort regresses O(n log k) to O(n log n)',kind:'performance'},{id:'mutation',label:'Function now mutates caller-owned input',kind:'correctness'},{id:'scale',label:'No large-n regression test',kind:'testing'}],tests:['Returns earliest k jobs','Input order is unchanged','Large queue uses bounded selection work'],lesson:'A cleaner-looking implementation can regress both complexity and API behavior.'},
    {id:'batch-memory',title:'Inference Batch Memory Leak',company:'Helix AI',file:'serving/batcher.py',difficulty:'Hard',summary:'Batch telemetry retains request metadata for debugging.',diff:`@@ def complete_batch(batch):\n     result = model(batch.inputs)\n+    completed_batches.append(batch)\n     metrics.observe(len(batch.inputs))\n     return result`,issues:[{id:'retention',label:'Global list retains complete batch/request graphs',kind:'performance'},{id:'privacy',label:'Request metadata may be retained indefinitely',kind:'security'},{id:'bound',label:'No bounded retention or redaction policy',kind:'reliability'}],tests:['Completed batches become collectible','Telemetry stores aggregate data only','Debug retention is bounded and redacted'],lesson:'Observability must have explicit ownership, retention, and privacy boundaries.'},
    {id:'telemetry-retry',title:'Mission Telemetry Retry',company:'Orbital Systems',file:'telemetry/client.py',difficulty:'Hard',summary:'Retries were added after intermittent uplink failures.',diff:`@@ def send(packet):\n-    transport.write(packet)\n+    while True:\n+        try:\n+            transport.write(packet)\n+            return\n+        except IOError:\n+            continue`,issues:[{id:'infinite',label:'Unbounded retry can hang the caller forever',kind:'reliability'},{id:'backoff',label:'Tight loop creates retry storm without backoff',kind:'performance'},{id:'duplicate',label:'No idempotency/ack strategy for ambiguous writes',kind:'correctness'}],tests:['Retry count is bounded','Backoff occurs between attempts','Ambiguous success does not duplicate packet effects'],lesson:'Retries require budgets, backoff, and idempotency semantics.'}
  ];
  const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const state=Object.assign({active:null,selected:[],comments:{},history:[],ci:null},load());
  const current=()=>scenarios.find(x=>x.id===state.active)||null;
  function start(id){state.active=id;state.selected=[];state.comments={};state.ci=null;save(state);render();}
  function toggle(id){const i=state.selected.indexOf(id);i>=0?state.selected.splice(i,1):state.selected.push(id);save(state);render();}
  function setComment(id,v){state.comments[id]=v;save(state);}
  function runCI(){const s=current();if(!s)return;const found=new Set(state.selected);const issueScore=Math.round(70*found.size/s.issues.length);const commentQuality=s.issues.reduce((n,i)=>n+((state.comments[i.id]||'').trim().length>=35?1:0),0);const communication=Math.round(20*commentQuality/s.issues.length);const tests=Math.min(10,found.size*3+((state.comments.tests||'').trim().length>=35?4:0));const score=Math.min(100,issueScore+communication+tests);state.ci={score,passed:score>=75,found:found.size,total:s.issues.length,at:Date.now()};save(state);window.dispatchEvent(new CustomEvent('codeopolis:repo-review-scored',{detail:{scenarioId:s.id,score,passed:score>=75}}));render();}
  function submit(){const s=current();if(!s||!state.ci?.passed)return;state.history.push({scenarioId:s.id,title:s.title,score:state.ci.score,at:Date.now()});state.active=null;state.selected=[];state.comments={};state.ci=null;save(state);window.dispatchEvent(new CustomEvent('codeopolis:repo-review-complete',{detail:{scenarioId:s.id,score:state.history.at(-1).score}}));render();}
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function render(){const root=document.getElementById('repositorySim');if(!root)return;const s=current();if(!s){root.innerHTML=`<div class="p22-hero"><div><h2>🔍 Repository Lab</h2><p>Review realistic Python pull requests. Find correctness, security, reliability, complexity, and testing problems before CI approves the change.</p></div><div class="p22-score">${state.history.length}<small>reviews passed</small></div></div><div class="p22-grid">${scenarios.map(x=>{const done=state.history.filter(h=>h.scenarioId===x.id);return `<article class="p22-card"><span>${esc(x.company)} · ${esc(x.difficulty)}</span><h3>${esc(x.title)}</h3><code>${esc(x.file)}</code><p>${esc(x.summary)}</p><button onclick="RepositorySim.start('${x.id}')">${done.length?'Review again':'Open PR'}</button>${done.length?`<small>Best ${Math.max(...done.map(d=>d.score))}/100</small>`:''}</article>`}).join('')}</div>`;return;}
    root.innerHTML=`<button class="p22-back" onclick="RepositorySim.start(null)">← Repository</button><div class="p22-review"><header><span>${esc(s.company)} · ${esc(s.difficulty)}</span><h2>${esc(s.title)}</h2><code>${esc(s.file)}</code><p>${esc(s.summary)}</p></header><pre class="p22-diff">${esc(s.diff)}</pre><h3>Review findings</h3>${s.issues.map(i=>`<div class="p22-finding ${state.selected.includes(i.id)?'selected':''}"><label><input type="checkbox" ${state.selected.includes(i.id)?'checked':''} onchange="RepositorySim.toggle('${i.id}')"> <b>${esc(i.kind)}</b> — ${esc(i.label)}</label><textarea placeholder="Write a review comment: explain the failure mode and a concrete fix…" oninput="RepositorySim.setComment('${i.id}',this.value)">${esc(state.comments[i.id]||'')}</textarea></div>`).join('')}<div class="p22-finding"><b>Test strategy</b><textarea placeholder="What regression tests should this PR add?" oninput="RepositorySim.setComment('tests',this.value)">${esc(state.comments.tests||'')}</textarea></div><div class="p22-actions"><button onclick="RepositorySim.runCI()">Run review CI</button>${state.ci?`<strong class="${state.ci.passed?'pass':'fail'}">${state.ci.score}/100 · ${state.ci.passed?'APPROVE':'CHANGES REQUESTED'}</strong>`:''}${state.ci?.passed?`<button onclick="RepositorySim.submit()">Approve & merge simulation</button>`:''}</div>${state.ci?`<aside class="p22-ci"><h3>CI review report</h3><p>Found ${state.ci.found}/${state.ci.total} seeded defects. Approval requires 75+ and substantive review comments improve the communication signal.</p>${state.ci.passed?`<p><b>Engineering takeaway:</b> ${esc(s.lesson)}</p>`:''}<details><summary>Expected regression-test themes</summary><ul>${s.tests.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></details></aside>`:''}</div>`;
  }
  window.RepositorySim={start,toggle,setComment,runCI,submit,render,state,scenarios};
  window.addEventListener('DOMContentLoaded',render);
})();