(function(C){
  'use strict';
  const CAMPAIGNS=[
    {id:'autonomous-transit',icon:'🚄',name:'Global Autonomous Transit',orgId:'nova',focus:['graphs','search'],minKnowledge:28,landmark:'world-transit-hub',reward:{money:1500,research:280},stages:[{type:'coding',title:'Map the failing corridors'},{type:'incident',title:'Stabilize the routing meltdown',incident:'routing-meltdown'},{type:'choice',title:'Choose the network doctrine',choices:[['centralize','Central control','Higher throughput, lower resilience'],['federate','Federated routing','Balanced capacity and resilience'],['edge','Edge autonomy','Local resilience, harder coordination']]},{type:'design',title:'Defend the control plane',scenario:'job-queue'},{type:'capstone',title:'Commission the global network'}]},
    {id:'cloud-migration',icon:'☁️',name:'Planetary Cloud Migration',orgId:'atlas',focus:['structures','graphs','search'],minKnowledge:36,landmark:'world-cloud-spire',reward:{money:1800,research:320},stages:[{type:'coding',title:'Inventory the migration graph'},{type:'incident',title:'Repair the latency regression',incident:'latency-regression'},{type:'choice',title:'Choose the migration architecture',choices:[['bigbang','Big-bang migration','Fastest, highest blast radius'],['waves','Regional waves','Controlled rollout'],['dual','Dual-running systems','Safest, most expensive']]},{type:'design',title:'Design the global job fabric',scenario:'job-queue'},{type:'capstone',title:'Cut over the final region'}]},
    {id:'ai-race',icon:'🧬',name:'AI Research Race',orgId:'helix',focus:['dp','arrays','search'],minKnowledge:42,landmark:'world-ai-campus',reward:{money:1700,research:440},stages:[{type:'coding',title:'Optimize the inference schedule'},{type:'incident',title:'Stop planner thrash',incident:'planner-thrash'},{type:'choice',title:'Choose the compute strategy',choices:[['scale','Scale compute','Maximum throughput'],['efficient','Algorithmic efficiency','Lower cost per result'],['edge','Distributed inference','Broader availability']]},{type:'design',title:'Design model job orchestration',scenario:'job-queue'},{type:'capstone',title:'Publish the frontier architecture'}]},
    {id:'zero-day',icon:'🛡️',name:'Zero-Day Response',orgId:'vector',focus:['hash','search','graphs'],minKnowledge:48,landmark:'world-security-vault',reward:{money:2100,research:390},stages:[{type:'coding',title:'Correlate the attack indicators'},{type:'incident',title:'Contain the dependency cascade',incident:'routing-meltdown'},{type:'choice',title:'Choose the containment posture',choices:[['isolate','Aggressive isolation','Stops spread, impacts availability'],['surgical','Surgical containment','Smaller impact, higher uncertainty'],['observe','Instrument first','More evidence, longer exposure']]},{type:'design',title:'Design resilient remediation delivery',scenario:'url-shortener'},{type:'capstone',title:'Ship the coordinated fix'}]},
    {id:'orbital-compute',icon:'🛰️',name:'Orbital Compute Network',orgId:'orbital',focus:['graphs','dp','structures'],minKnowledge:58,landmark:'world-orbital-array',reward:{money:2600,research:520},stages:[{type:'coding',title:'Plan orbital connectivity'},{type:'incident',title:'Recover the planning fabric',incident:'planner-thrash'},{type:'choice',title:'Choose the orbital topology',choices:[['mesh','Dense mesh','Resilient, expensive'],['rings','Regional rings','Predictable routing'],['hybrid','Hybrid hierarchy','Complex, efficient']]},{type:'design',title:'Design distributed command jobs',scenario:'job-queue'},{type:'capstone',title:'Activate the orbital array'}]}
  ];
  const LANDMARKS=[
    {id:'world-transit-hub',name:'Global Transit Nexus',icon:'🚄',cost:0,district:'graphs',moneyRate:12,researchRate:5,population:80,happiness:5,desc:'Campaign landmark: autonomous global transit.'},
    {id:'world-cloud-spire',name:'Planetary Cloud Spire',icon:'☁️',cost:0,district:'structures',moneyRate:16,researchRate:6,population:55,energy:-2,desc:'Campaign landmark: planetary compute fabric.'},
    {id:'world-ai-campus',name:'Frontier AI Campus',icon:'🧬',cost:0,district:'dp',researchRate:18,energy:-3,happiness:3,desc:'Campaign landmark: advanced optimization research.'},
    {id:'world-security-vault',name:'Global Security Vault',icon:'🛡️',cost:0,district:'search',moneyRate:9,researchRate:9,happiness:7,desc:'Campaign landmark: civilization-wide resilience.'},
    {id:'world-orbital-array',name:'Orbital Compute Array',icon:'🛰️',cost:0,district:'graphs',moneyRate:14,researchRate:14,energy:-4,population:40,desc:'Campaign landmark: orbital-scale distributed compute.'}
  ];
  class CampaignSystem{
    constructor(state,economy,world,generator){this.state=state;this.economy=economy;this.world=world;this.generator=generator;this.data=this.ensure();this.installLandmarks()}
    ensure(){const old=this.state.worldCampaigns||{};return this.state.worldCampaigns={version:1,active:old.active||null,completed:old.completed||[],history:old.history||[],choices:old.choices||{}}}
    installLandmarks(){if(typeof BUILDINGS==='undefined')return;for(const b of LANDMARKS)if(!BUILDINGS.some(x=>x.id===b.id))BUILDINGS.push(b)}
    def(id){return CAMPAIGNS.find(c=>c.id===id)}
    available(){return CAMPAIGNS.filter(c=>!this.data.completed.includes(c.id)&&this.economy.knowledgeIndex()>=c.minKnowledge)}
    current(){return this.data.active?.status==='active'?this.data.active:null}
    stage(){const a=this.current(),d=a&&this.def(a.id);return a&&d?d.stages[a.stage]:null}
    start(id){if(this.current())return false;const d=this.def(id);if(!d||this.data.completed.includes(id)||this.economy.knowledgeIndex()<d.minKnowledge)return false;this.data.active={id,stage:0,status:'active',startedAt:Date.now(),stageData:{},score:0};this.world.project(id,d.name,d.orgId,'active');this.world.log(`${d.name} campaign launched.`,'campaign');C.events.emit('campaign:started',{campaign:d,run:this.data.active});this.prepareStage();return true}
    prepareStage(){const a=this.current(),d=a&&this.def(a.id),s=this.stage();if(!a||!d||!s)return;if(s.type==='coding'||s.type==='capstone'){const m=this.generator.generate({orgId:d.orgId,orgName:d.name,focus:d.focus,campaignId:d.id});a.stageData={mission:m};C.events.emit('campaign:mission',{campaign:d,stage:s,mission:m})}else if(s.type==='incident'){a.stageData={incidentId:s.incident};C.events.emit('campaign:incident-ready',{campaign:d,stage:s,incidentId:s.incident})}else if(s.type==='design'){a.stageData={scenario:s.scenario};C.events.emit('campaign:design-ready',{campaign:d,stage:s,scenario:s.scenario})}else if(s.type==='choice'){a.stageData={choices:s.choices};C.events.emit('campaign:choice-ready',{campaign:d,stage:s})}}
    launchStage(){const a=this.current(),s=this.stage();if(!a||!s)return false;if(s.type==='coding'||s.type==='capstone'){const id=a.stageData.mission?.challengeId;if(!id)return false;state.current=id;persist(false);if(typeof switchTab==='function')switchTab('challenge');if(typeof render==='function')render();return true}if(s.type==='incident'){const incidents=C.game?.phase10?.incidents;if(!incidents)return false;if(!incidents.current())incidents.start(a.stageData.incidentId);C.events.emit('campaign:stage-launched',{type:'incident',id:a.stageData.incidentId});return true}if(s.type==='design'){const design=C.game?.phase9?.design;if(!design)return false;design.start(a.stageData.scenario);C.events.emit('campaign:stage-launched',{type:'design',id:a.stageData.scenario});return true}return false}
    choose(id){const a=this.current(),d=a&&this.def(a.id),s=this.stage();if(!a||s?.type!=='choice')return false;const choice=(s.choices||[]).find(x=>x[0]===id);if(!choice)return false;this.data.choices[d.id]={id,label:choice[1],at:new Date().toISOString()};a.score+=12;this.world.changeInfluence(d.orgId,2,`${choice[1]} chosen`);this.world.log(`${d.name}: ${choice[1]} strategy selected.`,'decision');this.advance('strategic decision');return true}
    onMastered(e){const a=this.current(),s=this.stage(),m=a?.stageData?.mission;if(!a||!m||(s.type!=='coding'&&s.type!=='capstone')||e.challenge?.id!==m.challengeId)return false;m.status='completed';a.score+=20+(e.first?5:0);this.world.changeInfluence('codeopolis',3,`${e.challenge.title} mastered`);this.advance('judged engineering solve');return true}
    onIncident(e){const a=this.current(),s=this.stage();if(!a||s?.type!=='incident'||e.incident?.id!==a.stageData.incidentId)return false;a.score+=Math.max(10,Math.round((e.score||60)/5));this.advance('production incident resolved');return true}
    onDesign(e){const a=this.current(),s=this.stage();if(!a||s?.type!=='design'||e.scenario?.id!==a.stageData.scenario)return false;if((e.record?.score||0)<70)return false;a.score+=Math.round((e.record.score||70)/5);this.advance('architecture defended');return true}
    advance(reason){const a=this.current(),d=a&&this.def(a.id);if(!a||!d)return;a.stage++;this.world.log(`${d.name}: stage ${a.stage}/${d.stages.length} completed — ${reason}.`,'campaign');if(a.stage>=d.stages.length)return this.finish();a.stageData={};this.prepareStage();C.events.emit('campaign:advanced',{campaign:d,run:a,reason})}
    finish(){const a=this.current(),d=a&&this.def(a.id);if(!a||!d)return null;a.status='completed';a.completedAt=Date.now();this.state.money=(this.state.money||0)+d.reward.money;this.state.research=(this.state.research||0)+d.reward.research;if(!this.state.buildings.includes(d.landmark))this.state.buildings.push(d.landmark);if(!this.data.completed.includes(d.id))this.data.completed.push(d.id);this.data.history.unshift({...a});this.data.history=this.data.history.slice(0,20);this.world.completeProject(d.id,`${d.name} campaign victory`);this.world.changeInfluence('codeopolis',8,`${d.name} completed`);this.world.advanceYear(d.name);this.data.active=null;C.events.emit('campaign:completed',{campaign:d,run:a,landmark:d.landmark});return a}
  }
  CampaignSystem.CAMPAIGNS=CAMPAIGNS;CampaignSystem.LANDMARKS=LANDMARKS;C.register('CampaignSystem',CampaignSystem);
})(window.Codeopolis);