(function(C){
  'use strict';
  class Phase14UI{
    constructor(game,world,campaigns,events){this.game=game;this.world=world;this.campaigns=campaigns;this.events=events}
    esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    ensureTab(){if(document.getElementById('worldTab'))return;const tabs=document.querySelector('.tabs');if(tabs){const b=document.createElement('button');b.dataset.tab='world';b.textContent='🌍 World';tabs.appendChild(b);b.onclick=()=>switchTab('world')}const host=document.querySelector('.panel');const d=document.createElement('div');d.id='worldTab';d.className='hidden';host.appendChild(d)}
    refresh(){this.ensureTab();const root=document.getElementById('worldTab');if(!root)return;const snap=this.world.snapshot(),active=this.campaigns.current(),stage=this.campaigns.stage(),event=this.events.current();root.innerHTML=`<div class="p14-grid"><section class="p14-card p14-map-card"><div class="section-title"><h3>🌍 Engineering World · Year ${snap.year}</h3><span class="tag">Leader: ${snap.leader.icon} ${this.esc(snap.leader.name)}</span></div><div class="p14-map">${snap.regions.map(r=>`<span class="p14-region" style="left:${r.x}%;top:${r.y}%">${this.esc(r.name)}</span>`).join('')}${snap.orgs.map(o=>`<div class="p14-node ${o.id==='codeopolis'?'player':''}" style="left:${o.x}%;top:${o.y}%"><b>${o.icon} ${this.esc(o.name)}</b><small>${o.influence} influence${o.id!=='codeopolis'?` · ${o.reputation} rep`:''}</small><i style="width:${Math.min(100,o.influence)}%"></i></div>`).join('')}</div></section>${this.renderCampaign(active,stage)}${this.renderEvent(event)}<section class="p14-card"><h3>🏁 Available campaigns</h3>${this.campaigns.available().map(c=>`<div class="p14-campaign"><b>${c.icon} ${this.esc(c.name)}</b><small>Knowledge ${c.minKnowledge}+ · ${c.focus.join(' · ')}</small><button class="btn ${active?'':'primary'}" ${active?'disabled':''} onclick="Codeopolis.game.phase14.ui.startCampaign('${c.id}')">${active?'Campaign already active':'Launch campaign'}</button></div>`).join('')||'<p class="muted">Raise your durable Knowledge Index to reveal the next world campaign.</p>'}</section><section class="p14-card"><h3>📚 World history</h3>${snap.history.map(h=>`<div class="history-item"><b>Year ${h.year}</b> · ${this.esc(h.text)}</div>`).join('')||'<p class="muted">Your world history begins with the next engineering event.</p>'}</section></div>`}
    renderCampaign(active,stage){if(!active)return`<section class="p14-card"><h3>🧭 Campaign Control</h3><p class="muted">Launch a major engineering campaign to connect coding, production incidents, architecture decisions, strategy, and a capstone into one continuous story.</p></section>`;const d=this.campaigns.def(active.id),progress=Math.round(active.stage/d.stages.length*100);let action='';if(stage.type==='choice')action=(stage.choices||[]).map(x=>`<button class="btn primary" onclick="Codeopolis.game.phase14.ui.choose('${x[0]}')"><b>${this.esc(x[1])}</b><br><small>${this.esc(x[2])}</small></button>`).join('');else action=`<button class="btn primary" onclick="Codeopolis.game.phase14.ui.launchStage()">${stage.type==='incident'?'Open incident':stage.type==='design'?'Open design lab':'Open judged mission'}</button>`;return`<section class="p14-card p14-active"><h3>${d.icon} ${this.esc(d.name)}</h3><div class="p14-progress"><i style="width:${progress}%"></i></div><p><b>Stage ${active.stage+1}/${d.stages.length}: ${this.esc(stage.title)}</b></p><p class="muted">${stage.type==='coding'||stage.type==='capstone'?this.esc(active.stageData.mission?.brief||'Adaptive judged mission'):stage.type==='incident'?'Resolve a multi-stage production incident.':stage.type==='design'?'Build and defend an architecture under real design scoring.':'Choose a strategy; the world will remember it.'}</p><div class="p14-actions">${action}</div></section>`}
    renderEvent(event){if(!event)return`<section class="p14-card"><h3>📰 World Event Desk</h3><p class="muted">Meaningful engineering actions periodically create optional world events. There are no destructive countdowns and deferring one never erases progress.</p></section>`;return`<section class="p14-card p14-event"><h3>${event.icon} ${this.esc(event.title)}</h3><p>${this.esc(event.brief)}</p><p class="muted">Adaptive response: ${this.esc(event.mission?.title||'engineering mission')}</p><button class="btn primary" onclick="Codeopolis.game.phase14.ui.openEvent()">Respond through judged challenge</button> <button class="btn" onclick="Codeopolis.game.phase14.ui.deferEvent()">Defer without penalty</button></section>`}
    startCampaign(id){if(this.campaigns.start(id)){persist(false);this.refresh()}}
    launchStage(){const type=this.campaigns.stage()?.type;if(!this.campaigns.launchStage())return;persist(false);if(type==='incident'&&typeof switchTab==='function')switchTab('ops');if(type==='design'&&typeof switchTab==='function')switchTab('engineering');if(typeof render==='function')render()}
    choose(id){if(this.campaigns.choose(id)){persist(false);if(typeof render==='function')render()}}
    openEvent(){this.events.open()}
    deferEvent(){if(this.events.defer()){persist(false);this.refresh()}}
  }
  C.register('Phase14UI',Phase14UI);
})(window.Codeopolis);