(function(C){'use strict';
const PROFILES={
 nova:{name:'Nova Robotics',bar:74,rounds:['coding','reasoning','design','behavioral'],budgets:{coding:35,reasoning:35,design:45,behavioral:30},focus:['arrays','graphs','search']},
 atlas:{name:'Atlas Cloud',bar:77,rounds:['coding','reasoning','incident','behavioral'],budgets:{coding:35,reasoning:40,incident:45,behavioral:30},focus:['graphs','search','dp']},
 helix:{name:'Helix AI',bar:78,rounds:['coding','reasoning','design','behavioral'],budgets:{coding:40,reasoning:40,design:45,behavioral:30},focus:['arrays','dp','structures']},
 vector:{name:'Vector Security',bar:80,rounds:['coding','reasoning','debug','behavioral'],budgets:{coding:35,reasoning:40,debug:40,behavioral:30},focus:['hash','structures','graphs']},
 orbital:{name:'Orbital Systems',bar:82,rounds:['coding','reasoning','incident','design','behavioral'],budgets:{coding:35,reasoning:40,incident:40,design:45,behavioral:30},focus:['graphs','search','dp']}
};
const PRESSURE={coding:['State your brute-force baseline before optimizing.','What invariant makes this loop correct?','Name the largest-input complexity before you run tests.'],reasoning:['Explain the approach without referring to code syntax.','What assumption would break this solution?','Give one adversarial edge case.'],design:['Where does backpressure live?','What fails first at 10× traffic?','Which decision is hardest to reverse?'],incident:['What is your first containment action?','Which signal would distinguish cause from symptom?','When would you roll back instead of investigate?'],debug:['What observation would falsify your current hypothesis?','What regression test proves the fix?','Could the fix create a second failure mode?'],behavioral:['What did you personally own?','What evidence shows the outcome changed?','What would you do differently now?']};
const clamp=n=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
class InterviewDay{
 constructor(game){this.game=game;this.state=game?.state||window.state||{};this.key='codeopolis-phase29-interview-day-v1';this.data=this.load()}
 load(){try{return Object.assign({active:null,history:[]},JSON.parse(localStorage.getItem(this.key)||'{}'))}catch{return{active:null,history:[]}}}
 save(){localStorage.setItem(this.key,JSON.stringify(this.data))}
 profile(id){return PROFILES[id]||PROFILES.nova}
 pool(profile){return (typeof CHALLENGES==='undefined'?[]:CHALLENGES).filter(c=>!String(c.id||'').startsWith('debug-')&&(typeof unlocked!=='function'||unlocked(c))).sort((a,b)=>{const af=profile.focus.includes(a.district)?1:0,bf=profile.focus.includes(b.district)?1:0;if(af!==bf)return bf-af;const as=(this.state.solved||[]).includes(a.id)?0:1,bs=(this.state.solved||[]).includes(b.id)?0:1;if(as!==bs)return bs-as;return String(a.id).localeCompare(String(b.id))})}
 build(profile){const p=this.pool(profile),coding=p[0],reasoning=p[1]||p[0],out=[];for(const type of profile.rounds){const r={type,title:{coding:'Coding',reasoning:'Technical Deep Dive',incident:'Production Incident',debug:'Debugging',design:'System Design',behavioral:'Behavioral'}[type],minutes:profile.budgets[type],startedAt:null,completedAt:null,score:null,pacing:null};if(type==='coding'&&coding)r.challengeId=coding.id;if(type==='reasoning'&&reasoning)r.challengeId=reasoning.id;if(type==='incident')r.scenarioId='routing-meltdown';if(type==='design')r.scenarioId='job-queue';if(type==='behavioral')r.questionIndex=1;out.push(r)}return out}
 start(profileId='nova',mode='realistic'){if(this.data.active)return{ok:false,reason:'Finish or abandon the current Interview Day first.'};if(this.game.phase18?.pipeline?.current?.())return{ok:false,reason:'Finish the active hiring loop before starting a practice Interview Day.'};const profile=this.profile(profileId),rounds=this.build(profile);if(rounds.filter(r=>r.challengeId||!['coding','reasoning'].includes(r.type)).length!==rounds.length)return{ok:false,reason:'Not enough unlocked interview content yet.'};this.data.active={id:`day-${profileId}-${Date.now()}`,profileId,company:profile.name,bar:profile.bar,mode,round:0,rounds,startedAt:Date.now(),completedAt:null,status:'active',pressureUsed:{}};this.save();C.events.emit('interview-day:started',{day:this.data.active});return{ok:true,day:this.data.active}}
 current(){return this.data.active?.status==='active'?this.data.active:null}
 round(){const d=this.current();return d?.rounds?.[d.round]||null}
 beginRound(){const r=this.round();if(r&&!r.startedAt){r.startedAt=Date.now();this.save()}return r}
 elapsedFor(r){if(!r?.startedAt)return 0;const end=r.completedAt||Date.now();return Math.max(0,(end-r.startedAt)/60000)}
 pacingScore(r){const used=this.elapsedFor(r),budget=r.minutes||1;if(this.current()?.mode==='practice')return 100;if(used<=budget*.75)return 100;if(used<=budget)return Math.round(100-(used/budget-.75)*80);return Math.max(35,Math.round(80-(used/budget-1)*45))}
 pressure(){const d=this.current(),r=this.round();if(!d||!r)return null;const key=`${d.round}:${r.type}`,used=d.pressureUsed[key]||0,list=PRESSURE[r.type]||[];const text=list[used%list.length]||'Explain your next decision and why.';d.pressureUsed[key]=used+1;this.save();return text}
 launch(){const r=this.beginRound();if(!r)return{ok:false,reason:'No active round.'};if(r.type==='coding'){if(typeof selectChallenge==='function')selectChallenge(r.challengeId);else this.state.current=r.challengeId;if(typeof switchTab==='function')switchTab('challenge');if(typeof render==='function')render();return{ok:true}}
  if(r.type==='reasoning'){const c=(typeof CHALLENGES==='undefined'?[]:CHALLENGES).find(x=>x.id===r.challengeId);if(!c)return{ok:false,reason:'Challenge unavailable.'};this.game.phase16?.director?.start?.(c);if(typeof switchTab==='function')switchTab('engineering');return{ok:true}}
  if(r.type==='incident'){const s=this.game.phase10?.incidents;if(!s)return{ok:false,reason:'Incident simulator unavailable.'};const cur=s.current?.();if(cur&&cur.id!==r.scenarioId)return{ok:false,reason:'Finish the active incident first.'};if(!cur)s.start?.(r.scenarioId);if(typeof switchTab==='function')switchTab('ops');return{ok:true}}
  if(r.type==='debug'){const s=this.game.phase9?.debugging,sc=s?.available?.()?.[0]||s?.constructor?.SCENARIOS?.[0];if(!sc)return{ok:false,reason:'Debugging scenario unavailable.'};r.scenarioId=sc.id;s.start(sc.id);if(typeof switchTab==='function')switchTab('challenge');return{ok:true}}
  if(r.type==='design'){this.game.phase9?.design?.start?.(r.scenarioId);if(typeof switchTab==='function')switchTab('engineering');return{ok:true}}
  if(r.type==='behavioral'){this.game.phase9?.behavioral?.start?.(r.questionIndex||0);if(typeof switchTab==='function')switchTab('engineering');return{ok:true}}return{ok:false,reason:'Launcher unavailable.'}}
 complete(type,score,meta={}){const d=this.current(),r=this.round();if(!d||!r||r.type!==type)return false;r.completedAt=Date.now();r.score=clamp(score);r.pacing=this.pacingScore(r);r.meta=meta;d.round++;if(d.round>=d.rounds.length)this.finish();this.save();C.events.emit('interview-day:round-complete',{day:d,round:r});return true}
 onMastered(e){const r=this.round();return r?.type==='coding'&&r.challengeId===e.challenge?.id?this.complete('coding',100,{challengeId:e.challenge.id}):false}
 onInterviewer(e){const r=this.round();return r?.type==='reasoning'&&r.challengeId===e.challenge?.id?this.complete('reasoning',e.record?.score||0,{challengeId:e.challenge.id}):false}
 onIncident(e){const r=this.round();return r?.type==='incident'&&r.scenarioId===e.incident?.id?this.complete('incident',e.score??e.incident?.score??0,{scenarioId:e.incident.id}):false}
 onDebug(e){const r=this.round();return r?.type==='debug'&&(!r.scenarioId||r.scenarioId===e.scenario?.id)?this.complete('debug',100,{scenarioId:e.scenario?.id}):false}
 onDesign(e){const r=this.round();return r?.type==='design'&&r.scenarioId===e.scenario?.id?this.complete('design',e.record?.score||0,{scenarioId:e.scenario.id}):false}
 onBehavioral(e){return this.round()?.type==='behavioral'?this.complete('behavioral',e.record?.score||0,{question:e.record?.question}):false}
 finish(){const d=this.current();if(!d)return null;const technical=d.rounds.filter(r=>r.type!=='behavioral'),behavioral=d.rounds.find(r=>r.type==='behavioral'),scores=d.rounds.map(r=>r.score||0),pacing=d.rounds.map(r=>r.pacing||0),avg=Math.round(scores.reduce((a,b)=>a+b,0)/scores.length),pace=Math.round(pacing.reduce((a,b)=>a+b,0)/pacing.length),consistency=Math.max(0,100-(Math.max(...scores)-Math.min(...scores))),overall=Math.round(avg*.72+pace*.13+consistency*.15),critical=technical.every(r=>(r.score||0)>=65)&&(!behavioral||(behavioral.score||0)>=65),verdict=critical&&overall>=d.bar?(overall>=88?'Strong Hire Calibration':'Hire Calibration'):'Below Bar';d.status='complete';d.completedAt=Date.now();d.summary={avg,pace,consistency,overall,critical,verdict,bar:d.bar,weakest:[...d.rounds].sort((a,b)=>(a.score||0)-(b.score||0))[0]?.type};this.data.history.unshift({...d});this.data.history=this.data.history.slice(0,30);this.data.active=null;this.save();C.events.emit('interview-day:finished',{day:d});return d}
 abandon(){const d=this.current();if(!d)return false;d.status='abandoned';d.completedAt=Date.now();this.data.history.unshift({...d});this.data.history=this.data.history.slice(0,30);this.data.active=null;this.save();C.events.emit('interview-day:abandoned',{day:d});return true}
}
InterviewDay.PROFILES=PROFILES;InterviewDay.PRESSURE=PRESSURE;C.register('InterviewDay',InterviewDay);})(window.Codeopolis);