(function(C){'use strict';
class Phase29UI{
 constructor(game,day){this.game=game;this.day=day;this.timer=null}
 esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 ensure(){let root=document.getElementById('phase29InterviewDay');if(root)return root;root=document.createElement('section');root.id='phase29InterviewDay';root.className='panel p29-wrap';const anchor=document.getElementById('repositorySim')||document.querySelector('.footer');anchor?.parentNode?.insertBefore(root,anchor);return root}
 format(min){const m=Math.floor(min),s=Math.floor((min-m)*60);return `${m}:${String(s).padStart(2,'0')}`}
 refresh(){const root=this.ensure();if(!root)return;const active=this.day.current();if(!active){const hist=this.day.data.history.filter(x=>x.status==='complete').slice(0,4);root.innerHTML=`<div class="p29-head"><div><h2>🎧 Interview Day</h2><p>Run a realistic end-to-end mock loop using the same authoritative coding, reasoning, incident, design, debugging, and behavioral scorers used elsewhere in Codeopolis.</p></div><span class="tag">Practice calibration</span></div><div class="p29-grid">${Object.entries(C.get('InterviewDay').PROFILES).map(([id,p])=>`<article class="p29-card"><span>${p.rounds.length} rounds · bar ${p.bar}</span><h3>${this.esc(p.name)}</h3><p>${p.rounds.map(x=>x.replace('reasoning','deep dive')).join(' → ')}</p><button class="btn primary" onclick="Codeopolis.game.phase29.ui.start('${id}','realistic')">Start realistic loop</button><button class="btn" onclick="Codeopolis.game.phase29.ui.start('${id}','practice')">Untimed practice</button></article>`).join('')}</div>${hist.length?`<h3>Recent calibration</h3><div class="p29-history">${hist.map(h=>`<div><b>${this.esc(h.company)}</b><span>${h.summary.overall}/100 · ${this.esc(h.summary.verdict)}</span><small>pacing ${h.summary.pace} · consistency ${h.summary.consistency} · weakest ${this.esc(h.summary.weakest)}</small></div>`).join('')}</div>`:''}`;this.stopTimer();return}
 const r=this.day.round(),elapsed=this.day.elapsedFor(r),over=active.mode==='realistic'&&elapsed>r.minutes;root.innerHTML=`<div class="p29-head"><div><h2>🎧 ${this.esc(active.company)} Interview Day</h2><p>Round ${active.round+1}/${active.rounds.length} · ${active.mode==='realistic'?'realistic pacing':'untimed practice'}</p></div><div class="p29-clock ${over?'over':''}">${this.format(elapsed)}<small>/ ${r.minutes}:00</small></div></div><div class="p29-rounds">${active.rounds.map((x,i)=>`<div class="${i<active.round?'done':i===active.round?'active':''}"><b>${i+1}. ${this.esc(x.title)}</b><span>${x.score!==null?`${x.score}/100 · pace ${x.pacing}`:i===active.round?'CURRENT':'UP NEXT'}</span></div>`).join('')}</div><article class="p29-current"><span>${this.esc(r.type)} · ${r.minutes} minute target</span><h3>${this.esc(r.title)}</h3><p>${this.promptFor(r.type)}</p><div class="actions"><button class="btn primary" onclick="Codeopolis.game.phase29.ui.launch()">${r.startedAt?'Return to round':'Begin round'}</button><button class="btn" onclick="Codeopolis.game.phase29.ui.pressure()">Interviewer follow-up</button><button class="btn danger" onclick="Codeopolis.game.phase29.ui.abandon()">End mock</button></div><div id="p29Pressure" class="p29-pressure">Follow-ups are coaching pressure only; they never change your score.</div></article><aside class="p29-rule"><b>Calibration rule:</b> technical correctness and existing rubrics remain authoritative. Phase 29 adds pacing and cross-round consistency to the debrief, but time never auto-fails a round.</aside>`;this.startTimer()}
 promptFor(type){return{coding:'Solve the judged problem while narrating assumptions, complexity, invariants, and tests.',reasoning:'Defend the approach, edge cases, and tradeoffs without leaning on implementation syntax.',incident:'Contain first, diagnose with evidence, then make a reversible repair and postmortem.',debug:'Form a falsifiable hypothesis, isolate the defect, fix it, and name the regression test.',design:'Clarify requirements, estimate scale, choose boundaries, and defend failure/consistency tradeoffs.',behavioral:'Use a concrete story with your ownership, decisions, evidence, impact, and reflection.'}[type]||'Complete the round with explicit reasoning.'}
 start(id,mode){const r=this.day.start(id,mode);if(!r.ok)return alert(r.reason);this.refresh()}
 launch(){const r=this.day.launch();if(!r.ok)alert(r.reason);this.refresh()}
 pressure(){const text=this.day.pressure();const el=document.getElementById('p29Pressure');if(el&&text)el.textContent=`Interviewer: “${text}”`}
 abandon(){if(this.day.abandon())this.refresh()}
 startTimer(){if(this.timer)return;this.timer=setInterval(()=>{const root=document.getElementById('phase29InterviewDay'),clock=root?.querySelector('.p29-clock');const r=this.day.round();if(!clock||!r)return;const elapsed=this.day.elapsedFor(r);clock.firstChild.nodeValue=this.format(elapsed);clock.classList.toggle('over',this.day.current()?.mode==='realistic'&&elapsed>r.minutes)},1000)}
 stopTimer(){if(this.timer){clearInterval(this.timer);this.timer=null}}
}
C.register('Phase29UI',Phase29UI);})(window.Codeopolis);