(function(C){
  'use strict';
  class Phase9UI{
    constructor(game,interviewer,debugging,design,behavioral){this.game=game;this.interviewer=interviewer;this.debugging=debugging;this.design=design;this.behavioral=behavioral;this.lastFeedback='';this.install();this.bind()}
    install(){this.ensureEngineeringTab();this.refresh()}
    ensureEngineeringTab(){const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-tab="engineering"]')){const b=document.createElement('button');b.dataset.tab='engineering';b.textContent='🧰 Engineer';tabs.appendChild(b);b.onclick=()=>switchTab('engineering')}const panel=document.querySelector('.panel');if(panel&&!document.getElementById('engineeringTab')){const d=document.createElement('div');d.id='engineeringTab';d.className='hidden';const stats=document.getElementById('statsTab');stats?.insertAdjacentElement('afterend',d)}}
    bind(){C.events.on('interviewer:evaluated',e=>{this.lastFeedback=e.turn.result.feedback;this.refresh()});C.events.on('interviewer:performance',()=>this.refresh());C.events.on('interviewer:finished',e=>{this.lastFeedback=`Interview reasoning score: ${e.record.score}/100`;this.refresh()});C.events.on('debugging:resolved',()=>this.refresh());C.events.on('design:finished',e=>{this.lastFeedback=`System design score: ${e.record.score}/100`;this.refresh()})}
    refresh(){const root=document.getElementById('engineeringTab');if(!root)return;root.innerHTML=`<div class="phase9-grid">${this.renderInterviewer()}${this.renderDebugging()}${this.renderDesign()}${this.renderBehavioral()}</div>${this.lastFeedback?`<div class="phase9-feedback">${this.lastFeedback}</div>`:''}`;this.wire(root)}
    renderInterviewer(){const s=this.interviewer.active(),c=s?CHALLENGES.find(x=>x.id===s.challengeId):null;return`<section class="phase9-card"><div class="phase9-head"><span>🎙️</span><div><h3>Reasoning Interviewer</h3><small>Freeform explanation + adaptive follow-up</small></div></div>${s?`<p><b>${c?.title||'Interview'}</b></p><p>${s.prompt}</p><textarea id="reasoningAnswer" class="phase9-text" placeholder="Explain your reasoning out loud in writing..."></textarea><button class="btn primary" data-p9="reasoning-submit">Submit reasoning</button><button class="btn" data-p9="reasoning-code">Open code</button>`:`<p class="muted">Practice the part normal judges cannot see: assumptions, invariants, edge cases, tradeoffs, and performance reasoning.</p><button class="btn primary" data-p9="reasoning-start">Interview current problem</button>`}<div class="mini-stat">Best reasoning: ${this.interviewer.data.bestReasoning||0}/100 · Responses: ${this.interviewer.data.totalResponses||0}</div></section>`}
    renderDebugging(){const scenarios=this.debugging.available();return`<section class="phase9-card"><div class="phase9-head"><span>🐛</span><div><h3>Production Debugging</h3><small>Repair realistic broken code</small></div></div>${scenarios.length?scenarios.map(s=>`<button class="phase9-row" data-debug="${s.id}"><b>${s.title}</b><small>${s.pattern} · ${s.complexity}</small></button>`).join(''):'<p>✅ All current debugging incidents resolved.</p>'}<div class="mini-stat">Resolved: ${this.debugging.data.completed.length}/${this.debugging.constructor.SCENARIOS.length}</div></section>`}
    renderDesign(){const active=this.design.data.active;if(active){const s=this.design.scenario(active.id);return`<section class="phase9-card phase9-wide"><div class="phase9-head"><span>${s.icon}</span><div><h3>${s.name}</h3><small>${s.goal}</small></div></div><div class="component-grid">${s.components.map(x=>`<button class="component ${active.selected.includes(x)?'selected':''}" data-component="${x}">${x}</button>`).join('')}</div><textarea id="designExplanation" class="phase9-text" placeholder="Explain traffic flow, data ownership, scaling, failure handling, caching/queues, and tradeoffs..."></textarea><button class="btn primary" data-p9="design-submit">Submit design</button></section>`}const S=this.design.constructor.SCENARIOS;return`<section class="phase9-card"><div class="phase9-head"><span>🏗️</span><div><h3>System Design Lab</h3><small>Build architecture, then defend it</small></div></div>${S.map(s=>`<button class="phase9-row" data-design="${s.id}"><b>${s.icon} ${s.name}</b><small>${s.goal}</small></button>`).join('')}<div class="mini-stat">Passed: ${this.design.data.completed.length}/${S.length}</div></section>`}
    renderBehavioral(){const q=this.behavioral.activeQuestion;return`<section class="phase9-card"><div class="phase9-head"><span>🗣️</span><div><h3>Behavioral Round</h3><small>STAR + ownership + measurable impact</small></div></div>${q?`<p>${q}</p><textarea id="behavioralAnswer" class="phase9-text" placeholder="Situation → Task → your Actions → Result → what you learned"></textarea><button class="btn primary" data-p9="behavioral-submit">Score answer</button>`:`<p class="muted">Practice concise stories that demonstrate judgment, ownership, conflict resolution, debugging, and growth.</p><button class="btn" data-p9="behavioral-start">Start behavioral question</button>`}<div class="mini-stat">Best: ${this.behavioral.data.best||0}/100</div></section>`}
    wire(root){root.querySelector('[data-p9="reasoning-start"]')?.addEventListener('click',()=>{this.interviewer.start(current());this.refresh()});root.querySelector('[data-p9="reasoning-submit"]')?.addEventListener('click',()=>{const text=document.getElementById('reasoningAnswer')?.value||'';if(this.interviewer.active()?.status==='performance-followup'){const rec=this.interviewer.finish(text);this.lastFeedback=rec?`Reasoning + performance score: ${rec.score}/100`:''}else this.interviewer.submit(text);persist(false);this.refresh()});root.querySelector('[data-p9="reasoning-code"]')?.addEventListener('click',()=>{const s=this.interviewer.active();if(s){state.current=s.challengeId;persist(false);switchTab('challenge')}});root.querySelectorAll('[data-debug]').forEach(b=>b.onclick=()=>{this.debugging.start(b.dataset.debug);persist(false)});root.querySelectorAll('[data-design]').forEach(b=>b.onclick=()=>{this.design.start(b.dataset.design);persist(false);this.refresh()});root.querySelectorAll('[data-component]').forEach(b=>b.onclick=()=>{this.design.toggle(b.dataset.component);persist(false);this.refresh()});root.querySelector('[data-p9="design-submit"]')?.addEventListener('click',()=>{const rec=this.design.submit(document.getElementById('designExplanation')?.value||'');this.lastFeedback=rec?`System design score: ${rec.score}/100`:'';persist(false);this.refresh()});root.querySelector('[data-p9="behavioral-start"]')?.addEventListener('click',()=>{const qs=this.behavioral.constructor.QUESTIONS;this.behavioral.start((this.behavioral.data.history.length)%qs.length);this.refresh()});root.querySelector('[data-p9="behavioral-submit"]')?.addEventListener('click',()=>{const r=this.behavioral.evaluate(document.getElementById('behavioralAnswer')?.value||'');this.lastFeedback=`Behavioral score: ${r.record.score}/100. ${r.feedback}`;persist(false);this.refresh()})}
  }
  C.register('Phase9UI',Phase9UI);
})(window.Codeopolis);
