(function(C){
  'use strict';
  class Phase20UI{
    constructor(game,programs){this.game=game;this.programs=programs;this.message='';this.lastResult=null}
    ensure(){if(document.getElementById('leadershipTab'))return;const tabs=document.querySelector('.tabs');if(tabs){const b=document.createElement('button');b.dataset.tab='leadership';b.textContent='🧭 Leadership';tabs.appendChild(b);b.onclick=()=>switchTab('leadership')}const host=document.querySelector('.panel');if(host){const d=document.createElement('div');d.id='leadershipTab';d.className='hidden';host.appendChild(d)}}
    esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    refresh(){this.ensure();const el=document.getElementById('leadershipTab');if(!el)return;const e=this.programs.employment(),gate=this.programs.eligibility(),active=this.programs.current(),lead=this.programs.readiness(),promo=this.programs.promotionGate();if(!e){el.innerHTML='<section class="p20-card"><h3>🧭 Technical Leadership</h3><p class="muted">Accept a company offer to unlock staff/principal leadership simulation.</p></section>';return}el.innerHTML=`<div class="p20-grid"><section class="p20-card p20-hero"><small>Leadership scope</small><h2>🧭 ${this.esc(e.companyName)}</h2><h3>${this.esc(e.role)}</h3><p>Leadership evidence is separate from project output. Staff/principal progression requires cross-team judgment, not just more implementation volume.</p><div class="p20-metrics"><span>Programs <b>${lead.completed}</b></span><span>Average <b>${lead.avg||0}</b></span><span>Best <b>${lead.best||0}</b></span></div></section>${active?this.renderActive(active):this.renderProgram(gate)}${this.renderReadiness(lead,promo)}${this.renderHistory()}</div>${this.message?`<div class="p20-message">${this.esc(this.message)}</div>`:''}`;this.wire()}
    renderProgram(gate){const t=this.programs.template();if(!t)return'<section class="p20-card"><p>No leadership program is configured for this employer.</p></section>';return`<section class="p20-card p20-wide"><small>Cross-team program</small><h3>${t.icon} ${this.esc(t.name)}</h3><p>${this.esc(t.brief)}</p><div class="p20-stakeholders">${t.stakeholders.map(x=>`<span class="tag">${this.esc(x)}</span>`).join(' ')}</div><p class="muted">Stages: RFC → architecture review → incident command → mentoring → roadmap decision.</p>${gate.ok?'<button class="btn primary" data-p20="start">Start leadership program</button>':`<span class="tag">${this.esc(gate.reason)}</span>`}</section>`}
    renderActive(p){const s=this.programs.currentStage();return`<section class="p20-card p20-wide"><small>Active leadership program</small><h3>${p.icon} ${this.esc(p.name)}</h3><p>${this.esc(p.brief)}</p><div class="p20-stage-list">${p.stages.map((x,i)=>{const ev=p.evidence.find(e=>e.index===i),active=i===p.stage;return`<div class="p20-stage ${ev?'done':active?'active':''}"><span>${ev?'✅':active?'▶️':'⬜'} ${this.esc(x.title)}</span><b>${ev?`${ev.score}/100`:active?'Current':''}</b></div>`}).join('')}</div>${s?this.renderCurrent(s):''}</section>`}
    renderCurrent(s){if(['rfc','mentoring','strategy'].includes(s.type)){const threshold=this.game.phase20?.evaluator?.threshold?.(s.type)||70;return`<div class="p20-current"><b>${this.esc(s.title)}</b><p>${this.esc(s.prompt)}</p><textarea id="leadershipAnswer" class="p20-text" placeholder="Write a decision another senior engineer could critique and act on..."></textarea><div><button class="btn primary" data-p20="submit">Submit evidence</button> <span class="tag">${threshold}+ required</span></div>${this.lastResult?`<div class="p20-feedback"><b>${this.lastResult.score}/100</b> · ${this.esc(this.lastResult.feedback)}</div>`:''}</div>`}const text=s.type==='design'?'Score 75+ in the existing system-design lab.':'Complete the existing engineering incident with a 70+ score while demonstrating diagnosis, repair, engineering judgment, and postmortem quality.';return`<div class="p20-current"><b>${this.esc(s.title)}</b><p class="muted">${this.esc(text)}</p><button class="btn primary" data-p20="launch">Open authoritative exercise</button></div>`}
    renderReadiness(lead,promo){return`<section class="p20-card"><small>Promotion evidence</small><h3>Staff / Principal readiness</h3><div class="p20-readiness"><div><span>${lead.readyForStaff?'✅':'⬜'} Staff leadership</span><small>1 completed program with best score 75+</small></div><div><span>${lead.readyForPrincipal?'✅':'⬜'} Principal leadership</span><small>2 programs, average 82+, best 85+</small></div></div><p class="muted">This leadership gate is additive to the Phase 19 performance-review gate.</p><span class="tag ${promo.ok?'success':''}">${this.esc(promo.ok?'Leadership promotion gate satisfied':promo.reason)}</span></section>`}
    renderHistory(){const h=this.programs.companyHistory();return`<section class="p20-card"><small>Leadership dossier</small><h3>Completed programs</h3>${h.slice(0,8).map(p=>`<div class="p20-history"><b>${p.icon} ${this.esc(p.name)}</b><span>${p.score}/100</span><small>${new Date(p.completedAt).toLocaleDateString()} · ${p.evidence.map(e=>`${e.type} ${e.score}`).join(' · ')}</small></div>`).join('')||'<p class="muted">Complete a leadership program to create durable staff/principal evidence.</p>'}</section>`}
    wire(){document.querySelector('[data-p20="start"]')?.addEventListener('click',()=>this.start());document.querySelector('[data-p20="submit"]')?.addEventListener('click',()=>this.submit());document.querySelector('[data-p20="launch"]')?.addEventListener('click',()=>this.launch())}
    save(){try{persist(false)}catch{}this.refresh()}
    start(){const r=this.programs.start();this.message=r.ok?'Leadership program started. The written and scored exercises must be completed in order.':r.reason;this.lastResult=null;this.save()}
    submit(){const text=document.getElementById('leadershipAnswer')?.value||'',r=this.programs.submitText(text);this.lastResult=r.result||null;this.message=r.ok?`Leadership evidence passed at ${r.result.score}/100.`:r.reason;this.save()}
    launch(){const r=this.programs.launch();this.message=r.ok?'Opened the existing scored engineering system for this leadership stage.':r.reason;this.save()}
  }
  C.register('Phase20UI',Phase20UI);
})(window.Codeopolis);
