(function(C){
'use strict';
class Phase21UI{
 constructor(game,programs){this.game=game;this.programs=programs;this.root=null}
 mount(){if(document.getElementById('orgTab'))return;const tabs=document.querySelector('.tabs');if(!tabs)return;const b=document.createElement('button');b.dataset.tab='org';b.textContent='🌐 Org';tabs.appendChild(b);const host=document.querySelector('section.panel');this.root=document.createElement('div');this.root.id='orgTab';this.root.className='hidden';host.appendChild(this.root);this.refresh()}
 esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 refresh(){if(!this.root)return;const p=this.programs.current(),gate=this.programs.eligible(),impact=this.programs.data.impact,score=this.programs.impactScore();let html=`<div class="section-title"><h2>🌐 Organization Influence</h2><span class="tag">Impact ${score}/100</span></div><p class="muted">Lead through other engineers: decompose objectives, delegate ownership, review technical plans, resolve dependencies, grow teammates, and validate execution.</p><div class="org-impact">${Object.entries(impact).map(([k,v])=>`<div class="card"><b>${this.esc(k)}</b><div class="progress"><i style="width:${v}%"></i></div><span>${v}/100</span></div>`).join('')}</div>`;
 if(!p){html+=`<div class="card"><h3>Next organization program</h3><p>${this.esc(gate.reason||'You have enough leadership evidence to run a multi-team program.')}</p><button class="btn primary" id="orgStart" ${gate.ok?'':'disabled'}>Start Program</button></div>`;}
 else{html+=`<div class="card"><h3>${p.icon} ${this.esc(p.name)}</h3><p>${this.esc(p.objective)}</p><span class="tag">${this.esc(p.stage)}</span></div>`;
 if(p.stage==='delegate')html+=`<div class="card"><h3>Delegate workstreams</h3>${p.workstreams.map(w=>`<label><b>${this.esc(w.team)}</b> · ${this.esc(w.role)}<select data-ws="${w.id}"><option value="">Choose owner</option>${this.programs.teammates().map(m=>{const id=m.id||m.name;return`<option value="${this.esc(id)}" ${w.owner===id?'selected':''}>${this.esc(m.name||id)} · trust ${Number(m.trust||0)}</option>`}).join('')}</select></label>`).join('')}<button class="btn primary" id="orgLock">Lock delegation</button></div>`;
 if(p.stage==='review')html+=`<div class="card"><h3>Review delegated plans</h3><p class="muted">Identify correctness/complexity risks, tests, blast radius, and concrete changes. You are reviewing—not rewriting—the teammate's implementation.</p>${p.workstreams.map(w=>w.reviewed?`<p>✅ ${this.esc(w.team)} · ${w.planScore}/100</p>`:`<div><b>${this.esc(w.team)} · ${this.esc(w.ownerName)}</b><textarea data-review="${w.id}" rows="5" placeholder="Review the proposed plan..."></textarea><button class="btn" data-submit-review="${w.id}">Submit review</button></div>`).join('')}</div>`;
 if(p.stage==='dependency')html+=this.textStage('dependency','Resolve the cross-team dependency',p.decision,'80+ words · 75+ score','orgDependency');
 if(p.stage==='develop')html+=this.textStage('development','Develop an engineering leader','Choose one delegated owner. Explain the capability gap, what ownership you will delegate next, how you will coach without taking over, milestones, evidence of growth, and escalation/safety boundaries.','70+ words · 70+ score','orgDevelopment');
 if(p.stage==='execute')html+=`<div class="card"><h3>Validate cross-team execution</h3><p>Defend the integrated architecture in the existing scored system-design lab. A score of 75+ completes the program.</p><button class="btn primary" id="orgExecute">Launch architecture defense</button></div>`;}
 const hist=this.programs.data.history||[];if(hist.length)html+=`<div class="card"><h3>Program history</h3>${hist.slice(0,6).map(x=>`<p><b>${this.esc(x.name)}</b> · ${x.score}/100 · delegation ${x.metrics?.delegation||0} · execution ${x.metrics?.execution||0}</p>`).join('')}</div>`;
 const growth=this.programs.data.npcGrowth||{};if(Object.keys(growth).length)html+=`<div class="card"><h3>Teammate growth</h3>${Object.entries(growth).map(([id,g])=>`<p>${this.esc(id)} · ${g.programs} programs · capability +${g.capability}</p>`).join('')}</div>`;
 this.root.innerHTML=html;this.bind()}
 textStage(type,title,prompt,rule,id){return`<div class="card"><h3>${title}</h3><p>${this.esc(prompt)}</p><p class="muted">${rule}</p><textarea id="${id}" rows="8"></textarea><button class="btn primary" data-text-stage="${type}">Submit decision</button></div>`}
 bind(){this.root.querySelector('#orgStart')?.addEventListener('click',()=>{const r=this.programs.start();if(!r.ok)alert(r.reason);this.refresh()});this.root.querySelectorAll('select[data-ws]').forEach(x=>x.addEventListener('change',()=>this.programs.assign(x.dataset.ws,x.value)));this.root.querySelector('#orgLock')?.addEventListener('click',()=>{const r=this.programs.lockDelegation();if(!r.ok)alert(r.reason);else alert(`Delegation quality: ${r.score}/100`);this.refresh()});this.root.querySelectorAll('[data-submit-review]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.submitReview,t=this.root.querySelector(`[data-review="${id}"]`),r=this.programs.submitReview(id,t?.value);if(!r.ok)alert(`${r.reason}${r.result?` Score ${r.result.score}/100; missing: ${r.result.missing.join(', ')}`:''}`);this.refresh()}));this.root.querySelectorAll('[data-text-stage]').forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.textStage,id=type==='dependency'?'orgDependency':'orgDevelopment',text=this.root.querySelector(`#${id}`)?.value,r=type==='dependency'?this.programs.submitDependency(text):this.programs.submitDevelopment(text);if(!r.ok)alert(`${r.reason}${r.result?` Score ${r.result.score}/100; missing: ${r.result.missing.join(', ')}`:''}`);this.refresh()}));this.root.querySelector('#orgExecute')?.addEventListener('click',()=>{const r=this.programs.launchExecution();if(!r.ok)alert(r.reason)})}
}
C.register('Phase21UI',Phase21UI);
})(window.Codeopolis);