(function(C){
  'use strict';
  class Phase19UI{
    constructor(game,team,projects,performance){this.game=game;this.team=team;this.projects=projects;this.performance=performance;this.message=''}
    ensure(){if(document.getElementById('companyTab'))return;const tabs=document.querySelector('.tabs');if(tabs){const b=document.createElement('button');b.dataset.tab='company';b.textContent='🏢 Company';tabs.appendChild(b);b.onclick=()=>switchTab('company')}const host=document.querySelector('.panel');if(host){const d=document.createElement('div');d.id='companyTab';d.className='hidden';host.appendChild(d)}}
    esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    refresh(){this.ensure();const el=document.getElementById('companyTab');if(!el)return;const employment=this.team.employment();if(!employment){el.innerHTML='<div class="p19-card"><h3>🏢 Company Life</h3><p class="muted">Complete a hiring loop and accept an offer to unlock internal teams, real project delivery, teammate collaboration, performance reviews, and promotions.</p><button class="btn primary" onclick="switchTab(\'hiring\')">Open Hiring</button></div>';return}
      const team=this.team.team(),active=this.projects.current(),review=this.performance.last(),gate=this.performance.eligible(),lenses=this.team.constructor.ROLE_LENSES;
      el.innerHTML=`<div class="p19-grid"><section class="p19-card p19-hero"><small>Current employment</small><h2>🏢 ${this.esc(employment.companyName)}</h2><h3>${this.esc(employment.role)}</h3><p>${this.esc(team?.name||'Engineering Team')}</p><div class="p19-lenses">${Object.entries(lenses).map(([id,l])=>`<button class="btn ${this.team.data.roleLens===id?'primary':''}" onclick="Codeopolis.game.phase19.ui.role('${id}')">${l.icon} ${this.esc(l.name)}</button>`).join('')}</div></section>${this.renderTeam()}${active?this.renderActive(active):this.renderBoard()}${this.renderPerformance(review,gate)}${this.renderHistory()}</div>${this.message?`<div class="p19-message">${this.esc(this.message)}</div>`:''}`}
    renderTeam(){const members=this.team.members();return`<section class="p19-card"><small>Your team</small><h3>NPC engineering partners</h3>${members.map(m=>{const r=this.team.relation(m.id);return`<article class="p19-person"><div><b>${m.icon} ${this.esc(m.name)}</b><small>${this.esc(m.role)}</small><p>${this.esc(m.lens)}</p></div><div><span class="tag">Trust ${r.trust}</span>${this.projects.current()?` <button class="btn" onclick="Codeopolis.game.phase19.ui.advice('${m.id}')">Ask for an idea</button>`:''}</div></article>`}).join('')}${this.team.data.lastAdvice?`<div class="p19-advice"><b>${this.team.data.lastAdvice.icon} ${this.esc(this.team.data.lastAdvice.name)}:</b> ${this.esc(this.team.data.lastAdvice.text)}</div>`:'<p class="muted">Advice is free context. Trust only increases when you complete the engineering stage after collaborating.</p>'}</section>`}
    renderActive(p){const s=this.projects.currentStage();return`<section class="p19-card p19-wide"><small>Active project</small><h3>${p.icon} ${this.esc(p.name)}</h3><p>${this.esc(p.brief)}</p><div class="p19-stage-list">${p.stages.map((x,i)=>{const ev=p.evidence.find(e=>e.index===i),active=i===p.stage;return`<div class="p19-stage ${ev?'done':active?'active':''}"><span>${ev?'✅':active?'▶️':'⬜'} ${this.esc(x.title)}</span><b>${ev?`${ev.score}/100`:active?'Current':''}</b></div>`}).join('')}</div>${s?`<div class="p19-current"><b>Current: ${this.esc(s.title)}</b><p class="muted">${s.type==='coding'?'Pass the real hidden tests.':s.type==='reasoning'?'Score 70+ in the structured technical review.':s.type==='incident'?'Complete the incident with a 65+ project score.':s.type==='design'?'Score 70+ in system design.':'Resolve the real debugging scenario.'}</p><button class="btn primary" onclick="Codeopolis.game.phase19.ui.launch()">Open work</button></div>`:''}</section>`}
    renderBoard(){const templates=this.projects.templates();return`<section class="p19-card p19-wide"><small>Project board</small><h3>Choose meaningful work</h3><div class="p19-projects">${templates.map(t=>`<article><div><b>${t.icon} ${this.esc(t.name)}</b><p>${this.esc(t.brief)}</p><small>${t.focus.map(x=>this.esc(x)).join(' · ')}</small></div><button class="btn primary" onclick="Codeopolis.game.phase19.ui.startProject('${t.id}')">Take ownership</button></article>`).join('')}</div></section>`}
    renderPerformance(review,gate){return`<section class="p19-card"><small>Performance</small><h3>Evidence-backed review</h3><p class="muted">A review uses completed project delivery, readiness, stage breadth, and teammate trust. No calendar waiting and no passive work XP.</p>${review?`<div class="p19-review"><b>${this.esc(review.band)} · ${review.score}/100</b><small>Delivery ${review.signals.delivery} · Readiness ${review.signals.readiness} · Breadth ${review.signals.breadth} · Team trust ${review.signals.trust}</small></div>`:''}${gate.ok?'<button class="btn primary" onclick="Codeopolis.game.phase19.ui.review()">Run performance review</button>':`<span class="tag">${this.esc(gate.reason||'More evidence required')}</span>`}${this.performance.canPromote()?` <button class="btn primary" onclick="Codeopolis.game.phase19.ui.promote()">Accept promotion → ${this.esc(this.performance.nextRole())}</button>`:''}</section>`}
    renderHistory(){const history=this.projects.data.history||[];return`<section class="p19-card"><small>Impact ledger</small><h3>Delivered projects</h3>${history.slice(0,8).map(p=>`<div class="p19-history"><b>${p.icon} ${this.esc(p.name)}</b><span>${p.score}/100</span><small>${new Date(p.completedAt).toLocaleDateString()} · ${p.evidence.map(e=>e.type).join(', ')}</small></div>`).join('')||'<p class="muted">Complete your first company project to create durable performance evidence.</p>'}</section>`}
    persist(){try{persist(false)}catch{}this.refresh()}
    role(id){if(this.team.setRoleLens(id)){this.message=`Role lens changed to ${this.team.lens().name}. Future project selection and teammate advice will reflect it.`;this.persist()}}
    advice(id){const p=this.projects.current(),s=this.projects.currentStage();const a=this.team.advice(id,p,s);this.message=a?'Teammate context added. Completing the stage is what earns collaboration trust.':'No active stage to discuss.';this.persist()}
    startProject(id){const r=this.projects.start(id);this.message=r.ok?'Project ownership accepted. Start with the first real engineering deliverable.':r.reason;this.persist()}
    launch(){const r=this.projects.launch();this.message=r.ok?'Opened the authoritative work system for this stage.':r.reason;this.persist()}
    review(){const r=this.performance.review();this.message=r.ok?`${r.review.band}: ${r.review.score}/100. ${r.review.promotionReady?'Promotion evidence is ready.':'Keep building stronger project evidence.'}`:r.reason;this.persist()}
    promote(){const r=this.performance.promote();this.message=r.ok?`Promoted from ${r.from} to ${r.to}.`:r.reason;this.persist()}
  }
  C.register('Phase19UI',Phase19UI);
})(window.Codeopolis);
