(function(C){
  'use strict';
  class Phase18UI{
    constructor(game,pipeline){this.game=game;this.pipeline=pipeline}
    esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    ensure(){if(document.getElementById('hiringTab'))return;const tabs=document.querySelector('.tabs');if(tabs&&!tabs.querySelector('[data-tab="hiring"]')){const b=document.createElement('button');b.dataset.tab='hiring';b.textContent='💼 Hiring';tabs.appendChild(b);b.onclick=()=>switchTab('hiring')}const host=document.querySelector('.panel');if(host){const d=document.createElement('div');d.id='hiringTab';d.className='hidden';host.appendChild(d)}}
    stageRow(s,i,a){const evidence=a?.evidence?.find(e=>e.index===i),current=a?.stage===i&&a.status==='active';return`<div class="hire-stage ${evidence?'done':current?'current':''}"><span>${evidence?'✅':current?'▶️':s.icon}</span><div><b>${this.esc(s.title)}</b><small>${this.esc(s.label)}</small></div><strong>${evidence?`${evidence.score}/100`:current?'Current':''}</strong></div>`}
    companyCard(c){const p=this.pipeline,available=p.available(c),cfg=p.config(c.id),last=p.data.history.find(x=>x.companyId===c.id);return`<article class="hire-company"><div class="hire-company-head"><span>${c.icon}</span><div><h3>${this.esc(c.name)}</h3><small>${this.esc(c.offer)} · focus: ${c.focus.map(x=>this.esc(x)).join(', ')}</small></div></div><p class="muted">Hiring bar ${cfg.threshold}/100${last?` · last loop ${last.score}/100 ${this.esc(last.verdict)}`:''}</p><button class="btn ${available?'primary':''}" ${available?'':'disabled'} onclick="Codeopolis.game.phase18.ui.start('${c.id}')">${available?'Start full hiring loop':'Build recruiting evidence'}</button></article>`}
    signalGrid(a){const labels={coding:'Coding',reasoning:'Reasoning',production:'Production',systems:'Systems',behavioral:'Behavioral'};return Object.entries(labels).map(([id,label])=>`<div class="hire-signal"><span>${label}</span><b>${a.signals?.[id]??'—'}</b></div>`).join('')}
    refresh(){this.ensure();const el=document.getElementById('hiringTab');if(!el)return;const p=this.pipeline,a=p.current(),offers=p.data.offers||[],history=p.data.history||[],employment=p.data.employment;let active='';if(a){const c=p.company(a.companyId),s=p.currentStage();active=`<section class="hire-card hire-active"><div class="hire-title"><div><small>Active onsite loop</small><h2>${c.icon} ${this.esc(c.name)}</h2><p>${this.esc(c.offer)} target · attempt ${a.attempt} · readiness at start ${a.readinessAtStart}/100</p></div><span class="tag">Round ${Math.min(a.stage+1,a.stages.length)}/${a.stages.length}</span></div><div class="hire-stages">${a.stages.map((x,i)=>this.stageRow(x,i,a)).join('')}</div>${s?`<div class="hire-current"><b>${s.icon} ${this.esc(s.title)}</b><p>${this.esc(s.label)}</p><button class="btn primary" onclick="Codeopolis.game.phase18.ui.launch()">Launch current round</button></div>`:''}</section>`}
      const offerHtml=offers.filter(o=>o.status==='open').map(o=>`<article class="hire-offer"><div><small>${this.esc(o.verdict)} · ${o.score}/100</small><h3>📨 ${this.esc(o.companyName)}</h3><b>${this.esc(o.role)}</b></div><div><button class="btn primary" onclick="Codeopolis.game.phase18.ui.accept('${o.id}')">Accept</button> <button class="btn" onclick="Codeopolis.game.phase18.ui.decline('${o.id}')">Decline</button></div></article>`).join('');
      const historyHtml=history.slice(0,8).map(h=>`<article class="hire-history"><div><b>${this.esc(p.company(h.companyId)?.name||h.companyId)}</b><small>${new Date(h.completedAt).toLocaleDateString()} · attempt ${h.attempt}</small></div><strong class="${h.status==='passed'?'pass':'fail'}">${this.esc(h.verdict)} · ${h.score}/100</strong><p>${this.esc(h.feedback)}</p><div class="hire-signals">${this.signalGrid(h)}</div></article>`).join('')||'<p class="muted">Complete a full hiring loop to create your first debrief.</p>';
      el.innerHTML=`<div class="hire-grid">${employment?`<section class="hire-card hire-employment"><small>Current role</small><h2>🏢 ${this.esc(employment.companyName)}</h2><b>${this.esc(employment.role)}</b><p class="muted">Offers remain optional; accepting one never deletes durable mastery or prevents future interviews.</p></section>`:''}${active}${offerHtml?`<section class="hire-card"><small>Open offers</small><h2>Offer desk</h2>${offerHtml}</section>`:''}${!a?`<section class="hire-card hire-wide"><div class="hire-title"><div><small>Company pipelines</small><h2>Run a realistic onsite</h2></div><span class="tag">Evidence-backed</span></div><p class="muted">Each company uses the same real judge and scored engineering subsystems, but emphasizes different work samples and hiring bars.</p><div class="hire-companies">${p.companies().map(c=>this.companyCard(c)).join('')}</div></section>`:''}<section class="hire-card hire-wide"><small>Debrief archive</small><h2>Hiring history</h2>${historyHtml}</section></div>`}
    start(id){const r=this.pipeline.start(id);if(!r.ok){this.game.phase6?.ui?.toast?.(r.reason);return}persist(false);this.refresh();this.game.phase15?.director?.card?.('💼','Onsite loop started',this.pipeline.company(id)?.name||'Hiring loop')}
    launch(){const r=this.pipeline.launch();if(!r.ok)this.game.phase6?.ui?.toast?.(r.reason);persist(false);this.refresh()}
    accept(id){if(this.pipeline.accept(id)){persist(false);this.refresh();this.game.phase15?.director?.card?.('🎉','Offer accepted',this.pipeline.data.employment?.role||'New role')}}
    decline(id){if(this.pipeline.decline(id)){persist(false);this.refresh()}}
  }
  C.register('Phase18UI',Phase18UI);
})(window.Codeopolis);
