(function(C){
  'use strict';
  const VERSION=1;
  function clear(scene){for(const o of scene?.__r11CrisisObjects||[])try{o?.destroy?.()}catch{}if(scene)scene.__r11CrisisObjects=[]}
  function keep(scene,o){if(o)(scene.__r11CrisisObjects||(scene.__r11CrisisObjects=[])).push(o);return o}
  function center(scene,b){return scene.iso.footprintCenter({footprint:b.footprint||{w:1,h:1}},b.x,b.y,scene.layout)}
  function drawAffected(scene,b,a){const p=center(scene,b),depth=scene.iso.depth(b.x+(b.footprint?.w||1)-1,b.y+(b.footprint?.h||1)-1,46),g=keep(scene,scene.add.graphics().setDepth(depth));const color=a.severity>=3?0xff554f:a.severity===2?0xff8a4d:0xffc857;g.lineStyle(a.severity>=3?3:2,color,.92);g.strokeEllipse(p.x,p.y-5,45+(b.footprint?.w||1)*9,18+(b.footprint?.h||1)*3);g.fillStyle(color,.16);g.fillEllipse(p.x,p.y-5,38,13);if(a.type==='grid_cascade'){g.lineStyle(2,0xffe46b,.95);g.beginPath();g.moveTo(p.x-2,p.y-40);g.lineTo(p.x+4,p.y-29);g.lineTo(p.x-1,p.y-29);g.lineTo(p.x+5,p.y-17);g.strokePath()}else if(a.type==='maintenance_cascade'){for(let i=0;i<3;i++){const puff=keep(scene,scene.add.circle(p.x-8+i*7,p.y-36-i*5,4+i,0x6b6f73,.45).setDepth(depth+1));scene.tweens?.add?.({targets:puff,y:puff.y-10,alpha:0,duration:950+i*120,repeat:-1})}}else if(a.type==='supply_breakdown'){g.lineStyle(2,0xff7f66,.9);g.beginPath();g.moveTo(p.x-10,p.y-28);g.lineTo(p.x-2,p.y-20);g.moveTo(p.x+2,p.y-28);g.lineTo(p.x+10,p.y-20);g.strokePath()}else if(a.type==='budget_emergency'){keep(scene,scene.add.text(p.x,p.y-42,'💸',{fontFamily:'system-ui',fontSize:'15px'}).setOrigin(.5,1).setDepth(depth+2))}else if(a.type==='transit_gridlock'){keep(scene,scene.add.text(p.x,p.y-39,'🚧',{fontFamily:'system-ui',fontSize:'14px'}).setOrigin(.5,1).setDepth(depth+2))}}
  function drawRoadPressure(scene,a){if(a.type!=='transit_gridlock')return;for(const [i,r] of (scene.snapshot?.roads||[]).entries()){if(i%2)continue;const p=scene.toWorld(r.x,r.y),g=keep(scene,scene.add.graphics().setDepth(scene.iso.depth(r.x,r.y,10)));g.lineStyle(3,a.severity>=3?0xf94f45:0xf3a447,.55);g.beginPath();g.moveTo(p.x-11,p.y-5);g.lineTo(p.x+11,p.y+5);g.strokePath()}}
  function banner(scene,a){if(!a.origin)return;const b=(scene.snapshot?.buildings||[]).find(x=>x.x===a.origin.x&&x.y===a.origin.y),p=b?center(scene,b):scene.toWorld(a.origin.x,a.origin.y),label=keep(scene,scene.add.text(p.x,p.y-58,`${a.icon} ${a.title} · L${a.severity}`,{fontFamily:'monospace',fontSize:'9px',fontStyle:'bold',color:'#fff4e2',backgroundColor:a.severity>=3?'#7c1f1ddd':'#5e3126dd',padding:{x:5,y:3}}).setOrigin(.5,1).setDepth(10060));scene.tweens?.add?.({targets:label,y:label.y-3,duration:700,yoyo:true,repeat:-1})}
  function render(scene){clear(scene);const state=C.game?.state||window.state,active=C.CityCrisisSystem?.summary?.(state,scene.world)?.active;if(!active)return null;const buildings=scene.snapshot?.buildings||[];for(const target of active.affected||[]){const b=buildings.find(x=>x.x===target.x&&x.y===target.y);if(b)drawAffected(scene,b,active)}drawRoadPressure(scene,active);banner(scene,active);return active}
  function focusResolved(scene,record){if(!scene||!record?.origin)return;const p=scene.toWorld(record.origin.x,record.origin.y);scene.cameras?.main?.pan?.(p.x,p.y,420,'Sine.easeInOut');const burst=keep(scene,scene.add.circle(p.x,p.y-18,5,0x8ef0b4,.8).setDepth(10080));scene.tweens?.add?.({targets:burst,scale:5,alpha:0,duration:700,onComplete:()=>burst.destroy?.()})}
  function install(){const Scene=C.PhaserCityScene;if(!Scene?.prototype)return false;if(Scene.prototype.__r11CrisisVisuals)return true;Scene.prototype.__r11CrisisVisuals=true;const original=Scene.prototype.renderWorld;Scene.prototype.renderWorld=function(){const out=original.apply(this,arguments);render(this);return out};if(!install._events){install._events=true;for(const e of['city-crisis:triggered','city-crisis:escalated','city-crisis:stabilized'])C.events?.on?.(e,()=>setTimeout(()=>C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')?.refresh?.(),0));C.events?.on?.('city-crisis:resolved',e=>setTimeout(()=>{const s=C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity');s?.refresh?.();setTimeout(()=>focusResolved(s,e.crisis),25)},0))}const scene=C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity');if(scene)render(scene);C.events?.emit?.('r11:crisis-visuals-ready',{version:VERSION});return true}
  C.CrisisVisuals={VERSION,clear,render,focusResolved,install};
})(window.Codeopolis);
