(function(C){
  'use strict';
  const CAMERA_URL='src/civilization/phaser/mobile-camera-controller.js',AGE_URL='src/progression/age-progression.js',TECH_URL='src/progression/technology-tree.js',RETENTION_URL='src/progression/knowledge-retention.js',TRANSFER_URL='src/progression/transfer-generalization.js',INTERLEAVE_URL='src/progression/interleaved-practice.js',READINESS_URL='src/progression/interview-readiness.js',P2_INTEGRATION_URL='src/progression/p2-integration.js',ADAPTIVE_URL='src/progression/adaptive-challenge-selector.js',OBJECTIVES_URL='src/progression/learning-objectives.js',ANALYTICS_URL='src/progression/learning-analytics.js',SPECIALIZATION_URL='src/progression/civilization-specialization.js',MASTERY_GATES_URL='src/progression/mastery-building-gates.js',LEARNING_CITY_URL='src/progression/learning-city-loop.js',LEARNING_NAV_UI_URL='src/progression/city-learning-navigator-ui.js',LEARNING_MAP_URL='src/progression/city-learning-map-beacon.js';
  function activeView(){return document.querySelector('#codeopolisIonicShell')?.dataset.view||document.querySelector('.tabs button.active[data-tab]')?.dataset.tab||'challenge'}
  function syncLifecycle(){const p=C.phaserCity;if(!p)return;const active=activeView()==='city';p.setActive?.(active);p.host.style.visibility=active?'visible':'hidden';p.host.style.pointerEvents=active?'auto':'none';if(active)requestAnimationFrame(()=>{C.get?.('Phase44MobileCamera')?.resize?.();p.learningNavigator?.render?.()})}
  function watchViews(){const shell=document.querySelector('#codeopolisIonicShell');if(shell)new MutationObserver(syncLifecycle).observe(shell,{attributes:true,attributeFilter:['data-view']});const tabs=document.querySelector('.tabs');if(tabs)new MutationObserver(syncLifecycle).observe(tabs,{subtree:true,attributes:true,attributeFilter:['class']});document.addEventListener('click',e=>{if(e.target.closest?.('[data-tab]'))requestAnimationFrame(syncLifecycle)},true);document.addEventListener('visibilitychange',()=>{if(document.hidden)C.phaserCity?.setActive?.(false);else syncLifecycle()})}
  function loadScript(src,flag,ready){return new Promise((resolve,reject)=>{if(ready())return resolve();const old=document.querySelector(`script[data-${flag}="1"]`);if(old){if(ready())return resolve();old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.dataset[flag.replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  const loadCamera=()=>loadScript(CAMERA_URL,'phase44-camera',()=>!!C.get?.('Phase44MobileCamera'));
  const loadAge=()=>loadScript(AGE_URL,'phase44-age',()=>!!C.AgeProgression);
  const loadTech=()=>loadScript(TECH_URL,'phase44-tech',()=>!!C.TechnologyTree);
  const loadRetention=()=>loadScript(RETENTION_URL,'phase44-retention',()=>!!C.KnowledgeRetention);
  const loadTransfer=()=>loadScript(TRANSFER_URL,'phase44-transfer',()=>!!C.TransferGeneralization);
  const loadInterleaving=()=>loadScript(INTERLEAVE_URL,'phase44-interleaving',()=>!!C.InterleavedPractice);
  const loadReadiness=()=>loadScript(READINESS_URL,'phase44-readiness',()=>!!C.InterviewReadiness);
  const loadP2Integration=()=>loadScript(P2_INTEGRATION_URL,'phase44-p2-integration',()=>!!C.P2Integration);
  const loadAdaptive=()=>loadScript(ADAPTIVE_URL,'phase44-adaptive',()=>!!C.AdaptiveChallengeSelector);
  const loadObjectives=()=>loadScript(OBJECTIVES_URL,'phase44-objectives',()=>!!C.LearningObjectives);
  const loadAnalytics=()=>loadScript(ANALYTICS_URL,'phase44-learning-analytics',()=>!!C.LearningAnalytics);
  const loadSpecialization=()=>loadScript(SPECIALIZATION_URL,'phase44-civilization-specialization',()=>!!C.CivilizationSpecialization);
  const loadMasteryGates=()=>loadScript(MASTERY_GATES_URL,'phase44-mastery-gates',()=>!!C.MasteryBuildingGates);
  const loadLearningCity=()=>loadScript(LEARNING_CITY_URL,'phase44-learning-city',()=>!!C.LearningCityLoop);
  const loadLearningNavigatorUI=()=>loadScript(LEARNING_NAV_UI_URL,'phase44-learning-navigator-ui',()=>!!C.CityLearningNavigatorUI);
  const loadLearningMap=()=>loadScript(LEARNING_MAP_URL,'phase44-learning-map',()=>!!C.CityLearningMapBeacon);
  async function installExtras(world,state){try{await loadCamera();C.get('Phase44MobileCamera')?.install?.()}catch(e){console.warn('Phase 44 mobile camera unavailable',e)}try{await loadAge();C.AgeProgression?.install?.(state,world)}catch(e){console.warn('Phase 44 age progression unavailable',e)}try{await loadTech();C.TechnologyTree?.install?.(state)}catch(e){console.warn('Phase 44 technology tree unavailable',e)}try{await loadRetention();C.KnowledgeRetention?.install?.(state)}catch(e){console.warn('Phase 44 knowledge retention unavailable',e)}try{await loadTransfer();C.TransferGeneralization?.install?.(state)}catch(e){console.warn('Phase 44 transfer generalization unavailable',e)}try{await loadInterleaving();C.InterleavedPractice?.install?.(state)}catch(e){console.warn('Phase 44 interleaved practice unavailable',e)}try{await loadReadiness();C.InterviewReadiness?.install?.(state)}catch(e){console.warn('Phase 44 interview readiness unavailable',e)}try{await loadP2Integration();C.P2Integration?.install?.(state)}catch(e){console.warn('Phase 44 P2 integration unavailable',e)}try{await loadAdaptive();C.AdaptiveChallengeSelector?.install?.(state,world)}catch(e){console.warn('Phase 44 adaptive challenge selector unavailable',e)}try{await loadObjectives();C.LearningObjectives?.install?.(state,world)}catch(e){console.warn('Phase 44 learning objectives unavailable',e)}try{await loadAnalytics();C.LearningAnalytics?.install?.(state,world)}catch(e){console.warn('Phase 44 learning analytics unavailable',e)}try{await loadSpecialization();C.CivilizationSpecialization?.install?.(state,world)}catch(e){console.warn('Phase 44 civilization specialization unavailable',e)}try{await loadMasteryGates();C.MasteryBuildingGates?.install?.()}catch(e){console.warn('Phase 44 mastery building gates unavailable',e)}try{await loadLearningCity();C.LearningCityLoop?.install?.(state,world)}catch(e){console.warn('Phase 44 learning city loop unavailable',e)}try{await loadLearningMap();C.CityLearningMapBeacon?.install?.()}catch(e){console.warn('Phase 44 city learning map beacon unavailable',e)}try{await loadLearningNavigatorUI();if(C.phaserCity&&!C.phaserCity.learningNavigator)C.phaserCity.learningNavigator=new C.CityLearningNavigatorUI(C.phaserCity.host,state,world)}catch(e){console.warn('Phase 44 city learning navigator unavailable',e)}}
  async function start(){watchViews();let tries=0;const timer=setInterval(async()=>{tries++;if(C.phaserCity){clearInterval(timer);syncLifecycle();await installExtras(C.game?.world,typeof state!=='undefined'?state:C.game?.state);return}const boot=C.get?.('PhaserCivilizationBootstrap'),world=C.game?.world;if(boot&&world&&typeof state!=='undefined'){clearInterval(timer);const ok=await boot.start(world,state);if(ok){syncLifecycle();await installExtras(world,state)}return}if(tries>80)clearInterval(timer)},125)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})(window.Codeopolis);
