(function(C){
  'use strict';
  const INFRA_URL='src/civilization/infrastructure-network.js',POP_URL='src/civilization/population-simulation.js',OPS_URL='src/civilization/building-operations.js',OPS_VISUAL_URL='src/civilization/phaser/operation-visuals.js',ZONE_URL='src/civilization/district-zoning.js',ZONE_UI_URL='src/civilization/district-zoning-ui.js',ZONE_VISUAL_URL='src/civilization/phaser/district-zoning-visuals.js',SUPPLY_MODEL_URL='src/civilization/city-supply-model.js',SUPPLY_RUNTIME_URL='src/civilization/city-supply-runtime.js',SUPPLY_CHAIN_URL='src/civilization/city-supply-chain.js',ECON_UI_URL='src/civilization/city-economy-ui.js',SUPPLY_VISUAL_URL='src/civilization/phaser/supply-chain-visuals.js',AGE_CITY_URL='src/civilization/phaser/age-city-transformation.js',CRISIS_URL='src/civilization/city-crisis-system.js',CRISIS_UI_URL='src/civilization/city-crisis-ui.js',CRISIS_VISUAL_URL='src/civilization/phaser/crisis-visuals.js';
  function load(src,attr,ready,done){if(ready()){done?.();return}const old=document.querySelector(`script[${attr}="1"]`);if(old){old.addEventListener('load',done,{once:true});return}const s=document.createElement('script');s.src=src;s.setAttribute(attr,'1');s.onload=()=>done?.();document.head.appendChild(s)}
  function ensureInfrastructure(done){load(INFRA_URL,'data-r5-infrastructure',()=>!!C.InfrastructureNetwork,()=>{C.InfrastructureNetwork?.install?.();done?.()})}
  function ensurePopulation(done){load(POP_URL,'data-r6-population',()=>!!C.PopulationSimulation,()=>{C.PopulationSimulation?.install?.(C.game?.state||window.state,C.game?.world);done?.()})}
  function ensureOperations(done){load(OPS_URL,'data-r7-operations',()=>!!C.BuildingOperations,()=>{C.BuildingOperations?.install?.(C.game?.state||window.state,C.game?.world);load(OPS_VISUAL_URL,'data-r7-operation-visuals',()=>!!C.OperationVisuals,()=>{C.OperationVisuals?.install?.();done?.()})})}
  function attachZoningUI(){const p=C.phaserCity,scene=p?.game?.scene?.getScene?.('CodeopolisCity'),state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!scene||!state||!world||!C.DistrictZoningUI)return false;C.DistrictZoning?.install?.(state,world);if(!p.zoning)p.zoning=new C.DistrictZoningUI(p.host,world,scene,state);p.zoning.render?.();scene.refresh?.();return true}
  function ensureZoning(done){load(ZONE_URL,'data-r8-zoning',()=>!!C.DistrictZoning,()=>{C.DistrictZoning?.install?.(C.game?.state||window.state,C.game?.world);load(ZONE_VISUAL_URL,'data-r8-zoning-visuals',()=>!!C.DistrictZoningVisuals,()=>{C.DistrictZoningVisuals?.install?.();load(ZONE_UI_URL,'data-r8-zoning-ui',()=>!!C.DistrictZoningUI,()=>{if(!attachZoningUI()){C.events?.on?.('civilization:phaser-ready',()=>attachZoningUI());setTimeout(()=>attachZoningUI(),250)}done?.()})})})}
  function attachEconomyUI(){const p=C.phaserCity,state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!state||!world||!C.CityEconomyUI)return false;C.CitySupplyChain?.install?.(state,world);if(!p.economy)p.economy=new C.CityEconomyUI(p.host,world,state);p.economy.render?.();return true}
  function ensureEconomy(done){load(SUPPLY_MODEL_URL,'data-r9-supply-model',()=>!!C.CitySupplyModel,()=>load(SUPPLY_RUNTIME_URL,'data-r9-supply-runtime',()=>!!C.CitySupplyRuntime,()=>load(SUPPLY_CHAIN_URL,'data-r9-supply-chain',()=>!!C.CitySupplyChain,()=>{C.CitySupplyChain?.install?.(C.game?.state||window.state,C.game?.world);load(SUPPLY_VISUAL_URL,'data-r9-supply-visuals',()=>!!C.SupplyChainVisuals,()=>{C.SupplyChainVisuals?.install?.();load(ECON_UI_URL,'data-r9-economy-ui',()=>!!C.CityEconomyUI,()=>{if(!attachEconomyUI()){C.events?.on?.('civilization:phaser-ready',()=>attachEconomyUI());setTimeout(()=>attachEconomyUI(),300)}done?.()})})})))}
  function ensureAgeCity(done){load(AGE_CITY_URL,'data-r10-age-city',()=>!!C.AgeCityTransformation,()=>{C.AgeCityTransformation?.install?.(C.game?.state||window.state,C.game?.world);done?.()})}
  function attachCrisisUI(){const p=C.phaserCity,state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!state||!world||!C.CityCrisisUI)return false;C.CityCrisisSystem?.install?.(state,world);if(!p.crises)p.crises=new C.CityCrisisUI(p.host,state,world);p.crises.render?.();return true}
  function ensureCrises(done){load(CRISIS_URL,'data-r11-crisis',()=>!!C.CityCrisisSystem,()=>{C.CityCrisisSystem?.install?.(C.game?.state||window.state,C.game?.world);load(CRISIS_VISUAL_URL,'data-r11-crisis-visuals',()=>!!C.CrisisVisuals,()=>{C.CrisisVisuals?.install?.();load(CRISIS_UI_URL,'data-r11-crisis-ui',()=>!!C.CityCrisisUI,()=>{if(!attachCrisisUI()){C.events?.on?.('civilization:phaser-ready',()=>attachCrisisUI());setTimeout(()=>attachCrisisUI(),300)}done?.()})})})}
  function drawInfrastructure(scene){const net=scene.world?.infrastructureNetwork?.();if(!net||!scene.iso)return;for(const comp of net.components){const powered=net.poweredComponents.includes(comp.id);for(const r of comp.cells){const p=scene.toWorld(r.x,r.y),g=scene.add.graphics().setDepth(scene.iso.depth(r.x,r.y,7));g.lineStyle(powered?2:1,powered?0xffdf72:0x6c8d8b,powered?.72:.35);g.strokeEllipse(p.x,p.y,34,12);if(powered){g.fillStyle(0xffed99,.42);g.fillCircle(p.x,p.y,2)}}}for(const b of scene.snapshot?.buildings||[]){const s=scene.world.buildingServiceStatus?.(b.x,b.y);if(!s||s.efficiency>=.995)continue;const p=scene.iso.footprintCenter({footprint:b.footprint||{w:1,h:1}},b.x,b.y,scene.layout),icons=[];if(!s.roadConnected)icons.push('🛣');if(s.powerDemand&&!s.powerConnected)icons.push('⚡');else if(s.infrastructure?.powerRatio<.999&&s.powerDemand)icons.push('⚡');if(s.city?.workerRatio<.999&&s.workerDemand)icons.push('👷');if(s.city?.housingRatio<.999)icons.push('🏠');if(icons.length)scene.add.text(p.x,p.y-48,`${icons.join('')} ${Math.round(s.efficiency*100)}%`,{fontFamily:'monospace',fontSize:'8px',color:'#ffe2bf',backgroundColor:'#58351fdd',padding:{x:3,y:2}}).setOrigin(.5,1).setDepth(10020)}}
  function install(){const Scene=C.PhaserCityScene;if(!Scene||Scene.prototype.__p1eServiceVisuals)return false;Scene.prototype.__p1eServiceVisuals=true;const original=Scene.prototype.renderWorld;Scene.prototype.renderWorld=function(){original.apply(this,arguments);C.InfrastructureNetwork?.install?.();drawInfrastructure(this)};ensureInfrastructure(()=>C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')?.refresh?.());ensurePopulation(()=>C.PopulationSimulation?.renderHud?.(C.game?.state||window.state,C.game?.world));ensureOperations(()=>C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')?.refresh?.());ensureZoning(()=>ensureEconomy(()=>ensureAgeCity(()=>ensureCrises(()=>C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')?.refresh?.()))));return true}
  C.ServiceVisuals={install,drawInfrastructure,ensureInfrastructure,ensurePopulation,ensureOperations,ensureZoning,ensureEconomy,ensureAgeCity,ensureCrises,attachZoningUI,attachEconomyUI,attachCrisisUI};
})(window.Codeopolis);
