(function(C){
  'use strict';
  const INFRA_URL='src/civilization/infrastructure-network.js',POP_URL='src/civilization/population-simulation.js',OPS_URL='src/civilization/building-operations.js',OPS_VISUAL_URL='src/civilization/phaser/operation-visuals.js',ZONE_URL='src/civilization/district-zoning.js',ZONE_UI_URL='src/civilization/district-zoning-ui.js',ZONE_VISUAL_URL='src/civilization/phaser/district-zoning-visuals.js',SUPPLY_MODEL_URL='src/civilization/city-supply-model.js',SUPPLY_RUNTIME_URL='src/civilization/city-supply-runtime.js',SUPPLY_CHAIN_URL='src/civilization/city-supply-chain.js',ECON_UI_URL='src/civilization/city-economy-ui.js',SUPPLY_VISUAL_URL='src/civilization/phaser/supply-chain-visuals.js',AGE_CITY_URL='src/civilization/phaser/age-city-transformation.js',CRISIS_URL='src/civilization/city-crisis-system.js',CRISIS_UI_URL='src/civilization/city-crisis-ui.js',CRISIS_VISUAL_URL='src/civilization/phaser/crisis-visuals.js',CUSTOM_URL='src/civilization/world-customization.js',CUSTOM_UI_URL='src/civilization/world-customization-ui.js',CUSTOM_VISUAL_URL='src/civilization/phaser/world-customization-visuals.js',CAMPAIGN_URL='src/progression/interview-city-campaign.js',CAMPAIGN_UI_URL='src/progression/interview-city-campaign-ui.js',CAMPAIGN_VISUAL_URL='src/civilization/phaser/interview-campaign-visuals.js';
  function load(src,attr,ready,done){if(ready()){done?.();return}const old=document.querySelector(`script[${attr}="1"]`);if(old){old.addEventListener('load',done,{once:true});return}const s=document.createElement('script');s.src=src;s.setAttribute(attr,'1');s.onload=()=>done?.();document.head.appendChild(s)}
  function scene(){return C.phaserCity?.game?.scene?.getScene?.('CodeopolisCity')}
  function ensureInfrastructure(done){load(INFRA_URL,'data-r5-infrastructure',()=>!!C.InfrastructureNetwork,()=>{C.InfrastructureNetwork?.install?.();done?.()})}
  function ensurePopulation(done){load(POP_URL,'data-r6-population',()=>!!C.PopulationSimulation,()=>{C.PopulationSimulation?.install?.(C.game?.state||window.state,C.game?.world);done?.()})}
  function ensureOperations(done){load(OPS_URL,'data-r7-operations',()=>!!C.BuildingOperations,()=>{C.BuildingOperations?.install?.(C.game?.state||window.state,C.game?.world);load(OPS_VISUAL_URL,'data-r7-operation-visuals',()=>!!C.OperationVisuals,()=>{C.OperationVisuals?.install?.();done?.()})})}
  function attachZoningUI(){const p=C.phaserCity,s=scene(),state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!s||!state||!world||!C.DistrictZoningUI)return false;C.DistrictZoning?.install?.(state,world);if(!p.zoning)p.zoning=new C.DistrictZoningUI(p.host,world,s,state);p.zoning.render?.();s.refresh?.();return true}
  function ensureZoning(done){load(ZONE_URL,'data-r8-zoning',()=>!!C.DistrictZoning,()=>{C.DistrictZoning?.install?.(C.game?.state||window.state,C.game?.world);load(ZONE_VISUAL_URL,'data-r8-zoning-visuals',()=>!!C.DistrictZoningVisuals,()=>{C.DistrictZoningVisuals?.install?.();load(ZONE_UI_URL,'data-r8-zoning-ui',()=>!!C.DistrictZoningUI,()=>{if(!attachZoningUI()){C.events?.on?.('civilization:phaser-ready',()=>attachZoningUI());setTimeout(()=>attachZoningUI(),250)}done?.()})})})}
  function attachEconomyUI(){const p=C.phaserCity,state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!state||!world||!C.CityEconomyUI)return false;C.CitySupplyChain?.install?.(state,world);if(!p.economy)p.economy=new C.CityEconomyUI(p.host,world,state);p.economy.render?.();return true}
  function ensureEconomy(done){load(SUPPLY_MODEL_URL,'data-r9-supply-model',()=>!!C.CitySupplyModel,()=>load(SUPPLY_RUNTIME_URL,'data-r9-supply-runtime',()=>!!C.CitySupplyRuntime,()=>load(SUPPLY_CHAIN_URL,'data-r9-supply-chain',()=>!!C.CitySupplyChain,()=>{C.CitySupplyChain?.install?.(C.game?.state||window.state,C.game?.world);load(SUPPLY_VISUAL_URL,'data-r9-supply-visuals',()=>!!C.SupplyChainVisuals,()=>{C.SupplyChainVisuals?.install?.();load(ECON_UI_URL,'data-r9-economy-ui',()=>!!C.CityEconomyUI,()=>{if(!attachEconomyUI()){C.events?.on?.('civilization:phaser-ready',()=>attachEconomyUI());setTimeout(()=>attachEconomyUI(),300)}done?.()})})})))}
  function ensureAgeCity(done){load(AGE_CITY_URL,'data-r10-age-city',()=>!!C.AgeCityTransformation,()=>{C.AgeCityTransformation?.install?.(C.game?.state||window.state,C.game?.world);done?.()})}
  function attachCrisisUI(){const p=C.phaserCity,state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!state||!world||!C.CityCrisisUI)return false;C.CityCrisisSystem?.install?.(state,world);if(!p.crises)p.crises=new C.CityCrisisUI(p.host,state,world);p.crises.render?.();return true}
  function ensureCrises(done){load(CRISIS_URL,'data-r11-crisis',()=>!!C.CityCrisisSystem,()=>{C.CityCrisisSystem?.install?.(C.game?.state||window.state,C.game?.world);load(CRISIS_VISUAL_URL,'data-r11-crisis-visuals',()=>!!C.CrisisVisuals,()=>{C.CrisisVisuals?.install?.();load(CRISIS_UI_URL,'data-r11-crisis-ui',()=>!!C.CityCrisisUI,()=>{if(!attachCrisisUI()){C.events?.on?.('civilization:phaser-ready',()=>attachCrisisUI());setTimeout(()=>attachCrisisUI(),300)}done?.()})})})}
  function attachCustomizationUI(){const p=C.phaserCity,s=scene(),state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!s||!state||!world||!C.WorldCustomizationUI)return false;C.WorldCustomization?.install?.(state,world);if(!p.customization)p.customization=new C.WorldCustomizationUI(p.host,state,world,s);p.customization.render?.();return true}
  function ensureCustomization(done){load(CUSTOM_URL,'data-r12-customization',()=>!!C.WorldCustomization,()=>{C.WorldCustomization?.install?.(C.game?.state||window.state,C.game?.world);load(CUSTOM_VISUAL_URL,'data-r12-customization-visuals',()=>!!C.WorldCustomizationVisuals,()=>{C.WorldCustomizationVisuals?.install?.();load(CUSTOM_UI_URL,'data-r12-customization-ui',()=>!!C.WorldCustomizationUI,()=>{if(!attachCustomizationUI()){C.events?.on?.('civilization:phaser-ready',()=>attachCustomizationUI());setTimeout(()=>attachCustomizationUI(),300)}done?.()})})})}
  function campaignDependencies(){return !!(C.InterviewReadiness&&C.AdaptiveChallengeSelector&&C.LearningCityLoop)}
  function attachCampaignUI(tries=0){const p=C.phaserCity,state=C.game?.state||window.state,world=C.game?.world;if(!p?.host||!state||!world||!C.InterviewCityCampaignUI||!campaignDependencies()){if(tries<40)setTimeout(()=>attachCampaignUI(tries+1),250);return false}C.InterviewCityCampaign?.install?.(state,world);if(!p.campaign)p.campaign=new C.InterviewCityCampaignUI(p.host,state,world);p.campaign.render?.();scene()?.refresh?.();return true}
  function ensureCampaign(done){load(CAMPAIGN_URL,'data-r13-campaign',()=>!!C.InterviewCityCampaign,()=>{load(CAMPAIGN_VISUAL_URL,'data-r13-campaign-visuals',()=>!!C.InterviewCampaignVisuals,()=>{C.InterviewCampaignVisuals?.install?.();load(CAMPAIGN_UI_URL,'data-r13-campaign-ui',()=>!!C.InterviewCityCampaignUI,()=>{attachCampaignUI();done?.()})})})}
  function drawInfrastructure(s){const net=s.world?.infrastructureNetwork?.();if(!net||!s.iso)return;/* Powered is the normal state, so it gets no marker at all. This used to stamp a bright gold ring on every powered cell, and because the power network follows the roads that meant a ring on every road tile — the loudest thing on the map, permanently, over the art. Only the actionable state (a cell with no power) is marked now, and quietly. */for(const comp of net.components){if(net.poweredComponents.includes(comp.id))continue;for(const r of comp.cells){const p=s.toWorld(r.x,r.y),g=s.add.graphics().setDepth(s.iso.depth(r.x,r.y,7));g.fillStyle(0x6c8d8b,.28);g.fillEllipse(p.x,p.y,22,10)}}for(const b of s.snapshot?.buildings||[]){const st=s.world.buildingServiceStatus?.(b.x,b.y);/* Only flag a real shortfall, not rounding. At >=.995 every healthy building printed a badge over the art. */if(!st||st.efficiency>=.9)continue;const p=s.iso.footprintCenter({footprint:b.footprint||{w:1,h:1}},b.x,b.y,s.layout),icons=[];if(!st.roadConnected)icons.push('🛣');if(st.powerDemand&&!st.powerConnected)icons.push('⚡');else if(st.infrastructure?.powerRatio<.999&&st.powerDemand)icons.push('⚡');if(st.city?.workerRatio<.999&&st.workerDemand)icons.push('👷');if(st.city?.housingRatio<.999)icons.push('🏠');if(icons.length)s.add.text(p.x,p.y-48,`${icons.join('')} ${Math.round(st.efficiency*100)}%`,{fontFamily:'monospace',fontSize:'8px',color:'#ffe2bf',backgroundColor:'#58351fdd',padding:{x:3,y:2}}).setOrigin(.5,1).setDepth(10020)}}
  function install(){const Scene=C.PhaserCityScene;if(!Scene||Scene.prototype.__p1eServiceVisuals)return false;Scene.prototype.__p1eServiceVisuals=true;const original=Scene.prototype.renderWorld;Scene.prototype.renderWorld=function(){original.apply(this,arguments);C.InfrastructureNetwork?.install?.();drawInfrastructure(this)};ensureInfrastructure(()=>scene()?.refresh?.());ensurePopulation(()=>C.PopulationSimulation?.renderHud?.(C.game?.state||window.state,C.game?.world));ensureOperations(()=>scene()?.refresh?.());ensureZoning(()=>ensureEconomy(()=>ensureAgeCity(()=>ensureCrises(()=>ensureCustomization(()=>ensureCampaign(()=>scene()?.refresh?.()))))));return true}
  C.ServiceVisuals={install,drawInfrastructure,ensureInfrastructure,ensurePopulation,ensureOperations,ensureZoning,ensureEconomy,ensureAgeCity,ensureCrises,ensureCustomization,ensureCampaign,attachZoningUI,attachEconomyUI,attachCrisisUI,attachCustomizationUI,attachCampaignUI};
})(window.Codeopolis);
